// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class ReloadCitiesRequestProto;
@class ReloadCitiesRequestProto_Builder;
@class ReloadEquipmentRequestProto;
@class ReloadEquipmentRequestProto_Builder;
@class ReloadTaskEquipmentRequirementsRequestProto;
@class ReloadTaskEquipmentRequirementsRequestProto_Builder;
@class ReloadTaskRequestProto;
@class ReloadTaskRequestProto_Builder;

@interface AdminRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface ReloadCitiesRequestProto : PBGeneratedMessage {
@private
}

+ (ReloadCitiesRequestProto*) defaultInstance;
- (ReloadCitiesRequestProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ReloadCitiesRequestProto_Builder*) builder;
+ (ReloadCitiesRequestProto_Builder*) builder;
+ (ReloadCitiesRequestProto_Builder*) builderWithPrototype:(ReloadCitiesRequestProto*) prototype;

+ (ReloadCitiesRequestProto*) parseFromData:(NSData*) data;
+ (ReloadCitiesRequestProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReloadCitiesRequestProto*) parseFromInputStream:(NSInputStream*) input;
+ (ReloadCitiesRequestProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReloadCitiesRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ReloadCitiesRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ReloadCitiesRequestProto_Builder : PBGeneratedMessage_Builder {
@private
  ReloadCitiesRequestProto* result;
}

- (ReloadCitiesRequestProto*) defaultInstance;

- (ReloadCitiesRequestProto_Builder*) clear;
- (ReloadCitiesRequestProto_Builder*) clone;

- (ReloadCitiesRequestProto*) build;
- (ReloadCitiesRequestProto*) buildPartial;

- (ReloadCitiesRequestProto_Builder*) mergeFrom:(ReloadCitiesRequestProto*) other;
- (ReloadCitiesRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ReloadCitiesRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ReloadEquipmentRequestProto : PBGeneratedMessage {
@private
}

+ (ReloadEquipmentRequestProto*) defaultInstance;
- (ReloadEquipmentRequestProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ReloadEquipmentRequestProto_Builder*) builder;
+ (ReloadEquipmentRequestProto_Builder*) builder;
+ (ReloadEquipmentRequestProto_Builder*) builderWithPrototype:(ReloadEquipmentRequestProto*) prototype;

+ (ReloadEquipmentRequestProto*) parseFromData:(NSData*) data;
+ (ReloadEquipmentRequestProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReloadEquipmentRequestProto*) parseFromInputStream:(NSInputStream*) input;
+ (ReloadEquipmentRequestProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReloadEquipmentRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ReloadEquipmentRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ReloadEquipmentRequestProto_Builder : PBGeneratedMessage_Builder {
@private
  ReloadEquipmentRequestProto* result;
}

- (ReloadEquipmentRequestProto*) defaultInstance;

- (ReloadEquipmentRequestProto_Builder*) clear;
- (ReloadEquipmentRequestProto_Builder*) clone;

- (ReloadEquipmentRequestProto*) build;
- (ReloadEquipmentRequestProto*) buildPartial;

- (ReloadEquipmentRequestProto_Builder*) mergeFrom:(ReloadEquipmentRequestProto*) other;
- (ReloadEquipmentRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ReloadEquipmentRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ReloadTaskEquipmentRequirementsRequestProto : PBGeneratedMessage {
@private
}

+ (ReloadTaskEquipmentRequirementsRequestProto*) defaultInstance;
- (ReloadTaskEquipmentRequirementsRequestProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ReloadTaskEquipmentRequirementsRequestProto_Builder*) builder;
+ (ReloadTaskEquipmentRequirementsRequestProto_Builder*) builder;
+ (ReloadTaskEquipmentRequirementsRequestProto_Builder*) builderWithPrototype:(ReloadTaskEquipmentRequirementsRequestProto*) prototype;

+ (ReloadTaskEquipmentRequirementsRequestProto*) parseFromData:(NSData*) data;
+ (ReloadTaskEquipmentRequirementsRequestProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReloadTaskEquipmentRequirementsRequestProto*) parseFromInputStream:(NSInputStream*) input;
+ (ReloadTaskEquipmentRequirementsRequestProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReloadTaskEquipmentRequirementsRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ReloadTaskEquipmentRequirementsRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ReloadTaskEquipmentRequirementsRequestProto_Builder : PBGeneratedMessage_Builder {
@private
  ReloadTaskEquipmentRequirementsRequestProto* result;
}

- (ReloadTaskEquipmentRequirementsRequestProto*) defaultInstance;

- (ReloadTaskEquipmentRequirementsRequestProto_Builder*) clear;
- (ReloadTaskEquipmentRequirementsRequestProto_Builder*) clone;

- (ReloadTaskEquipmentRequirementsRequestProto*) build;
- (ReloadTaskEquipmentRequirementsRequestProto*) buildPartial;

- (ReloadTaskEquipmentRequirementsRequestProto_Builder*) mergeFrom:(ReloadTaskEquipmentRequirementsRequestProto*) other;
- (ReloadTaskEquipmentRequirementsRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ReloadTaskEquipmentRequirementsRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ReloadTaskRequestProto : PBGeneratedMessage {
@private
}

+ (ReloadTaskRequestProto*) defaultInstance;
- (ReloadTaskRequestProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ReloadTaskRequestProto_Builder*) builder;
+ (ReloadTaskRequestProto_Builder*) builder;
+ (ReloadTaskRequestProto_Builder*) builderWithPrototype:(ReloadTaskRequestProto*) prototype;

+ (ReloadTaskRequestProto*) parseFromData:(NSData*) data;
+ (ReloadTaskRequestProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReloadTaskRequestProto*) parseFromInputStream:(NSInputStream*) input;
+ (ReloadTaskRequestProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReloadTaskRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ReloadTaskRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ReloadTaskRequestProto_Builder : PBGeneratedMessage_Builder {
@private
  ReloadTaskRequestProto* result;
}

- (ReloadTaskRequestProto*) defaultInstance;

- (ReloadTaskRequestProto_Builder*) clear;
- (ReloadTaskRequestProto_Builder*) clone;

- (ReloadTaskRequestProto*) build;
- (ReloadTaskRequestProto*) buildPartial;

- (ReloadTaskRequestProto_Builder*) mergeFrom:(ReloadTaskRequestProto*) other;
- (ReloadTaskRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ReloadTaskRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

