// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Admin.pb.h"

@implementation AdminRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [AdminRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface ReloadCitiesRequestProto ()
@end

@implementation ReloadCitiesRequestProto

- (void) dealloc {
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
  }
  return self;
}
static ReloadCitiesRequestProto* defaultReloadCitiesRequestProtoInstance = nil;
+ (void) initialize {
  if (self == [ReloadCitiesRequestProto class]) {
    defaultReloadCitiesRequestProtoInstance = [[ReloadCitiesRequestProto alloc] init];
  }
}
+ (ReloadCitiesRequestProto*) defaultInstance {
  return defaultReloadCitiesRequestProtoInstance;
}
- (ReloadCitiesRequestProto*) defaultInstance {
  return defaultReloadCitiesRequestProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (ReloadCitiesRequestProto*) parseFromData:(NSData*) data {
  return (ReloadCitiesRequestProto*)[[[ReloadCitiesRequestProto builder] mergeFromData:data] build];
}
+ (ReloadCitiesRequestProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ReloadCitiesRequestProto*)[[[ReloadCitiesRequestProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (ReloadCitiesRequestProto*) parseFromInputStream:(NSInputStream*) input {
  return (ReloadCitiesRequestProto*)[[[ReloadCitiesRequestProto builder] mergeFromInputStream:input] build];
}
+ (ReloadCitiesRequestProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ReloadCitiesRequestProto*)[[[ReloadCitiesRequestProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ReloadCitiesRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (ReloadCitiesRequestProto*)[[[ReloadCitiesRequestProto builder] mergeFromCodedInputStream:input] build];
}
+ (ReloadCitiesRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ReloadCitiesRequestProto*)[[[ReloadCitiesRequestProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ReloadCitiesRequestProto_Builder*) builder {
  return [[[ReloadCitiesRequestProto_Builder alloc] init] autorelease];
}
+ (ReloadCitiesRequestProto_Builder*) builderWithPrototype:(ReloadCitiesRequestProto*) prototype {
  return [[ReloadCitiesRequestProto builder] mergeFrom:prototype];
}
- (ReloadCitiesRequestProto_Builder*) builder {
  return [ReloadCitiesRequestProto builder];
}
@end

@interface ReloadCitiesRequestProto_Builder()
@property (retain) ReloadCitiesRequestProto* result;
@end

@implementation ReloadCitiesRequestProto_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[ReloadCitiesRequestProto alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (ReloadCitiesRequestProto_Builder*) clear {
  self.result = [[[ReloadCitiesRequestProto alloc] init] autorelease];
  return self;
}
- (ReloadCitiesRequestProto_Builder*) clone {
  return [ReloadCitiesRequestProto builderWithPrototype:result];
}
- (ReloadCitiesRequestProto*) defaultInstance {
  return [ReloadCitiesRequestProto defaultInstance];
}
- (ReloadCitiesRequestProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (ReloadCitiesRequestProto*) buildPartial {
  ReloadCitiesRequestProto* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (ReloadCitiesRequestProto_Builder*) mergeFrom:(ReloadCitiesRequestProto*) other {
  if (other == [ReloadCitiesRequestProto defaultInstance]) {
    return self;
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (ReloadCitiesRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (ReloadCitiesRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
    }
  }
}
@end

@interface ReloadEquipmentRequestProto ()
@end

@implementation ReloadEquipmentRequestProto

- (void) dealloc {
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
  }
  return self;
}
static ReloadEquipmentRequestProto* defaultReloadEquipmentRequestProtoInstance = nil;
+ (void) initialize {
  if (self == [ReloadEquipmentRequestProto class]) {
    defaultReloadEquipmentRequestProtoInstance = [[ReloadEquipmentRequestProto alloc] init];
  }
}
+ (ReloadEquipmentRequestProto*) defaultInstance {
  return defaultReloadEquipmentRequestProtoInstance;
}
- (ReloadEquipmentRequestProto*) defaultInstance {
  return defaultReloadEquipmentRequestProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (ReloadEquipmentRequestProto*) parseFromData:(NSData*) data {
  return (ReloadEquipmentRequestProto*)[[[ReloadEquipmentRequestProto builder] mergeFromData:data] build];
}
+ (ReloadEquipmentRequestProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ReloadEquipmentRequestProto*)[[[ReloadEquipmentRequestProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (ReloadEquipmentRequestProto*) parseFromInputStream:(NSInputStream*) input {
  return (ReloadEquipmentRequestProto*)[[[ReloadEquipmentRequestProto builder] mergeFromInputStream:input] build];
}
+ (ReloadEquipmentRequestProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ReloadEquipmentRequestProto*)[[[ReloadEquipmentRequestProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ReloadEquipmentRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (ReloadEquipmentRequestProto*)[[[ReloadEquipmentRequestProto builder] mergeFromCodedInputStream:input] build];
}
+ (ReloadEquipmentRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ReloadEquipmentRequestProto*)[[[ReloadEquipmentRequestProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ReloadEquipmentRequestProto_Builder*) builder {
  return [[[ReloadEquipmentRequestProto_Builder alloc] init] autorelease];
}
+ (ReloadEquipmentRequestProto_Builder*) builderWithPrototype:(ReloadEquipmentRequestProto*) prototype {
  return [[ReloadEquipmentRequestProto builder] mergeFrom:prototype];
}
- (ReloadEquipmentRequestProto_Builder*) builder {
  return [ReloadEquipmentRequestProto builder];
}
@end

@interface ReloadEquipmentRequestProto_Builder()
@property (retain) ReloadEquipmentRequestProto* result;
@end

@implementation ReloadEquipmentRequestProto_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[ReloadEquipmentRequestProto alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (ReloadEquipmentRequestProto_Builder*) clear {
  self.result = [[[ReloadEquipmentRequestProto alloc] init] autorelease];
  return self;
}
- (ReloadEquipmentRequestProto_Builder*) clone {
  return [ReloadEquipmentRequestProto builderWithPrototype:result];
}
- (ReloadEquipmentRequestProto*) defaultInstance {
  return [ReloadEquipmentRequestProto defaultInstance];
}
- (ReloadEquipmentRequestProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (ReloadEquipmentRequestProto*) buildPartial {
  ReloadEquipmentRequestProto* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (ReloadEquipmentRequestProto_Builder*) mergeFrom:(ReloadEquipmentRequestProto*) other {
  if (other == [ReloadEquipmentRequestProto defaultInstance]) {
    return self;
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (ReloadEquipmentRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (ReloadEquipmentRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
    }
  }
}
@end

@interface ReloadTaskEquipmentRequirementsRequestProto ()
@end

@implementation ReloadTaskEquipmentRequirementsRequestProto

- (void) dealloc {
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
  }
  return self;
}
static ReloadTaskEquipmentRequirementsRequestProto* defaultReloadTaskEquipmentRequirementsRequestProtoInstance = nil;
+ (void) initialize {
  if (self == [ReloadTaskEquipmentRequirementsRequestProto class]) {
    defaultReloadTaskEquipmentRequirementsRequestProtoInstance = [[ReloadTaskEquipmentRequirementsRequestProto alloc] init];
  }
}
+ (ReloadTaskEquipmentRequirementsRequestProto*) defaultInstance {
  return defaultReloadTaskEquipmentRequirementsRequestProtoInstance;
}
- (ReloadTaskEquipmentRequirementsRequestProto*) defaultInstance {
  return defaultReloadTaskEquipmentRequirementsRequestProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (ReloadTaskEquipmentRequirementsRequestProto*) parseFromData:(NSData*) data {
  return (ReloadTaskEquipmentRequirementsRequestProto*)[[[ReloadTaskEquipmentRequirementsRequestProto builder] mergeFromData:data] build];
}
+ (ReloadTaskEquipmentRequirementsRequestProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ReloadTaskEquipmentRequirementsRequestProto*)[[[ReloadTaskEquipmentRequirementsRequestProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (ReloadTaskEquipmentRequirementsRequestProto*) parseFromInputStream:(NSInputStream*) input {
  return (ReloadTaskEquipmentRequirementsRequestProto*)[[[ReloadTaskEquipmentRequirementsRequestProto builder] mergeFromInputStream:input] build];
}
+ (ReloadTaskEquipmentRequirementsRequestProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ReloadTaskEquipmentRequirementsRequestProto*)[[[ReloadTaskEquipmentRequirementsRequestProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ReloadTaskEquipmentRequirementsRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (ReloadTaskEquipmentRequirementsRequestProto*)[[[ReloadTaskEquipmentRequirementsRequestProto builder] mergeFromCodedInputStream:input] build];
}
+ (ReloadTaskEquipmentRequirementsRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ReloadTaskEquipmentRequirementsRequestProto*)[[[ReloadTaskEquipmentRequirementsRequestProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ReloadTaskEquipmentRequirementsRequestProto_Builder*) builder {
  return [[[ReloadTaskEquipmentRequirementsRequestProto_Builder alloc] init] autorelease];
}
+ (ReloadTaskEquipmentRequirementsRequestProto_Builder*) builderWithPrototype:(ReloadTaskEquipmentRequirementsRequestProto*) prototype {
  return [[ReloadTaskEquipmentRequirementsRequestProto builder] mergeFrom:prototype];
}
- (ReloadTaskEquipmentRequirementsRequestProto_Builder*) builder {
  return [ReloadTaskEquipmentRequirementsRequestProto builder];
}
@end

@interface ReloadTaskEquipmentRequirementsRequestProto_Builder()
@property (retain) ReloadTaskEquipmentRequirementsRequestProto* result;
@end

@implementation ReloadTaskEquipmentRequirementsRequestProto_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[ReloadTaskEquipmentRequirementsRequestProto alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (ReloadTaskEquipmentRequirementsRequestProto_Builder*) clear {
  self.result = [[[ReloadTaskEquipmentRequirementsRequestProto alloc] init] autorelease];
  return self;
}
- (ReloadTaskEquipmentRequirementsRequestProto_Builder*) clone {
  return [ReloadTaskEquipmentRequirementsRequestProto builderWithPrototype:result];
}
- (ReloadTaskEquipmentRequirementsRequestProto*) defaultInstance {
  return [ReloadTaskEquipmentRequirementsRequestProto defaultInstance];
}
- (ReloadTaskEquipmentRequirementsRequestProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (ReloadTaskEquipmentRequirementsRequestProto*) buildPartial {
  ReloadTaskEquipmentRequirementsRequestProto* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (ReloadTaskEquipmentRequirementsRequestProto_Builder*) mergeFrom:(ReloadTaskEquipmentRequirementsRequestProto*) other {
  if (other == [ReloadTaskEquipmentRequirementsRequestProto defaultInstance]) {
    return self;
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (ReloadTaskEquipmentRequirementsRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (ReloadTaskEquipmentRequirementsRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
    }
  }
}
@end

@interface ReloadTaskRequestProto ()
@end

@implementation ReloadTaskRequestProto

- (void) dealloc {
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
  }
  return self;
}
static ReloadTaskRequestProto* defaultReloadTaskRequestProtoInstance = nil;
+ (void) initialize {
  if (self == [ReloadTaskRequestProto class]) {
    defaultReloadTaskRequestProtoInstance = [[ReloadTaskRequestProto alloc] init];
  }
}
+ (ReloadTaskRequestProto*) defaultInstance {
  return defaultReloadTaskRequestProtoInstance;
}
- (ReloadTaskRequestProto*) defaultInstance {
  return defaultReloadTaskRequestProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (ReloadTaskRequestProto*) parseFromData:(NSData*) data {
  return (ReloadTaskRequestProto*)[[[ReloadTaskRequestProto builder] mergeFromData:data] build];
}
+ (ReloadTaskRequestProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ReloadTaskRequestProto*)[[[ReloadTaskRequestProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (ReloadTaskRequestProto*) parseFromInputStream:(NSInputStream*) input {
  return (ReloadTaskRequestProto*)[[[ReloadTaskRequestProto builder] mergeFromInputStream:input] build];
}
+ (ReloadTaskRequestProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ReloadTaskRequestProto*)[[[ReloadTaskRequestProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ReloadTaskRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (ReloadTaskRequestProto*)[[[ReloadTaskRequestProto builder] mergeFromCodedInputStream:input] build];
}
+ (ReloadTaskRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ReloadTaskRequestProto*)[[[ReloadTaskRequestProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ReloadTaskRequestProto_Builder*) builder {
  return [[[ReloadTaskRequestProto_Builder alloc] init] autorelease];
}
+ (ReloadTaskRequestProto_Builder*) builderWithPrototype:(ReloadTaskRequestProto*) prototype {
  return [[ReloadTaskRequestProto builder] mergeFrom:prototype];
}
- (ReloadTaskRequestProto_Builder*) builder {
  return [ReloadTaskRequestProto builder];
}
@end

@interface ReloadTaskRequestProto_Builder()
@property (retain) ReloadTaskRequestProto* result;
@end

@implementation ReloadTaskRequestProto_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[ReloadTaskRequestProto alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (ReloadTaskRequestProto_Builder*) clear {
  self.result = [[[ReloadTaskRequestProto alloc] init] autorelease];
  return self;
}
- (ReloadTaskRequestProto_Builder*) clone {
  return [ReloadTaskRequestProto builderWithPrototype:result];
}
- (ReloadTaskRequestProto*) defaultInstance {
  return [ReloadTaskRequestProto defaultInstance];
}
- (ReloadTaskRequestProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (ReloadTaskRequestProto*) buildPartial {
  ReloadTaskRequestProto* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (ReloadTaskRequestProto_Builder*) mergeFrom:(ReloadTaskRequestProto*) other {
  if (other == [ReloadTaskRequestProto defaultInstance]) {
    return self;
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (ReloadTaskRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (ReloadTaskRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
    }
  }
}
@end

