// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Admin.pb.h"

@implementation AdminRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [AdminRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface AdminChangeRequestProto ()
@property AdminChangeRequestProto_StaticDataReloadType staticDataReloadType;
@property BOOL purgeStaticDataForConnectedClients;
@end

@implementation AdminChangeRequestProto

- (BOOL) hasStaticDataReloadType {
  return !!hasStaticDataReloadType_;
}
- (void) setHasStaticDataReloadType:(BOOL) value {
  hasStaticDataReloadType_ = !!value;
}
@synthesize staticDataReloadType;
- (BOOL) hasPurgeStaticDataForConnectedClients {
  return !!hasPurgeStaticDataForConnectedClients_;
}
- (void) setHasPurgeStaticDataForConnectedClients:(BOOL) value {
  hasPurgeStaticDataForConnectedClients_ = !!value;
}
- (BOOL) purgeStaticDataForConnectedClients {
  return !!purgeStaticDataForConnectedClients_;
}
- (void) setPurgeStaticDataForConnectedClients:(BOOL) value {
  purgeStaticDataForConnectedClients_ = !!value;
}
- (void) dealloc {
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.staticDataReloadType = AdminChangeRequestProto_StaticDataReloadTypeAll;
    self.purgeStaticDataForConnectedClients = NO;
  }
  return self;
}
static AdminChangeRequestProto* defaultAdminChangeRequestProtoInstance = nil;
+ (void) initialize {
  if (self == [AdminChangeRequestProto class]) {
    defaultAdminChangeRequestProtoInstance = [[AdminChangeRequestProto alloc] init];
  }
}
+ (AdminChangeRequestProto*) defaultInstance {
  return defaultAdminChangeRequestProtoInstance;
}
- (AdminChangeRequestProto*) defaultInstance {
  return defaultAdminChangeRequestProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasStaticDataReloadType) {
    [output writeEnum:1 value:self.staticDataReloadType];
  }
  if (self.hasPurgeStaticDataForConnectedClients) {
    [output writeBool:2 value:self.purgeStaticDataForConnectedClients];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasStaticDataReloadType) {
    size += computeEnumSize(1, self.staticDataReloadType);
  }
  if (self.hasPurgeStaticDataForConnectedClients) {
    size += computeBoolSize(2, self.purgeStaticDataForConnectedClients);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (AdminChangeRequestProto*) parseFromData:(NSData*) data {
  return (AdminChangeRequestProto*)[[[AdminChangeRequestProto builder] mergeFromData:data] build];
}
+ (AdminChangeRequestProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (AdminChangeRequestProto*)[[[AdminChangeRequestProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (AdminChangeRequestProto*) parseFromInputStream:(NSInputStream*) input {
  return (AdminChangeRequestProto*)[[[AdminChangeRequestProto builder] mergeFromInputStream:input] build];
}
+ (AdminChangeRequestProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (AdminChangeRequestProto*)[[[AdminChangeRequestProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (AdminChangeRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (AdminChangeRequestProto*)[[[AdminChangeRequestProto builder] mergeFromCodedInputStream:input] build];
}
+ (AdminChangeRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (AdminChangeRequestProto*)[[[AdminChangeRequestProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (AdminChangeRequestProto_Builder*) builder {
  return [[[AdminChangeRequestProto_Builder alloc] init] autorelease];
}
+ (AdminChangeRequestProto_Builder*) builderWithPrototype:(AdminChangeRequestProto*) prototype {
  return [[AdminChangeRequestProto builder] mergeFrom:prototype];
}
- (AdminChangeRequestProto_Builder*) builder {
  return [AdminChangeRequestProto builder];
}
@end

BOOL AdminChangeRequestProto_StaticDataReloadTypeIsValidValue(AdminChangeRequestProto_StaticDataReloadType value) {
  switch (value) {
    case AdminChangeRequestProto_StaticDataReloadTypeAll:
    case AdminChangeRequestProto_StaticDataReloadTypeBuildStructJobs:
    case AdminChangeRequestProto_StaticDataReloadTypeCities:
    case AdminChangeRequestProto_StaticDataReloadTypeDefeatTypeJobs:
    case AdminChangeRequestProto_StaticDataReloadTypeEquipment:
    case AdminChangeRequestProto_StaticDataReloadTypeQuests:
    case AdminChangeRequestProto_StaticDataReloadTypeTaskEquipRequirements:
    case AdminChangeRequestProto_StaticDataReloadTypeTasks:
    case AdminChangeRequestProto_StaticDataReloadTypeUpgradeStructJobs:
    case AdminChangeRequestProto_StaticDataReloadTypeStructures:
    case AdminChangeRequestProto_StaticDataReloadTypePossessEquipJobs:
    case AdminChangeRequestProto_StaticDataReloadTypeLevelsRequiredExperience:
    case AdminChangeRequestProto_StaticDataReloadTypeNeutralCityElems:
      return YES;
    default:
      return NO;
  }
}
@interface AdminChangeRequestProto_Builder()
@property (retain) AdminChangeRequestProto* result;
@end

@implementation AdminChangeRequestProto_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[AdminChangeRequestProto alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (AdminChangeRequestProto_Builder*) clear {
  self.result = [[[AdminChangeRequestProto alloc] init] autorelease];
  return self;
}
- (AdminChangeRequestProto_Builder*) clone {
  return [AdminChangeRequestProto builderWithPrototype:result];
}
- (AdminChangeRequestProto*) defaultInstance {
  return [AdminChangeRequestProto defaultInstance];
}
- (AdminChangeRequestProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (AdminChangeRequestProto*) buildPartial {
  AdminChangeRequestProto* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (AdminChangeRequestProto_Builder*) mergeFrom:(AdminChangeRequestProto*) other {
  if (other == [AdminChangeRequestProto defaultInstance]) {
    return self;
  }
  if (other.hasStaticDataReloadType) {
    [self setStaticDataReloadType:other.staticDataReloadType];
  }
  if (other.hasPurgeStaticDataForConnectedClients) {
    [self setPurgeStaticDataForConnectedClients:other.purgeStaticDataForConnectedClients];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (AdminChangeRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (AdminChangeRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        int32_t value = [input readEnum];
        if (AdminChangeRequestProto_StaticDataReloadTypeIsValidValue(value)) {
          [self setStaticDataReloadType:value];
        } else {
          [unknownFields mergeVarintField:1 value:value];
        }
        break;
      }
      case 16: {
        [self setPurgeStaticDataForConnectedClients:[input readBool]];
        break;
      }
    }
  }
}
- (BOOL) hasStaticDataReloadType {
  return result.hasStaticDataReloadType;
}
- (AdminChangeRequestProto_StaticDataReloadType) staticDataReloadType {
  return result.staticDataReloadType;
}
- (AdminChangeRequestProto_Builder*) setStaticDataReloadType:(AdminChangeRequestProto_StaticDataReloadType) value {
  result.hasStaticDataReloadType = YES;
  result.staticDataReloadType = value;
  return self;
}
- (AdminChangeRequestProto_Builder*) clearStaticDataReloadType {
  result.hasStaticDataReloadType = NO;
  result.staticDataReloadType = AdminChangeRequestProto_StaticDataReloadTypeAll;
  return self;
}
- (BOOL) hasPurgeStaticDataForConnectedClients {
  return result.hasPurgeStaticDataForConnectedClients;
}
- (BOOL) purgeStaticDataForConnectedClients {
  return result.purgeStaticDataForConnectedClients;
}
- (AdminChangeRequestProto_Builder*) setPurgeStaticDataForConnectedClients:(BOOL) value {
  result.hasPurgeStaticDataForConnectedClients = YES;
  result.purgeStaticDataForConnectedClients = value;
  return self;
}
- (AdminChangeRequestProto_Builder*) clearPurgeStaticDataForConnectedClients {
  result.hasPurgeStaticDataForConnectedClients = NO;
  result.purgeStaticDataForConnectedClients = NO;
  return self;
}
@end

