// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class CoordinateProto;
@class CoordinateProto_Builder;
@class FullEquipProto;
@class FullEquipProto_Builder;
@class FullMarketplacePostProto;
@class FullMarketplacePostProto_Builder;
@class FullTaskProto;
@class FullTaskProto_Builder;
@class FullUserProto;
@class FullUserProto_Builder;
@class FullUserStructureProto;
@class FullUserStructureProto_Builder;
@class LocationProto;
@class LocationProto_Builder;
@class MinimumUserProto;
@class MinimumUserProto_Builder;
typedef enum {
  UserTypeGoodWarrior = 0,
  UserTypeGoodArcher = 1,
  UserTypeGoodMage = 2,
  UserTypeBadWarrior = 3,
  UserTypeBadArcher = 4,
  UserTypeBadMage = 5,
} UserType;

BOOL UserTypeIsValidValue(UserType value);

typedef enum {
  MarketplacePostTypeEquipPost = 0,
  MarketplacePostTypeWoodPost = 1,
  MarketplacePostTypeDiamondPost = 2,
  MarketplacePostTypeCoinPost = 3,
} MarketplacePostType;

BOOL MarketplacePostTypeIsValidValue(MarketplacePostType value);

typedef enum {
  FullEquipProto_RarityCommon = 0,
  FullEquipProto_RarityUncommon = 1,
  FullEquipProto_RarityRare = 2,
  FullEquipProto_RarityEpic = 3,
  FullEquipProto_RarityLegendary = 4,
} FullEquipProto_Rarity;

BOOL FullEquipProto_RarityIsValidValue(FullEquipProto_Rarity value);

typedef enum {
  FullEquipProto_EquipTypeWeapon = 0,
  FullEquipProto_EquipTypeArmor = 1,
  FullEquipProto_EquipTypeAccessory = 2,
} FullEquipProto_EquipType;

BOOL FullEquipProto_EquipTypeIsValidValue(FullEquipProto_EquipType value);

typedef enum {
  FullEquipProto_ClassTypeWarrior = 0,
  FullEquipProto_ClassTypeArcher = 1,
  FullEquipProto_ClassTypeMage = 2,
} FullEquipProto_ClassType;

BOOL FullEquipProto_ClassTypeIsValidValue(FullEquipProto_ClassType value);


@interface InfoRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface MinimumUserProto : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasName_:1;
  BOOL hasUserType_:1;
  int32_t userId;
  NSString* name;
  UserType userType;
}
- (BOOL) hasUserId;
- (BOOL) hasName;
- (BOOL) hasUserType;
@property (readonly) int32_t userId;
@property (readonly, retain) NSString* name;
@property (readonly) UserType userType;

+ (MinimumUserProto*) defaultInstance;
- (MinimumUserProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MinimumUserProto_Builder*) builder;
+ (MinimumUserProto_Builder*) builder;
+ (MinimumUserProto_Builder*) builderWithPrototype:(MinimumUserProto*) prototype;

+ (MinimumUserProto*) parseFromData:(NSData*) data;
+ (MinimumUserProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MinimumUserProto*) parseFromInputStream:(NSInputStream*) input;
+ (MinimumUserProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MinimumUserProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MinimumUserProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MinimumUserProto_Builder : PBGeneratedMessage_Builder {
@private
  MinimumUserProto* result;
}

- (MinimumUserProto*) defaultInstance;

- (MinimumUserProto_Builder*) clear;
- (MinimumUserProto_Builder*) clone;

- (MinimumUserProto*) build;
- (MinimumUserProto*) buildPartial;

- (MinimumUserProto_Builder*) mergeFrom:(MinimumUserProto*) other;
- (MinimumUserProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MinimumUserProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (MinimumUserProto_Builder*) setUserId:(int32_t) value;
- (MinimumUserProto_Builder*) clearUserId;

- (BOOL) hasName;
- (NSString*) name;
- (MinimumUserProto_Builder*) setName:(NSString*) value;
- (MinimumUserProto_Builder*) clearName;

- (BOOL) hasUserType;
- (UserType) userType;
- (MinimumUserProto_Builder*) setUserType:(UserType) value;
- (MinimumUserProto_Builder*) clearUserType;
@end

@interface FullUserProto : PBGeneratedMessage {
@private
  BOOL hasNumReferrals_:1;
  BOOL hasHourlyCoins_:1;
  BOOL hasBattlesLost_:1;
  BOOL hasBattlesWon_:1;
  BOOL hasTasksCompleted_:1;
  BOOL hasExperience_:1;
  BOOL hasVaultBalance_:1;
  BOOL hasWood_:1;
  BOOL hasCoins_:1;
  BOOL hasDiamonds_:1;
  BOOL hasStaminaMax_:1;
  BOOL hasEnergyMax_:1;
  BOOL hasHealthMax_:1;
  BOOL hasSkillPoints_:1;
  BOOL hasHealth_:1;
  BOOL hasEnergy_:1;
  BOOL hasStamina_:1;
  BOOL hasDefense_:1;
  BOOL hasAttack_:1;
  BOOL hasLevel_:1;
  BOOL hasUserId_:1;
  BOOL hasName_:1;
  BOOL hasArmyCode_:1;
  BOOL hasUdid_:1;
  BOOL hasUserLocation_:1;
  BOOL hasUserType_:1;
  int32_t numReferrals;
  int32_t hourlyCoins;
  int32_t battlesLost;
  int32_t battlesWon;
  int32_t tasksCompleted;
  int32_t experience;
  int32_t vaultBalance;
  int32_t wood;
  int32_t coins;
  int32_t diamonds;
  int32_t staminaMax;
  int32_t energyMax;
  int32_t healthMax;
  int32_t skillPoints;
  int32_t health;
  int32_t energy;
  int32_t stamina;
  int32_t defense;
  int32_t attack;
  int32_t level;
  int32_t userId;
  NSString* name;
  NSString* armyCode;
  NSString* udid;
  LocationProto* userLocation;
  UserType userType;
}
- (BOOL) hasUserId;
- (BOOL) hasName;
- (BOOL) hasLevel;
- (BOOL) hasUserType;
- (BOOL) hasAttack;
- (BOOL) hasDefense;
- (BOOL) hasStamina;
- (BOOL) hasEnergy;
- (BOOL) hasHealth;
- (BOOL) hasSkillPoints;
- (BOOL) hasHealthMax;
- (BOOL) hasEnergyMax;
- (BOOL) hasStaminaMax;
- (BOOL) hasDiamonds;
- (BOOL) hasCoins;
- (BOOL) hasWood;
- (BOOL) hasVaultBalance;
- (BOOL) hasExperience;
- (BOOL) hasTasksCompleted;
- (BOOL) hasBattlesWon;
- (BOOL) hasBattlesLost;
- (BOOL) hasHourlyCoins;
- (BOOL) hasArmyCode;
- (BOOL) hasNumReferrals;
- (BOOL) hasUdid;
- (BOOL) hasUserLocation;
@property (readonly) int32_t userId;
@property (readonly, retain) NSString* name;
@property (readonly) int32_t level;
@property (readonly) UserType userType;
@property (readonly) int32_t attack;
@property (readonly) int32_t defense;
@property (readonly) int32_t stamina;
@property (readonly) int32_t energy;
@property (readonly) int32_t health;
@property (readonly) int32_t skillPoints;
@property (readonly) int32_t healthMax;
@property (readonly) int32_t energyMax;
@property (readonly) int32_t staminaMax;
@property (readonly) int32_t diamonds;
@property (readonly) int32_t coins;
@property (readonly) int32_t wood;
@property (readonly) int32_t vaultBalance;
@property (readonly) int32_t experience;
@property (readonly) int32_t tasksCompleted;
@property (readonly) int32_t battlesWon;
@property (readonly) int32_t battlesLost;
@property (readonly) int32_t hourlyCoins;
@property (readonly, retain) NSString* armyCode;
@property (readonly) int32_t numReferrals;
@property (readonly, retain) NSString* udid;
@property (readonly, retain) LocationProto* userLocation;

+ (FullUserProto*) defaultInstance;
- (FullUserProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FullUserProto_Builder*) builder;
+ (FullUserProto_Builder*) builder;
+ (FullUserProto_Builder*) builderWithPrototype:(FullUserProto*) prototype;

+ (FullUserProto*) parseFromData:(NSData*) data;
+ (FullUserProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullUserProto*) parseFromInputStream:(NSInputStream*) input;
+ (FullUserProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullUserProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FullUserProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FullUserProto_Builder : PBGeneratedMessage_Builder {
@private
  FullUserProto* result;
}

- (FullUserProto*) defaultInstance;

- (FullUserProto_Builder*) clear;
- (FullUserProto_Builder*) clone;

- (FullUserProto*) build;
- (FullUserProto*) buildPartial;

- (FullUserProto_Builder*) mergeFrom:(FullUserProto*) other;
- (FullUserProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FullUserProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (FullUserProto_Builder*) setUserId:(int32_t) value;
- (FullUserProto_Builder*) clearUserId;

- (BOOL) hasName;
- (NSString*) name;
- (FullUserProto_Builder*) setName:(NSString*) value;
- (FullUserProto_Builder*) clearName;

- (BOOL) hasLevel;
- (int32_t) level;
- (FullUserProto_Builder*) setLevel:(int32_t) value;
- (FullUserProto_Builder*) clearLevel;

- (BOOL) hasUserType;
- (UserType) userType;
- (FullUserProto_Builder*) setUserType:(UserType) value;
- (FullUserProto_Builder*) clearUserType;

- (BOOL) hasAttack;
- (int32_t) attack;
- (FullUserProto_Builder*) setAttack:(int32_t) value;
- (FullUserProto_Builder*) clearAttack;

- (BOOL) hasDefense;
- (int32_t) defense;
- (FullUserProto_Builder*) setDefense:(int32_t) value;
- (FullUserProto_Builder*) clearDefense;

- (BOOL) hasStamina;
- (int32_t) stamina;
- (FullUserProto_Builder*) setStamina:(int32_t) value;
- (FullUserProto_Builder*) clearStamina;

- (BOOL) hasEnergy;
- (int32_t) energy;
- (FullUserProto_Builder*) setEnergy:(int32_t) value;
- (FullUserProto_Builder*) clearEnergy;

- (BOOL) hasHealth;
- (int32_t) health;
- (FullUserProto_Builder*) setHealth:(int32_t) value;
- (FullUserProto_Builder*) clearHealth;

- (BOOL) hasSkillPoints;
- (int32_t) skillPoints;
- (FullUserProto_Builder*) setSkillPoints:(int32_t) value;
- (FullUserProto_Builder*) clearSkillPoints;

- (BOOL) hasHealthMax;
- (int32_t) healthMax;
- (FullUserProto_Builder*) setHealthMax:(int32_t) value;
- (FullUserProto_Builder*) clearHealthMax;

- (BOOL) hasEnergyMax;
- (int32_t) energyMax;
- (FullUserProto_Builder*) setEnergyMax:(int32_t) value;
- (FullUserProto_Builder*) clearEnergyMax;

- (BOOL) hasStaminaMax;
- (int32_t) staminaMax;
- (FullUserProto_Builder*) setStaminaMax:(int32_t) value;
- (FullUserProto_Builder*) clearStaminaMax;

- (BOOL) hasDiamonds;
- (int32_t) diamonds;
- (FullUserProto_Builder*) setDiamonds:(int32_t) value;
- (FullUserProto_Builder*) clearDiamonds;

- (BOOL) hasCoins;
- (int32_t) coins;
- (FullUserProto_Builder*) setCoins:(int32_t) value;
- (FullUserProto_Builder*) clearCoins;

- (BOOL) hasWood;
- (int32_t) wood;
- (FullUserProto_Builder*) setWood:(int32_t) value;
- (FullUserProto_Builder*) clearWood;

- (BOOL) hasVaultBalance;
- (int32_t) vaultBalance;
- (FullUserProto_Builder*) setVaultBalance:(int32_t) value;
- (FullUserProto_Builder*) clearVaultBalance;

- (BOOL) hasExperience;
- (int32_t) experience;
- (FullUserProto_Builder*) setExperience:(int32_t) value;
- (FullUserProto_Builder*) clearExperience;

- (BOOL) hasTasksCompleted;
- (int32_t) tasksCompleted;
- (FullUserProto_Builder*) setTasksCompleted:(int32_t) value;
- (FullUserProto_Builder*) clearTasksCompleted;

- (BOOL) hasBattlesWon;
- (int32_t) battlesWon;
- (FullUserProto_Builder*) setBattlesWon:(int32_t) value;
- (FullUserProto_Builder*) clearBattlesWon;

- (BOOL) hasBattlesLost;
- (int32_t) battlesLost;
- (FullUserProto_Builder*) setBattlesLost:(int32_t) value;
- (FullUserProto_Builder*) clearBattlesLost;

- (BOOL) hasHourlyCoins;
- (int32_t) hourlyCoins;
- (FullUserProto_Builder*) setHourlyCoins:(int32_t) value;
- (FullUserProto_Builder*) clearHourlyCoins;

- (BOOL) hasArmyCode;
- (NSString*) armyCode;
- (FullUserProto_Builder*) setArmyCode:(NSString*) value;
- (FullUserProto_Builder*) clearArmyCode;

- (BOOL) hasNumReferrals;
- (int32_t) numReferrals;
- (FullUserProto_Builder*) setNumReferrals:(int32_t) value;
- (FullUserProto_Builder*) clearNumReferrals;

- (BOOL) hasUdid;
- (NSString*) udid;
- (FullUserProto_Builder*) setUdid:(NSString*) value;
- (FullUserProto_Builder*) clearUdid;

- (BOOL) hasUserLocation;
- (LocationProto*) userLocation;
- (FullUserProto_Builder*) setUserLocation:(LocationProto*) value;
- (FullUserProto_Builder*) setUserLocationBuilder:(LocationProto_Builder*) builderForValue;
- (FullUserProto_Builder*) mergeUserLocation:(LocationProto*) value;
- (FullUserProto_Builder*) clearUserLocation;
@end

@interface FullEquipProto : PBGeneratedMessage {
@private
  BOOL hasChanceOfLoss_:1;
  BOOL hasEquipId_:1;
  BOOL hasAttackBoost_:1;
  BOOL hasDefenseBoost_:1;
  BOOL hasMinLevel_:1;
  BOOL hasCoinPrice_:1;
  BOOL hasDiamondPrice_:1;
  BOOL hasName_:1;
  BOOL hasEquipType_:1;
  BOOL hasClassType_:1;
  BOOL hasRarity_:1;
  Float32 chanceOfLoss;
  int32_t equipId;
  int32_t attackBoost;
  int32_t defenseBoost;
  int32_t minLevel;
  int32_t coinPrice;
  int32_t diamondPrice;
  NSString* name;
  FullEquipProto_EquipType equipType;
  FullEquipProto_ClassType classType;
  FullEquipProto_Rarity rarity;
}
- (BOOL) hasEquipId;
- (BOOL) hasName;
- (BOOL) hasEquipType;
- (BOOL) hasClassType;
- (BOOL) hasAttackBoost;
- (BOOL) hasDefenseBoost;
- (BOOL) hasMinLevel;
- (BOOL) hasCoinPrice;
- (BOOL) hasDiamondPrice;
- (BOOL) hasChanceOfLoss;
- (BOOL) hasRarity;
@property (readonly) int32_t equipId;
@property (readonly, retain) NSString* name;
@property (readonly) FullEquipProto_EquipType equipType;
@property (readonly) FullEquipProto_ClassType classType;
@property (readonly) int32_t attackBoost;
@property (readonly) int32_t defenseBoost;
@property (readonly) int32_t minLevel;
@property (readonly) int32_t coinPrice;
@property (readonly) int32_t diamondPrice;
@property (readonly) Float32 chanceOfLoss;
@property (readonly) FullEquipProto_Rarity rarity;

+ (FullEquipProto*) defaultInstance;
- (FullEquipProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FullEquipProto_Builder*) builder;
+ (FullEquipProto_Builder*) builder;
+ (FullEquipProto_Builder*) builderWithPrototype:(FullEquipProto*) prototype;

+ (FullEquipProto*) parseFromData:(NSData*) data;
+ (FullEquipProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullEquipProto*) parseFromInputStream:(NSInputStream*) input;
+ (FullEquipProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullEquipProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FullEquipProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FullEquipProto_Builder : PBGeneratedMessage_Builder {
@private
  FullEquipProto* result;
}

- (FullEquipProto*) defaultInstance;

- (FullEquipProto_Builder*) clear;
- (FullEquipProto_Builder*) clone;

- (FullEquipProto*) build;
- (FullEquipProto*) buildPartial;

- (FullEquipProto_Builder*) mergeFrom:(FullEquipProto*) other;
- (FullEquipProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FullEquipProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasEquipId;
- (int32_t) equipId;
- (FullEquipProto_Builder*) setEquipId:(int32_t) value;
- (FullEquipProto_Builder*) clearEquipId;

- (BOOL) hasName;
- (NSString*) name;
- (FullEquipProto_Builder*) setName:(NSString*) value;
- (FullEquipProto_Builder*) clearName;

- (BOOL) hasEquipType;
- (FullEquipProto_EquipType) equipType;
- (FullEquipProto_Builder*) setEquipType:(FullEquipProto_EquipType) value;
- (FullEquipProto_Builder*) clearEquipType;

- (BOOL) hasClassType;
- (FullEquipProto_ClassType) classType;
- (FullEquipProto_Builder*) setClassType:(FullEquipProto_ClassType) value;
- (FullEquipProto_Builder*) clearClassType;

- (BOOL) hasAttackBoost;
- (int32_t) attackBoost;
- (FullEquipProto_Builder*) setAttackBoost:(int32_t) value;
- (FullEquipProto_Builder*) clearAttackBoost;

- (BOOL) hasDefenseBoost;
- (int32_t) defenseBoost;
- (FullEquipProto_Builder*) setDefenseBoost:(int32_t) value;
- (FullEquipProto_Builder*) clearDefenseBoost;

- (BOOL) hasMinLevel;
- (int32_t) minLevel;
- (FullEquipProto_Builder*) setMinLevel:(int32_t) value;
- (FullEquipProto_Builder*) clearMinLevel;

- (BOOL) hasCoinPrice;
- (int32_t) coinPrice;
- (FullEquipProto_Builder*) setCoinPrice:(int32_t) value;
- (FullEquipProto_Builder*) clearCoinPrice;

- (BOOL) hasDiamondPrice;
- (int32_t) diamondPrice;
- (FullEquipProto_Builder*) setDiamondPrice:(int32_t) value;
- (FullEquipProto_Builder*) clearDiamondPrice;

- (BOOL) hasChanceOfLoss;
- (Float32) chanceOfLoss;
- (FullEquipProto_Builder*) setChanceOfLoss:(Float32) value;
- (FullEquipProto_Builder*) clearChanceOfLoss;

- (BOOL) hasRarity;
- (FullEquipProto_Rarity) rarity;
- (FullEquipProto_Builder*) setRarity:(FullEquipProto_Rarity) value;
- (FullEquipProto_Builder*) clearRarity;
@end

@interface FullUserStructureProto : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasStructId_:1;
  BOOL hasLevel_:1;
  BOOL hasLastRetrieved_:1;
  BOOL hasCoordinates_:1;
  int32_t userId;
  int32_t structId;
  int32_t level;
  NSString* lastRetrieved;
  CoordinateProto* coordinates;
}
- (BOOL) hasUserId;
- (BOOL) hasStructId;
- (BOOL) hasCoordinates;
- (BOOL) hasLastRetrieved;
- (BOOL) hasLevel;
@property (readonly) int32_t userId;
@property (readonly) int32_t structId;
@property (readonly, retain) CoordinateProto* coordinates;
@property (readonly, retain) NSString* lastRetrieved;
@property (readonly) int32_t level;

+ (FullUserStructureProto*) defaultInstance;
- (FullUserStructureProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FullUserStructureProto_Builder*) builder;
+ (FullUserStructureProto_Builder*) builder;
+ (FullUserStructureProto_Builder*) builderWithPrototype:(FullUserStructureProto*) prototype;

+ (FullUserStructureProto*) parseFromData:(NSData*) data;
+ (FullUserStructureProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullUserStructureProto*) parseFromInputStream:(NSInputStream*) input;
+ (FullUserStructureProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullUserStructureProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FullUserStructureProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FullUserStructureProto_Builder : PBGeneratedMessage_Builder {
@private
  FullUserStructureProto* result;
}

- (FullUserStructureProto*) defaultInstance;

- (FullUserStructureProto_Builder*) clear;
- (FullUserStructureProto_Builder*) clone;

- (FullUserStructureProto*) build;
- (FullUserStructureProto*) buildPartial;

- (FullUserStructureProto_Builder*) mergeFrom:(FullUserStructureProto*) other;
- (FullUserStructureProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FullUserStructureProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (FullUserStructureProto_Builder*) setUserId:(int32_t) value;
- (FullUserStructureProto_Builder*) clearUserId;

- (BOOL) hasStructId;
- (int32_t) structId;
- (FullUserStructureProto_Builder*) setStructId:(int32_t) value;
- (FullUserStructureProto_Builder*) clearStructId;

- (BOOL) hasCoordinates;
- (CoordinateProto*) coordinates;
- (FullUserStructureProto_Builder*) setCoordinates:(CoordinateProto*) value;
- (FullUserStructureProto_Builder*) setCoordinatesBuilder:(CoordinateProto_Builder*) builderForValue;
- (FullUserStructureProto_Builder*) mergeCoordinates:(CoordinateProto*) value;
- (FullUserStructureProto_Builder*) clearCoordinates;

- (BOOL) hasLastRetrieved;
- (NSString*) lastRetrieved;
- (FullUserStructureProto_Builder*) setLastRetrieved:(NSString*) value;
- (FullUserStructureProto_Builder*) clearLastRetrieved;

- (BOOL) hasLevel;
- (int32_t) level;
- (FullUserStructureProto_Builder*) setLevel:(int32_t) value;
- (FullUserStructureProto_Builder*) clearLevel;
@end

@interface FullTaskProto : PBGeneratedMessage {
@private
  BOOL hasChanceOfEquipLoot_:1;
  BOOL hasTaskId_:1;
  BOOL hasCityId_:1;
  BOOL hasNumRequiredForCompletion_:1;
  BOOL hasEnergyCost_:1;
  BOOL hasMinCoinsGained_:1;
  BOOL hasMaxCoinsGained_:1;
  BOOL hasExpGained_:1;
  BOOL hasAssetNumWithinCity_:1;
  BOOL hasName_:1;
  Float32 chanceOfEquipLoot;
  int32_t taskId;
  int32_t cityId;
  int32_t numRequiredForCompletion;
  int32_t energyCost;
  int32_t minCoinsGained;
  int32_t maxCoinsGained;
  int32_t expGained;
  int32_t assetNumWithinCity;
  NSString* name;
  NSMutableArray* mutablePotentialLootEquipIdsList;
}
- (BOOL) hasTaskId;
- (BOOL) hasName;
- (BOOL) hasCityId;
- (BOOL) hasNumRequiredForCompletion;
- (BOOL) hasEnergyCost;
- (BOOL) hasMinCoinsGained;
- (BOOL) hasMaxCoinsGained;
- (BOOL) hasChanceOfEquipLoot;
- (BOOL) hasExpGained;
- (BOOL) hasAssetNumWithinCity;
@property (readonly) int32_t taskId;
@property (readonly, retain) NSString* name;
@property (readonly) int32_t cityId;
@property (readonly) int32_t numRequiredForCompletion;
@property (readonly) int32_t energyCost;
@property (readonly) int32_t minCoinsGained;
@property (readonly) int32_t maxCoinsGained;
@property (readonly) Float32 chanceOfEquipLoot;
@property (readonly) int32_t expGained;
@property (readonly) int32_t assetNumWithinCity;
- (NSArray*) potentialLootEquipIdsList;
- (int32_t) potentialLootEquipIdsAtIndex:(int32_t) index;

+ (FullTaskProto*) defaultInstance;
- (FullTaskProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FullTaskProto_Builder*) builder;
+ (FullTaskProto_Builder*) builder;
+ (FullTaskProto_Builder*) builderWithPrototype:(FullTaskProto*) prototype;

+ (FullTaskProto*) parseFromData:(NSData*) data;
+ (FullTaskProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullTaskProto*) parseFromInputStream:(NSInputStream*) input;
+ (FullTaskProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullTaskProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FullTaskProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FullTaskProto_Builder : PBGeneratedMessage_Builder {
@private
  FullTaskProto* result;
}

- (FullTaskProto*) defaultInstance;

- (FullTaskProto_Builder*) clear;
- (FullTaskProto_Builder*) clone;

- (FullTaskProto*) build;
- (FullTaskProto*) buildPartial;

- (FullTaskProto_Builder*) mergeFrom:(FullTaskProto*) other;
- (FullTaskProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FullTaskProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTaskId;
- (int32_t) taskId;
- (FullTaskProto_Builder*) setTaskId:(int32_t) value;
- (FullTaskProto_Builder*) clearTaskId;

- (BOOL) hasName;
- (NSString*) name;
- (FullTaskProto_Builder*) setName:(NSString*) value;
- (FullTaskProto_Builder*) clearName;

- (BOOL) hasCityId;
- (int32_t) cityId;
- (FullTaskProto_Builder*) setCityId:(int32_t) value;
- (FullTaskProto_Builder*) clearCityId;

- (BOOL) hasNumRequiredForCompletion;
- (int32_t) numRequiredForCompletion;
- (FullTaskProto_Builder*) setNumRequiredForCompletion:(int32_t) value;
- (FullTaskProto_Builder*) clearNumRequiredForCompletion;

- (BOOL) hasEnergyCost;
- (int32_t) energyCost;
- (FullTaskProto_Builder*) setEnergyCost:(int32_t) value;
- (FullTaskProto_Builder*) clearEnergyCost;

- (BOOL) hasMinCoinsGained;
- (int32_t) minCoinsGained;
- (FullTaskProto_Builder*) setMinCoinsGained:(int32_t) value;
- (FullTaskProto_Builder*) clearMinCoinsGained;

- (BOOL) hasMaxCoinsGained;
- (int32_t) maxCoinsGained;
- (FullTaskProto_Builder*) setMaxCoinsGained:(int32_t) value;
- (FullTaskProto_Builder*) clearMaxCoinsGained;

- (BOOL) hasChanceOfEquipLoot;
- (Float32) chanceOfEquipLoot;
- (FullTaskProto_Builder*) setChanceOfEquipLoot:(Float32) value;
- (FullTaskProto_Builder*) clearChanceOfEquipLoot;

- (NSArray*) potentialLootEquipIdsList;
- (int32_t) potentialLootEquipIdsAtIndex:(int32_t) index;
- (FullTaskProto_Builder*) replacePotentialLootEquipIdsAtIndex:(int32_t) index with:(int32_t) value;
- (FullTaskProto_Builder*) addPotentialLootEquipIds:(int32_t) value;
- (FullTaskProto_Builder*) addAllPotentialLootEquipIds:(NSArray*) values;
- (FullTaskProto_Builder*) clearPotentialLootEquipIdsList;

- (BOOL) hasExpGained;
- (int32_t) expGained;
- (FullTaskProto_Builder*) setExpGained:(int32_t) value;
- (FullTaskProto_Builder*) clearExpGained;

- (BOOL) hasAssetNumWithinCity;
- (int32_t) assetNumWithinCity;
- (FullTaskProto_Builder*) setAssetNumWithinCity:(int32_t) value;
- (FullTaskProto_Builder*) clearAssetNumWithinCity;
@end

@interface CoordinateProto : PBGeneratedMessage {
@private
  BOOL hasX_:1;
  BOOL hasY_:1;
  int32_t x;
  int32_t y;
}
- (BOOL) hasX;
- (BOOL) hasY;
@property (readonly) int32_t x;
@property (readonly) int32_t y;

+ (CoordinateProto*) defaultInstance;
- (CoordinateProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CoordinateProto_Builder*) builder;
+ (CoordinateProto_Builder*) builder;
+ (CoordinateProto_Builder*) builderWithPrototype:(CoordinateProto*) prototype;

+ (CoordinateProto*) parseFromData:(NSData*) data;
+ (CoordinateProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CoordinateProto*) parseFromInputStream:(NSInputStream*) input;
+ (CoordinateProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CoordinateProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CoordinateProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CoordinateProto_Builder : PBGeneratedMessage_Builder {
@private
  CoordinateProto* result;
}

- (CoordinateProto*) defaultInstance;

- (CoordinateProto_Builder*) clear;
- (CoordinateProto_Builder*) clone;

- (CoordinateProto*) build;
- (CoordinateProto*) buildPartial;

- (CoordinateProto_Builder*) mergeFrom:(CoordinateProto*) other;
- (CoordinateProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CoordinateProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasX;
- (int32_t) x;
- (CoordinateProto_Builder*) setX:(int32_t) value;
- (CoordinateProto_Builder*) clearX;

- (BOOL) hasY;
- (int32_t) y;
- (CoordinateProto_Builder*) setY:(int32_t) value;
- (CoordinateProto_Builder*) clearY;
@end

@interface LocationProto : PBGeneratedMessage {
@private
  BOOL hasLatitude_:1;
  BOOL hasLongitude_:1;
  Float32 latitude;
  Float32 longitude;
}
- (BOOL) hasLatitude;
- (BOOL) hasLongitude;
@property (readonly) Float32 latitude;
@property (readonly) Float32 longitude;

+ (LocationProto*) defaultInstance;
- (LocationProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LocationProto_Builder*) builder;
+ (LocationProto_Builder*) builder;
+ (LocationProto_Builder*) builderWithPrototype:(LocationProto*) prototype;

+ (LocationProto*) parseFromData:(NSData*) data;
+ (LocationProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LocationProto*) parseFromInputStream:(NSInputStream*) input;
+ (LocationProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LocationProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LocationProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LocationProto_Builder : PBGeneratedMessage_Builder {
@private
  LocationProto* result;
}

- (LocationProto*) defaultInstance;

- (LocationProto_Builder*) clear;
- (LocationProto_Builder*) clone;

- (LocationProto*) build;
- (LocationProto*) buildPartial;

- (LocationProto_Builder*) mergeFrom:(LocationProto*) other;
- (LocationProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LocationProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLatitude;
- (Float32) latitude;
- (LocationProto_Builder*) setLatitude:(Float32) value;
- (LocationProto_Builder*) clearLatitude;

- (BOOL) hasLongitude;
- (Float32) longitude;
- (LocationProto_Builder*) setLongitude:(Float32) value;
- (LocationProto_Builder*) clearLongitude;
@end

@interface FullMarketplacePostProto : PBGeneratedMessage {
@private
  BOOL hasTimeOfPost_:1;
  BOOL hasMarketplacePostId_:1;
  BOOL hasPosterId_:1;
  BOOL hasPostedEquipId_:1;
  BOOL hasPostedWood_:1;
  BOOL hasPostedDiamonds_:1;
  BOOL hasPostedCoins_:1;
  BOOL hasDiamondCost_:1;
  BOOL hasCoinCost_:1;
  BOOL hasWoodCost_:1;
  BOOL hasPostType_:1;
  int64_t timeOfPost;
  int32_t marketplacePostId;
  int32_t posterId;
  int32_t postedEquipId;
  int32_t postedWood;
  int32_t postedDiamonds;
  int32_t postedCoins;
  int32_t diamondCost;
  int32_t coinCost;
  int32_t woodCost;
  MarketplacePostType postType;
}
- (BOOL) hasMarketplacePostId;
- (BOOL) hasPosterId;
- (BOOL) hasPostType;
- (BOOL) hasTimeOfPost;
- (BOOL) hasPostedEquipId;
- (BOOL) hasPostedWood;
- (BOOL) hasPostedDiamonds;
- (BOOL) hasPostedCoins;
- (BOOL) hasDiamondCost;
- (BOOL) hasCoinCost;
- (BOOL) hasWoodCost;
@property (readonly) int32_t marketplacePostId;
@property (readonly) int32_t posterId;
@property (readonly) MarketplacePostType postType;
@property (readonly) int64_t timeOfPost;
@property (readonly) int32_t postedEquipId;
@property (readonly) int32_t postedWood;
@property (readonly) int32_t postedDiamonds;
@property (readonly) int32_t postedCoins;
@property (readonly) int32_t diamondCost;
@property (readonly) int32_t coinCost;
@property (readonly) int32_t woodCost;

+ (FullMarketplacePostProto*) defaultInstance;
- (FullMarketplacePostProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FullMarketplacePostProto_Builder*) builder;
+ (FullMarketplacePostProto_Builder*) builder;
+ (FullMarketplacePostProto_Builder*) builderWithPrototype:(FullMarketplacePostProto*) prototype;

+ (FullMarketplacePostProto*) parseFromData:(NSData*) data;
+ (FullMarketplacePostProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullMarketplacePostProto*) parseFromInputStream:(NSInputStream*) input;
+ (FullMarketplacePostProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullMarketplacePostProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FullMarketplacePostProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FullMarketplacePostProto_Builder : PBGeneratedMessage_Builder {
@private
  FullMarketplacePostProto* result;
}

- (FullMarketplacePostProto*) defaultInstance;

- (FullMarketplacePostProto_Builder*) clear;
- (FullMarketplacePostProto_Builder*) clone;

- (FullMarketplacePostProto*) build;
- (FullMarketplacePostProto*) buildPartial;

- (FullMarketplacePostProto_Builder*) mergeFrom:(FullMarketplacePostProto*) other;
- (FullMarketplacePostProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FullMarketplacePostProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMarketplacePostId;
- (int32_t) marketplacePostId;
- (FullMarketplacePostProto_Builder*) setMarketplacePostId:(int32_t) value;
- (FullMarketplacePostProto_Builder*) clearMarketplacePostId;

- (BOOL) hasPosterId;
- (int32_t) posterId;
- (FullMarketplacePostProto_Builder*) setPosterId:(int32_t) value;
- (FullMarketplacePostProto_Builder*) clearPosterId;

- (BOOL) hasPostType;
- (MarketplacePostType) postType;
- (FullMarketplacePostProto_Builder*) setPostType:(MarketplacePostType) value;
- (FullMarketplacePostProto_Builder*) clearPostType;

- (BOOL) hasTimeOfPost;
- (int64_t) timeOfPost;
- (FullMarketplacePostProto_Builder*) setTimeOfPost:(int64_t) value;
- (FullMarketplacePostProto_Builder*) clearTimeOfPost;

- (BOOL) hasPostedEquipId;
- (int32_t) postedEquipId;
- (FullMarketplacePostProto_Builder*) setPostedEquipId:(int32_t) value;
- (FullMarketplacePostProto_Builder*) clearPostedEquipId;

- (BOOL) hasPostedWood;
- (int32_t) postedWood;
- (FullMarketplacePostProto_Builder*) setPostedWood:(int32_t) value;
- (FullMarketplacePostProto_Builder*) clearPostedWood;

- (BOOL) hasPostedDiamonds;
- (int32_t) postedDiamonds;
- (FullMarketplacePostProto_Builder*) setPostedDiamonds:(int32_t) value;
- (FullMarketplacePostProto_Builder*) clearPostedDiamonds;

- (BOOL) hasPostedCoins;
- (int32_t) postedCoins;
- (FullMarketplacePostProto_Builder*) setPostedCoins:(int32_t) value;
- (FullMarketplacePostProto_Builder*) clearPostedCoins;

- (BOOL) hasDiamondCost;
- (int32_t) diamondCost;
- (FullMarketplacePostProto_Builder*) setDiamondCost:(int32_t) value;
- (FullMarketplacePostProto_Builder*) clearDiamondCost;

- (BOOL) hasCoinCost;
- (int32_t) coinCost;
- (FullMarketplacePostProto_Builder*) setCoinCost:(int32_t) value;
- (FullMarketplacePostProto_Builder*) clearCoinCost;

- (BOOL) hasWoodCost;
- (int32_t) woodCost;
- (FullMarketplacePostProto_Builder*) setWoodCost:(int32_t) value;
- (FullMarketplacePostProto_Builder*) clearWoodCost;
@end

