// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class BuildStructJobProto;
@class BuildStructJobProto_Builder;
@class CoordinateProto;
@class CoordinateProto_Builder;
@class DefeatTypeJobProto;
@class DefeatTypeJobProto_Builder;
@class FullCityProto;
@class FullCityProto_Builder;
@class FullEquipProto;
@class FullEquipProto_Builder;
@class FullMarketplacePostProto;
@class FullMarketplacePostProto_Builder;
@class FullQuestProto;
@class FullQuestProto_Builder;
@class FullStructureProto;
@class FullStructureProto_Builder;
@class FullTaskProto;
@class FullTaskProto_Builder;
@class FullTaskProto_FullTaskEquipReqProto;
@class FullTaskProto_FullTaskEquipReqProto_Builder;
@class FullUserEquipProto;
@class FullUserEquipProto_Builder;
@class FullUserProto;
@class FullUserProto_Builder;
@class FullUserQuestDataLarge;
@class FullUserQuestDataLarge_Builder;
@class FullUserStructureProto;
@class FullUserStructureProto_Builder;
@class LocationProto;
@class LocationProto_Builder;
@class MinimumUserBuildStructJobProto;
@class MinimumUserBuildStructJobProto_Builder;
@class MinimumUserDefeatTypeJobProto;
@class MinimumUserDefeatTypeJobProto_Builder;
@class MinimumUserPossessEquipJobProto;
@class MinimumUserPossessEquipJobProto_Builder;
@class MinimumUserProto;
@class MinimumUserProto_Builder;
@class MinimumUserTaskProto;
@class MinimumUserTaskProto_Builder;
@class MinimumUserUpgradeStructJobProto;
@class MinimumUserUpgradeStructJobProto_Builder;
@class PossessEquipJobProto;
@class PossessEquipJobProto_Builder;
@class UpgradeStructJobProto;
@class UpgradeStructJobProto_Builder;
typedef enum {
  UserTypeGoodWarrior = 0,
  UserTypeGoodArcher = 1,
  UserTypeGoodMage = 2,
  UserTypeBadWarrior = 3,
  UserTypeBadArcher = 4,
  UserTypeBadMage = 5,
} UserType;

BOOL UserTypeIsValidValue(UserType value);

typedef enum {
  MarketplacePostTypeEquipPost = 0,
  MarketplacePostTypeWoodPost = 1,
  MarketplacePostTypeDiamondPost = 2,
  MarketplacePostTypeCoinPost = 3,
} MarketplacePostType;

BOOL MarketplacePostTypeIsValidValue(MarketplacePostType value);

typedef enum {
  MarketplaceJobRequirementTypeBuy = 0,
  MarketplaceJobRequirementTypeSell = 1,
} MarketplaceJobRequirementType;

BOOL MarketplaceJobRequirementTypeIsValidValue(MarketplaceJobRequirementType value);

typedef enum {
  CritStructTypeAviary = 0,
  CritStructTypeLumbermill = 1,
  CritStructTypeCarpenter = 2,
  CritStructTypeVault = 3,
  CritStructTypeArmory = 4,
  CritStructTypeMarketplace = 5,
} CritStructType;

BOOL CritStructTypeIsValidValue(CritStructType value);

typedef enum {
  FullEquipProto_RarityCommon = 0,
  FullEquipProto_RarityUncommon = 1,
  FullEquipProto_RarityRare = 2,
  FullEquipProto_RarityEpic = 3,
  FullEquipProto_RarityLegendary = 4,
} FullEquipProto_Rarity;

BOOL FullEquipProto_RarityIsValidValue(FullEquipProto_Rarity value);

typedef enum {
  FullEquipProto_EquipTypeWeapon = 0,
  FullEquipProto_EquipTypeArmor = 1,
  FullEquipProto_EquipTypeAccessory = 2,
} FullEquipProto_EquipType;

BOOL FullEquipProto_EquipTypeIsValidValue(FullEquipProto_EquipType value);

typedef enum {
  FullEquipProto_ClassTypeWarrior = 0,
  FullEquipProto_ClassTypeArcher = 1,
  FullEquipProto_ClassTypeMage = 2,
} FullEquipProto_ClassType;

BOOL FullEquipProto_ClassTypeIsValidValue(FullEquipProto_ClassType value);


@interface InfoRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface MinimumUserProto : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasName_:1;
  BOOL hasUserType_:1;
  int32_t userId;
  NSString* name;
  UserType userType;
}
- (BOOL) hasUserId;
- (BOOL) hasName;
- (BOOL) hasUserType;
@property (readonly) int32_t userId;
@property (readonly, retain) NSString* name;
@property (readonly) UserType userType;

+ (MinimumUserProto*) defaultInstance;
- (MinimumUserProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MinimumUserProto_Builder*) builder;
+ (MinimumUserProto_Builder*) builder;
+ (MinimumUserProto_Builder*) builderWithPrototype:(MinimumUserProto*) prototype;

+ (MinimumUserProto*) parseFromData:(NSData*) data;
+ (MinimumUserProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MinimumUserProto*) parseFromInputStream:(NSInputStream*) input;
+ (MinimumUserProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MinimumUserProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MinimumUserProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MinimumUserProto_Builder : PBGeneratedMessage_Builder {
@private
  MinimumUserProto* result;
}

- (MinimumUserProto*) defaultInstance;

- (MinimumUserProto_Builder*) clear;
- (MinimumUserProto_Builder*) clone;

- (MinimumUserProto*) build;
- (MinimumUserProto*) buildPartial;

- (MinimumUserProto_Builder*) mergeFrom:(MinimumUserProto*) other;
- (MinimumUserProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MinimumUserProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (MinimumUserProto_Builder*) setUserId:(int32_t) value;
- (MinimumUserProto_Builder*) clearUserId;

- (BOOL) hasName;
- (NSString*) name;
- (MinimumUserProto_Builder*) setName:(NSString*) value;
- (MinimumUserProto_Builder*) clearName;

- (BOOL) hasUserType;
- (UserType) userType;
- (MinimumUserProto_Builder*) setUserType:(UserType) value;
- (MinimumUserProto_Builder*) clearUserType;
@end

@interface FullUserProto : PBGeneratedMessage {
@private
  BOOL hasNumPostsInMarketplace_:1;
  BOOL hasNumReferrals_:1;
  BOOL hasHourlyCoins_:1;
  BOOL hasBattlesLost_:1;
  BOOL hasBattlesWon_:1;
  BOOL hasTasksCompleted_:1;
  BOOL hasExperience_:1;
  BOOL hasVaultBalance_:1;
  BOOL hasMarketplaceWoodEarnings_:1;
  BOOL hasMarketplaceCoinsEarnings_:1;
  BOOL hasMarketplaceDiamondsEarnings_:1;
  BOOL hasWood_:1;
  BOOL hasCoins_:1;
  BOOL hasDiamonds_:1;
  BOOL hasStaminaMax_:1;
  BOOL hasEnergyMax_:1;
  BOOL hasHealthMax_:1;
  BOOL hasSkillPoints_:1;
  BOOL hasEnergy_:1;
  BOOL hasStamina_:1;
  BOOL hasDefense_:1;
  BOOL hasAttack_:1;
  BOOL hasLevel_:1;
  BOOL hasUserId_:1;
  BOOL hasArmyCode_:1;
  BOOL hasName_:1;
  BOOL hasUdid_:1;
  BOOL hasUserLocation_:1;
  BOOL hasUserType_:1;
  int32_t numPostsInMarketplace;
  int32_t numReferrals;
  int32_t hourlyCoins;
  int32_t battlesLost;
  int32_t battlesWon;
  int32_t tasksCompleted;
  int32_t experience;
  int32_t vaultBalance;
  int32_t marketplaceWoodEarnings;
  int32_t marketplaceCoinsEarnings;
  int32_t marketplaceDiamondsEarnings;
  int32_t wood;
  int32_t coins;
  int32_t diamonds;
  int32_t staminaMax;
  int32_t energyMax;
  int32_t healthMax;
  int32_t skillPoints;
  int32_t energy;
  int32_t stamina;
  int32_t defense;
  int32_t attack;
  int32_t level;
  int32_t userId;
  NSString* armyCode;
  NSString* name;
  NSString* udid;
  LocationProto* userLocation;
  UserType userType;
}
- (BOOL) hasUserId;
- (BOOL) hasName;
- (BOOL) hasLevel;
- (BOOL) hasUserType;
- (BOOL) hasAttack;
- (BOOL) hasDefense;
- (BOOL) hasStamina;
- (BOOL) hasEnergy;
- (BOOL) hasSkillPoints;
- (BOOL) hasHealthMax;
- (BOOL) hasEnergyMax;
- (BOOL) hasStaminaMax;
- (BOOL) hasDiamonds;
- (BOOL) hasCoins;
- (BOOL) hasWood;
- (BOOL) hasMarketplaceDiamondsEarnings;
- (BOOL) hasMarketplaceCoinsEarnings;
- (BOOL) hasMarketplaceWoodEarnings;
- (BOOL) hasVaultBalance;
- (BOOL) hasExperience;
- (BOOL) hasTasksCompleted;
- (BOOL) hasBattlesWon;
- (BOOL) hasBattlesLost;
- (BOOL) hasHourlyCoins;
- (BOOL) hasArmyCode;
- (BOOL) hasNumReferrals;
- (BOOL) hasUdid;
- (BOOL) hasUserLocation;
- (BOOL) hasNumPostsInMarketplace;
@property (readonly) int32_t userId;
@property (readonly, retain) NSString* name;
@property (readonly) int32_t level;
@property (readonly) UserType userType;
@property (readonly) int32_t attack;
@property (readonly) int32_t defense;
@property (readonly) int32_t stamina;
@property (readonly) int32_t energy;
@property (readonly) int32_t skillPoints;
@property (readonly) int32_t healthMax;
@property (readonly) int32_t energyMax;
@property (readonly) int32_t staminaMax;
@property (readonly) int32_t diamonds;
@property (readonly) int32_t coins;
@property (readonly) int32_t wood;
@property (readonly) int32_t marketplaceDiamondsEarnings;
@property (readonly) int32_t marketplaceCoinsEarnings;
@property (readonly) int32_t marketplaceWoodEarnings;
@property (readonly) int32_t vaultBalance;
@property (readonly) int32_t experience;
@property (readonly) int32_t tasksCompleted;
@property (readonly) int32_t battlesWon;
@property (readonly) int32_t battlesLost;
@property (readonly) int32_t hourlyCoins;
@property (readonly, retain) NSString* armyCode;
@property (readonly) int32_t numReferrals;
@property (readonly, retain) NSString* udid;
@property (readonly, retain) LocationProto* userLocation;
@property (readonly) int32_t numPostsInMarketplace;

+ (FullUserProto*) defaultInstance;
- (FullUserProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FullUserProto_Builder*) builder;
+ (FullUserProto_Builder*) builder;
+ (FullUserProto_Builder*) builderWithPrototype:(FullUserProto*) prototype;

+ (FullUserProto*) parseFromData:(NSData*) data;
+ (FullUserProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullUserProto*) parseFromInputStream:(NSInputStream*) input;
+ (FullUserProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullUserProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FullUserProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FullUserProto_Builder : PBGeneratedMessage_Builder {
@private
  FullUserProto* result;
}

- (FullUserProto*) defaultInstance;

- (FullUserProto_Builder*) clear;
- (FullUserProto_Builder*) clone;

- (FullUserProto*) build;
- (FullUserProto*) buildPartial;

- (FullUserProto_Builder*) mergeFrom:(FullUserProto*) other;
- (FullUserProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FullUserProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (FullUserProto_Builder*) setUserId:(int32_t) value;
- (FullUserProto_Builder*) clearUserId;

- (BOOL) hasName;
- (NSString*) name;
- (FullUserProto_Builder*) setName:(NSString*) value;
- (FullUserProto_Builder*) clearName;

- (BOOL) hasLevel;
- (int32_t) level;
- (FullUserProto_Builder*) setLevel:(int32_t) value;
- (FullUserProto_Builder*) clearLevel;

- (BOOL) hasUserType;
- (UserType) userType;
- (FullUserProto_Builder*) setUserType:(UserType) value;
- (FullUserProto_Builder*) clearUserType;

- (BOOL) hasAttack;
- (int32_t) attack;
- (FullUserProto_Builder*) setAttack:(int32_t) value;
- (FullUserProto_Builder*) clearAttack;

- (BOOL) hasDefense;
- (int32_t) defense;
- (FullUserProto_Builder*) setDefense:(int32_t) value;
- (FullUserProto_Builder*) clearDefense;

- (BOOL) hasStamina;
- (int32_t) stamina;
- (FullUserProto_Builder*) setStamina:(int32_t) value;
- (FullUserProto_Builder*) clearStamina;

- (BOOL) hasEnergy;
- (int32_t) energy;
- (FullUserProto_Builder*) setEnergy:(int32_t) value;
- (FullUserProto_Builder*) clearEnergy;

- (BOOL) hasSkillPoints;
- (int32_t) skillPoints;
- (FullUserProto_Builder*) setSkillPoints:(int32_t) value;
- (FullUserProto_Builder*) clearSkillPoints;

- (BOOL) hasHealthMax;
- (int32_t) healthMax;
- (FullUserProto_Builder*) setHealthMax:(int32_t) value;
- (FullUserProto_Builder*) clearHealthMax;

- (BOOL) hasEnergyMax;
- (int32_t) energyMax;
- (FullUserProto_Builder*) setEnergyMax:(int32_t) value;
- (FullUserProto_Builder*) clearEnergyMax;

- (BOOL) hasStaminaMax;
- (int32_t) staminaMax;
- (FullUserProto_Builder*) setStaminaMax:(int32_t) value;
- (FullUserProto_Builder*) clearStaminaMax;

- (BOOL) hasDiamonds;
- (int32_t) diamonds;
- (FullUserProto_Builder*) setDiamonds:(int32_t) value;
- (FullUserProto_Builder*) clearDiamonds;

- (BOOL) hasCoins;
- (int32_t) coins;
- (FullUserProto_Builder*) setCoins:(int32_t) value;
- (FullUserProto_Builder*) clearCoins;

- (BOOL) hasWood;
- (int32_t) wood;
- (FullUserProto_Builder*) setWood:(int32_t) value;
- (FullUserProto_Builder*) clearWood;

- (BOOL) hasMarketplaceDiamondsEarnings;
- (int32_t) marketplaceDiamondsEarnings;
- (FullUserProto_Builder*) setMarketplaceDiamondsEarnings:(int32_t) value;
- (FullUserProto_Builder*) clearMarketplaceDiamondsEarnings;

- (BOOL) hasMarketplaceCoinsEarnings;
- (int32_t) marketplaceCoinsEarnings;
- (FullUserProto_Builder*) setMarketplaceCoinsEarnings:(int32_t) value;
- (FullUserProto_Builder*) clearMarketplaceCoinsEarnings;

- (BOOL) hasMarketplaceWoodEarnings;
- (int32_t) marketplaceWoodEarnings;
- (FullUserProto_Builder*) setMarketplaceWoodEarnings:(int32_t) value;
- (FullUserProto_Builder*) clearMarketplaceWoodEarnings;

- (BOOL) hasVaultBalance;
- (int32_t) vaultBalance;
- (FullUserProto_Builder*) setVaultBalance:(int32_t) value;
- (FullUserProto_Builder*) clearVaultBalance;

- (BOOL) hasExperience;
- (int32_t) experience;
- (FullUserProto_Builder*) setExperience:(int32_t) value;
- (FullUserProto_Builder*) clearExperience;

- (BOOL) hasTasksCompleted;
- (int32_t) tasksCompleted;
- (FullUserProto_Builder*) setTasksCompleted:(int32_t) value;
- (FullUserProto_Builder*) clearTasksCompleted;

- (BOOL) hasBattlesWon;
- (int32_t) battlesWon;
- (FullUserProto_Builder*) setBattlesWon:(int32_t) value;
- (FullUserProto_Builder*) clearBattlesWon;

- (BOOL) hasBattlesLost;
- (int32_t) battlesLost;
- (FullUserProto_Builder*) setBattlesLost:(int32_t) value;
- (FullUserProto_Builder*) clearBattlesLost;

- (BOOL) hasHourlyCoins;
- (int32_t) hourlyCoins;
- (FullUserProto_Builder*) setHourlyCoins:(int32_t) value;
- (FullUserProto_Builder*) clearHourlyCoins;

- (BOOL) hasArmyCode;
- (NSString*) armyCode;
- (FullUserProto_Builder*) setArmyCode:(NSString*) value;
- (FullUserProto_Builder*) clearArmyCode;

- (BOOL) hasNumReferrals;
- (int32_t) numReferrals;
- (FullUserProto_Builder*) setNumReferrals:(int32_t) value;
- (FullUserProto_Builder*) clearNumReferrals;

- (BOOL) hasUdid;
- (NSString*) udid;
- (FullUserProto_Builder*) setUdid:(NSString*) value;
- (FullUserProto_Builder*) clearUdid;

- (BOOL) hasUserLocation;
- (LocationProto*) userLocation;
- (FullUserProto_Builder*) setUserLocation:(LocationProto*) value;
- (FullUserProto_Builder*) setUserLocationBuilder:(LocationProto_Builder*) builderForValue;
- (FullUserProto_Builder*) mergeUserLocation:(LocationProto*) value;
- (FullUserProto_Builder*) clearUserLocation;

- (BOOL) hasNumPostsInMarketplace;
- (int32_t) numPostsInMarketplace;
- (FullUserProto_Builder*) setNumPostsInMarketplace:(int32_t) value;
- (FullUserProto_Builder*) clearNumPostsInMarketplace;
@end

@interface FullEquipProto : PBGeneratedMessage {
@private
  BOOL hasChanceOfLoss_:1;
  BOOL hasEquipId_:1;
  BOOL hasAttackBoost_:1;
  BOOL hasDefenseBoost_:1;
  BOOL hasMinLevel_:1;
  BOOL hasCoinPrice_:1;
  BOOL hasDiamondPrice_:1;
  BOOL hasName_:1;
  BOOL hasEquipType_:1;
  BOOL hasClassType_:1;
  BOOL hasRarity_:1;
  Float32 chanceOfLoss;
  int32_t equipId;
  int32_t attackBoost;
  int32_t defenseBoost;
  int32_t minLevel;
  int32_t coinPrice;
  int32_t diamondPrice;
  NSString* name;
  FullEquipProto_EquipType equipType;
  FullEquipProto_ClassType classType;
  FullEquipProto_Rarity rarity;
}
- (BOOL) hasEquipId;
- (BOOL) hasName;
- (BOOL) hasEquipType;
- (BOOL) hasClassType;
- (BOOL) hasAttackBoost;
- (BOOL) hasDefenseBoost;
- (BOOL) hasMinLevel;
- (BOOL) hasCoinPrice;
- (BOOL) hasDiamondPrice;
- (BOOL) hasChanceOfLoss;
- (BOOL) hasRarity;
@property (readonly) int32_t equipId;
@property (readonly, retain) NSString* name;
@property (readonly) FullEquipProto_EquipType equipType;
@property (readonly) FullEquipProto_ClassType classType;
@property (readonly) int32_t attackBoost;
@property (readonly) int32_t defenseBoost;
@property (readonly) int32_t minLevel;
@property (readonly) int32_t coinPrice;
@property (readonly) int32_t diamondPrice;
@property (readonly) Float32 chanceOfLoss;
@property (readonly) FullEquipProto_Rarity rarity;

+ (FullEquipProto*) defaultInstance;
- (FullEquipProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FullEquipProto_Builder*) builder;
+ (FullEquipProto_Builder*) builder;
+ (FullEquipProto_Builder*) builderWithPrototype:(FullEquipProto*) prototype;

+ (FullEquipProto*) parseFromData:(NSData*) data;
+ (FullEquipProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullEquipProto*) parseFromInputStream:(NSInputStream*) input;
+ (FullEquipProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullEquipProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FullEquipProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FullEquipProto_Builder : PBGeneratedMessage_Builder {
@private
  FullEquipProto* result;
}

- (FullEquipProto*) defaultInstance;

- (FullEquipProto_Builder*) clear;
- (FullEquipProto_Builder*) clone;

- (FullEquipProto*) build;
- (FullEquipProto*) buildPartial;

- (FullEquipProto_Builder*) mergeFrom:(FullEquipProto*) other;
- (FullEquipProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FullEquipProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasEquipId;
- (int32_t) equipId;
- (FullEquipProto_Builder*) setEquipId:(int32_t) value;
- (FullEquipProto_Builder*) clearEquipId;

- (BOOL) hasName;
- (NSString*) name;
- (FullEquipProto_Builder*) setName:(NSString*) value;
- (FullEquipProto_Builder*) clearName;

- (BOOL) hasEquipType;
- (FullEquipProto_EquipType) equipType;
- (FullEquipProto_Builder*) setEquipType:(FullEquipProto_EquipType) value;
- (FullEquipProto_Builder*) clearEquipType;

- (BOOL) hasClassType;
- (FullEquipProto_ClassType) classType;
- (FullEquipProto_Builder*) setClassType:(FullEquipProto_ClassType) value;
- (FullEquipProto_Builder*) clearClassType;

- (BOOL) hasAttackBoost;
- (int32_t) attackBoost;
- (FullEquipProto_Builder*) setAttackBoost:(int32_t) value;
- (FullEquipProto_Builder*) clearAttackBoost;

- (BOOL) hasDefenseBoost;
- (int32_t) defenseBoost;
- (FullEquipProto_Builder*) setDefenseBoost:(int32_t) value;
- (FullEquipProto_Builder*) clearDefenseBoost;

- (BOOL) hasMinLevel;
- (int32_t) minLevel;
- (FullEquipProto_Builder*) setMinLevel:(int32_t) value;
- (FullEquipProto_Builder*) clearMinLevel;

- (BOOL) hasCoinPrice;
- (int32_t) coinPrice;
- (FullEquipProto_Builder*) setCoinPrice:(int32_t) value;
- (FullEquipProto_Builder*) clearCoinPrice;

- (BOOL) hasDiamondPrice;
- (int32_t) diamondPrice;
- (FullEquipProto_Builder*) setDiamondPrice:(int32_t) value;
- (FullEquipProto_Builder*) clearDiamondPrice;

- (BOOL) hasChanceOfLoss;
- (Float32) chanceOfLoss;
- (FullEquipProto_Builder*) setChanceOfLoss:(Float32) value;
- (FullEquipProto_Builder*) clearChanceOfLoss;

- (BOOL) hasRarity;
- (FullEquipProto_Rarity) rarity;
- (FullEquipProto_Builder*) setRarity:(FullEquipProto_Rarity) value;
- (FullEquipProto_Builder*) clearRarity;
@end

@interface FullUserStructureProto : PBGeneratedMessage {
@private
  BOOL hasIsComplete_:1;
  BOOL hasLastRetrieved_:1;
  BOOL hasPurchaseTime_:1;
  BOOL hasId_:1;
  BOOL hasUserId_:1;
  BOOL hasStructId_:1;
  BOOL hasLevel_:1;
  BOOL hasCoordinates_:1;
  BOOL isComplete_:1;
  int64_t lastRetrieved;
  int64_t purchaseTime;
  int32_t id;
  int32_t userId;
  int32_t structId;
  int32_t level;
  CoordinateProto* coordinates;
}
- (BOOL) hasId;
- (BOOL) hasUserId;
- (BOOL) hasStructId;
- (BOOL) hasLastRetrieved;
- (BOOL) hasCoordinates;
- (BOOL) hasLevel;
- (BOOL) hasPurchaseTime;
- (BOOL) hasIsComplete;
@property (readonly) int32_t id;
@property (readonly) int32_t userId;
@property (readonly) int32_t structId;
@property (readonly) int64_t lastRetrieved;
@property (readonly, retain) CoordinateProto* coordinates;
@property (readonly) int32_t level;
@property (readonly) int64_t purchaseTime;
- (BOOL) isComplete;

+ (FullUserStructureProto*) defaultInstance;
- (FullUserStructureProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FullUserStructureProto_Builder*) builder;
+ (FullUserStructureProto_Builder*) builder;
+ (FullUserStructureProto_Builder*) builderWithPrototype:(FullUserStructureProto*) prototype;

+ (FullUserStructureProto*) parseFromData:(NSData*) data;
+ (FullUserStructureProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullUserStructureProto*) parseFromInputStream:(NSInputStream*) input;
+ (FullUserStructureProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullUserStructureProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FullUserStructureProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FullUserStructureProto_Builder : PBGeneratedMessage_Builder {
@private
  FullUserStructureProto* result;
}

- (FullUserStructureProto*) defaultInstance;

- (FullUserStructureProto_Builder*) clear;
- (FullUserStructureProto_Builder*) clone;

- (FullUserStructureProto*) build;
- (FullUserStructureProto*) buildPartial;

- (FullUserStructureProto_Builder*) mergeFrom:(FullUserStructureProto*) other;
- (FullUserStructureProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FullUserStructureProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (int32_t) id;
- (FullUserStructureProto_Builder*) setId:(int32_t) value;
- (FullUserStructureProto_Builder*) clearId;

- (BOOL) hasUserId;
- (int32_t) userId;
- (FullUserStructureProto_Builder*) setUserId:(int32_t) value;
- (FullUserStructureProto_Builder*) clearUserId;

- (BOOL) hasStructId;
- (int32_t) structId;
- (FullUserStructureProto_Builder*) setStructId:(int32_t) value;
- (FullUserStructureProto_Builder*) clearStructId;

- (BOOL) hasLastRetrieved;
- (int64_t) lastRetrieved;
- (FullUserStructureProto_Builder*) setLastRetrieved:(int64_t) value;
- (FullUserStructureProto_Builder*) clearLastRetrieved;

- (BOOL) hasCoordinates;
- (CoordinateProto*) coordinates;
- (FullUserStructureProto_Builder*) setCoordinates:(CoordinateProto*) value;
- (FullUserStructureProto_Builder*) setCoordinatesBuilder:(CoordinateProto_Builder*) builderForValue;
- (FullUserStructureProto_Builder*) mergeCoordinates:(CoordinateProto*) value;
- (FullUserStructureProto_Builder*) clearCoordinates;

- (BOOL) hasLevel;
- (int32_t) level;
- (FullUserStructureProto_Builder*) setLevel:(int32_t) value;
- (FullUserStructureProto_Builder*) clearLevel;

- (BOOL) hasPurchaseTime;
- (int64_t) purchaseTime;
- (FullUserStructureProto_Builder*) setPurchaseTime:(int64_t) value;
- (FullUserStructureProto_Builder*) clearPurchaseTime;

- (BOOL) hasIsComplete;
- (BOOL) isComplete;
- (FullUserStructureProto_Builder*) setIsComplete:(BOOL) value;
- (FullUserStructureProto_Builder*) clearIsComplete;
@end

@interface FullUserEquipProto : PBGeneratedMessage {
@private
  BOOL hasIsStolen_:1;
  BOOL hasUserId_:1;
  BOOL hasEquipId_:1;
  BOOL hasQuantity_:1;
  BOOL isStolen_:1;
  int32_t userId;
  int32_t equipId;
  int32_t quantity;
}
- (BOOL) hasUserId;
- (BOOL) hasEquipId;
- (BOOL) hasQuantity;
- (BOOL) hasIsStolen;
@property (readonly) int32_t userId;
@property (readonly) int32_t equipId;
@property (readonly) int32_t quantity;
- (BOOL) isStolen;

+ (FullUserEquipProto*) defaultInstance;
- (FullUserEquipProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FullUserEquipProto_Builder*) builder;
+ (FullUserEquipProto_Builder*) builder;
+ (FullUserEquipProto_Builder*) builderWithPrototype:(FullUserEquipProto*) prototype;

+ (FullUserEquipProto*) parseFromData:(NSData*) data;
+ (FullUserEquipProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullUserEquipProto*) parseFromInputStream:(NSInputStream*) input;
+ (FullUserEquipProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullUserEquipProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FullUserEquipProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FullUserEquipProto_Builder : PBGeneratedMessage_Builder {
@private
  FullUserEquipProto* result;
}

- (FullUserEquipProto*) defaultInstance;

- (FullUserEquipProto_Builder*) clear;
- (FullUserEquipProto_Builder*) clone;

- (FullUserEquipProto*) build;
- (FullUserEquipProto*) buildPartial;

- (FullUserEquipProto_Builder*) mergeFrom:(FullUserEquipProto*) other;
- (FullUserEquipProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FullUserEquipProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (FullUserEquipProto_Builder*) setUserId:(int32_t) value;
- (FullUserEquipProto_Builder*) clearUserId;

- (BOOL) hasEquipId;
- (int32_t) equipId;
- (FullUserEquipProto_Builder*) setEquipId:(int32_t) value;
- (FullUserEquipProto_Builder*) clearEquipId;

- (BOOL) hasQuantity;
- (int32_t) quantity;
- (FullUserEquipProto_Builder*) setQuantity:(int32_t) value;
- (FullUserEquipProto_Builder*) clearQuantity;

- (BOOL) hasIsStolen;
- (BOOL) isStolen;
- (FullUserEquipProto_Builder*) setIsStolen:(BOOL) value;
- (FullUserEquipProto_Builder*) clearIsStolen;
@end

@interface FullStructureProto : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasIncome_:1;
  BOOL hasMinutesToGain_:1;
  BOOL hasMinutesToBuild_:1;
  BOOL hasCoinPrice_:1;
  BOOL hasDiamondPrice_:1;
  BOOL hasWoodPrice_:1;
  BOOL hasMinLevel_:1;
  BOOL hasXLength_:1;
  BOOL hasYLength_:1;
  BOOL hasUpgradeCoinCostBase_:1;
  BOOL hasUpgradeDiamondCostBase_:1;
  BOOL hasUpgradeWoodCostBase_:1;
  BOOL hasName_:1;
  int32_t id;
  int32_t income;
  int32_t minutesToGain;
  int32_t minutesToBuild;
  int32_t coinPrice;
  int32_t diamondPrice;
  int32_t woodPrice;
  int32_t minLevel;
  int32_t xLength;
  int32_t yLength;
  int32_t upgradeCoinCostBase;
  int32_t upgradeDiamondCostBase;
  int32_t upgradeWoodCostBase;
  NSString* name;
}
- (BOOL) hasId;
- (BOOL) hasName;
- (BOOL) hasIncome;
- (BOOL) hasMinutesToGain;
- (BOOL) hasMinutesToBuild;
- (BOOL) hasCoinPrice;
- (BOOL) hasDiamondPrice;
- (BOOL) hasWoodPrice;
- (BOOL) hasMinLevel;
- (BOOL) hasXLength;
- (BOOL) hasYLength;
- (BOOL) hasUpgradeCoinCostBase;
- (BOOL) hasUpgradeDiamondCostBase;
- (BOOL) hasUpgradeWoodCostBase;
@property (readonly) int32_t id;
@property (readonly, retain) NSString* name;
@property (readonly) int32_t income;
@property (readonly) int32_t minutesToGain;
@property (readonly) int32_t minutesToBuild;
@property (readonly) int32_t coinPrice;
@property (readonly) int32_t diamondPrice;
@property (readonly) int32_t woodPrice;
@property (readonly) int32_t minLevel;
@property (readonly) int32_t xLength;
@property (readonly) int32_t yLength;
@property (readonly) int32_t upgradeCoinCostBase;
@property (readonly) int32_t upgradeDiamondCostBase;
@property (readonly) int32_t upgradeWoodCostBase;

+ (FullStructureProto*) defaultInstance;
- (FullStructureProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FullStructureProto_Builder*) builder;
+ (FullStructureProto_Builder*) builder;
+ (FullStructureProto_Builder*) builderWithPrototype:(FullStructureProto*) prototype;

+ (FullStructureProto*) parseFromData:(NSData*) data;
+ (FullStructureProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullStructureProto*) parseFromInputStream:(NSInputStream*) input;
+ (FullStructureProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullStructureProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FullStructureProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FullStructureProto_Builder : PBGeneratedMessage_Builder {
@private
  FullStructureProto* result;
}

- (FullStructureProto*) defaultInstance;

- (FullStructureProto_Builder*) clear;
- (FullStructureProto_Builder*) clone;

- (FullStructureProto*) build;
- (FullStructureProto*) buildPartial;

- (FullStructureProto_Builder*) mergeFrom:(FullStructureProto*) other;
- (FullStructureProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FullStructureProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (int32_t) id;
- (FullStructureProto_Builder*) setId:(int32_t) value;
- (FullStructureProto_Builder*) clearId;

- (BOOL) hasName;
- (NSString*) name;
- (FullStructureProto_Builder*) setName:(NSString*) value;
- (FullStructureProto_Builder*) clearName;

- (BOOL) hasIncome;
- (int32_t) income;
- (FullStructureProto_Builder*) setIncome:(int32_t) value;
- (FullStructureProto_Builder*) clearIncome;

- (BOOL) hasMinutesToGain;
- (int32_t) minutesToGain;
- (FullStructureProto_Builder*) setMinutesToGain:(int32_t) value;
- (FullStructureProto_Builder*) clearMinutesToGain;

- (BOOL) hasMinutesToBuild;
- (int32_t) minutesToBuild;
- (FullStructureProto_Builder*) setMinutesToBuild:(int32_t) value;
- (FullStructureProto_Builder*) clearMinutesToBuild;

- (BOOL) hasCoinPrice;
- (int32_t) coinPrice;
- (FullStructureProto_Builder*) setCoinPrice:(int32_t) value;
- (FullStructureProto_Builder*) clearCoinPrice;

- (BOOL) hasDiamondPrice;
- (int32_t) diamondPrice;
- (FullStructureProto_Builder*) setDiamondPrice:(int32_t) value;
- (FullStructureProto_Builder*) clearDiamondPrice;

- (BOOL) hasWoodPrice;
- (int32_t) woodPrice;
- (FullStructureProto_Builder*) setWoodPrice:(int32_t) value;
- (FullStructureProto_Builder*) clearWoodPrice;

- (BOOL) hasMinLevel;
- (int32_t) minLevel;
- (FullStructureProto_Builder*) setMinLevel:(int32_t) value;
- (FullStructureProto_Builder*) clearMinLevel;

- (BOOL) hasXLength;
- (int32_t) xLength;
- (FullStructureProto_Builder*) setXLength:(int32_t) value;
- (FullStructureProto_Builder*) clearXLength;

- (BOOL) hasYLength;
- (int32_t) yLength;
- (FullStructureProto_Builder*) setYLength:(int32_t) value;
- (FullStructureProto_Builder*) clearYLength;

- (BOOL) hasUpgradeCoinCostBase;
- (int32_t) upgradeCoinCostBase;
- (FullStructureProto_Builder*) setUpgradeCoinCostBase:(int32_t) value;
- (FullStructureProto_Builder*) clearUpgradeCoinCostBase;

- (BOOL) hasUpgradeDiamondCostBase;
- (int32_t) upgradeDiamondCostBase;
- (FullStructureProto_Builder*) setUpgradeDiamondCostBase:(int32_t) value;
- (FullStructureProto_Builder*) clearUpgradeDiamondCostBase;

- (BOOL) hasUpgradeWoodCostBase;
- (int32_t) upgradeWoodCostBase;
- (FullStructureProto_Builder*) setUpgradeWoodCostBase:(int32_t) value;
- (FullStructureProto_Builder*) clearUpgradeWoodCostBase;
@end

@interface FullTaskProto : PBGeneratedMessage {
@private
  BOOL hasChanceOfEquipLoot_:1;
  BOOL hasTaskId_:1;
  BOOL hasCityId_:1;
  BOOL hasNumRequiredForCompletion_:1;
  BOOL hasEnergyCost_:1;
  BOOL hasMinCoinsGained_:1;
  BOOL hasMaxCoinsGained_:1;
  BOOL hasExpGained_:1;
  BOOL hasAssetNumWithinCity_:1;
  BOOL hasName_:1;
  Float32 chanceOfEquipLoot;
  int32_t taskId;
  int32_t cityId;
  int32_t numRequiredForCompletion;
  int32_t energyCost;
  int32_t minCoinsGained;
  int32_t maxCoinsGained;
  int32_t expGained;
  int32_t assetNumWithinCity;
  NSString* name;
  NSMutableArray* mutablePotentialLootEquipIdsList;
  NSMutableArray* mutableEquipReqsList;
}
- (BOOL) hasTaskId;
- (BOOL) hasName;
- (BOOL) hasCityId;
- (BOOL) hasNumRequiredForCompletion;
- (BOOL) hasEnergyCost;
- (BOOL) hasMinCoinsGained;
- (BOOL) hasMaxCoinsGained;
- (BOOL) hasChanceOfEquipLoot;
- (BOOL) hasExpGained;
- (BOOL) hasAssetNumWithinCity;
@property (readonly) int32_t taskId;
@property (readonly, retain) NSString* name;
@property (readonly) int32_t cityId;
@property (readonly) int32_t numRequiredForCompletion;
@property (readonly) int32_t energyCost;
@property (readonly) int32_t minCoinsGained;
@property (readonly) int32_t maxCoinsGained;
@property (readonly) Float32 chanceOfEquipLoot;
@property (readonly) int32_t expGained;
@property (readonly) int32_t assetNumWithinCity;
- (NSArray*) potentialLootEquipIdsList;
- (int32_t) potentialLootEquipIdsAtIndex:(int32_t) index;
- (NSArray*) equipReqsList;
- (FullTaskProto_FullTaskEquipReqProto*) equipReqsAtIndex:(int32_t) index;

+ (FullTaskProto*) defaultInstance;
- (FullTaskProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FullTaskProto_Builder*) builder;
+ (FullTaskProto_Builder*) builder;
+ (FullTaskProto_Builder*) builderWithPrototype:(FullTaskProto*) prototype;

+ (FullTaskProto*) parseFromData:(NSData*) data;
+ (FullTaskProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullTaskProto*) parseFromInputStream:(NSInputStream*) input;
+ (FullTaskProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullTaskProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FullTaskProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FullTaskProto_FullTaskEquipReqProto : PBGeneratedMessage {
@private
  BOOL hasTaskId_:1;
  BOOL hasEquipId_:1;
  BOOL hasQuantity_:1;
  int32_t taskId;
  int32_t equipId;
  int32_t quantity;
}
- (BOOL) hasTaskId;
- (BOOL) hasEquipId;
- (BOOL) hasQuantity;
@property (readonly) int32_t taskId;
@property (readonly) int32_t equipId;
@property (readonly) int32_t quantity;

+ (FullTaskProto_FullTaskEquipReqProto*) defaultInstance;
- (FullTaskProto_FullTaskEquipReqProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FullTaskProto_FullTaskEquipReqProto_Builder*) builder;
+ (FullTaskProto_FullTaskEquipReqProto_Builder*) builder;
+ (FullTaskProto_FullTaskEquipReqProto_Builder*) builderWithPrototype:(FullTaskProto_FullTaskEquipReqProto*) prototype;

+ (FullTaskProto_FullTaskEquipReqProto*) parseFromData:(NSData*) data;
+ (FullTaskProto_FullTaskEquipReqProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullTaskProto_FullTaskEquipReqProto*) parseFromInputStream:(NSInputStream*) input;
+ (FullTaskProto_FullTaskEquipReqProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullTaskProto_FullTaskEquipReqProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FullTaskProto_FullTaskEquipReqProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FullTaskProto_FullTaskEquipReqProto_Builder : PBGeneratedMessage_Builder {
@private
  FullTaskProto_FullTaskEquipReqProto* result;
}

- (FullTaskProto_FullTaskEquipReqProto*) defaultInstance;

- (FullTaskProto_FullTaskEquipReqProto_Builder*) clear;
- (FullTaskProto_FullTaskEquipReqProto_Builder*) clone;

- (FullTaskProto_FullTaskEquipReqProto*) build;
- (FullTaskProto_FullTaskEquipReqProto*) buildPartial;

- (FullTaskProto_FullTaskEquipReqProto_Builder*) mergeFrom:(FullTaskProto_FullTaskEquipReqProto*) other;
- (FullTaskProto_FullTaskEquipReqProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FullTaskProto_FullTaskEquipReqProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTaskId;
- (int32_t) taskId;
- (FullTaskProto_FullTaskEquipReqProto_Builder*) setTaskId:(int32_t) value;
- (FullTaskProto_FullTaskEquipReqProto_Builder*) clearTaskId;

- (BOOL) hasEquipId;
- (int32_t) equipId;
- (FullTaskProto_FullTaskEquipReqProto_Builder*) setEquipId:(int32_t) value;
- (FullTaskProto_FullTaskEquipReqProto_Builder*) clearEquipId;

- (BOOL) hasQuantity;
- (int32_t) quantity;
- (FullTaskProto_FullTaskEquipReqProto_Builder*) setQuantity:(int32_t) value;
- (FullTaskProto_FullTaskEquipReqProto_Builder*) clearQuantity;
@end

@interface FullTaskProto_Builder : PBGeneratedMessage_Builder {
@private
  FullTaskProto* result;
}

- (FullTaskProto*) defaultInstance;

- (FullTaskProto_Builder*) clear;
- (FullTaskProto_Builder*) clone;

- (FullTaskProto*) build;
- (FullTaskProto*) buildPartial;

- (FullTaskProto_Builder*) mergeFrom:(FullTaskProto*) other;
- (FullTaskProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FullTaskProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTaskId;
- (int32_t) taskId;
- (FullTaskProto_Builder*) setTaskId:(int32_t) value;
- (FullTaskProto_Builder*) clearTaskId;

- (BOOL) hasName;
- (NSString*) name;
- (FullTaskProto_Builder*) setName:(NSString*) value;
- (FullTaskProto_Builder*) clearName;

- (BOOL) hasCityId;
- (int32_t) cityId;
- (FullTaskProto_Builder*) setCityId:(int32_t) value;
- (FullTaskProto_Builder*) clearCityId;

- (BOOL) hasNumRequiredForCompletion;
- (int32_t) numRequiredForCompletion;
- (FullTaskProto_Builder*) setNumRequiredForCompletion:(int32_t) value;
- (FullTaskProto_Builder*) clearNumRequiredForCompletion;

- (BOOL) hasEnergyCost;
- (int32_t) energyCost;
- (FullTaskProto_Builder*) setEnergyCost:(int32_t) value;
- (FullTaskProto_Builder*) clearEnergyCost;

- (BOOL) hasMinCoinsGained;
- (int32_t) minCoinsGained;
- (FullTaskProto_Builder*) setMinCoinsGained:(int32_t) value;
- (FullTaskProto_Builder*) clearMinCoinsGained;

- (BOOL) hasMaxCoinsGained;
- (int32_t) maxCoinsGained;
- (FullTaskProto_Builder*) setMaxCoinsGained:(int32_t) value;
- (FullTaskProto_Builder*) clearMaxCoinsGained;

- (BOOL) hasChanceOfEquipLoot;
- (Float32) chanceOfEquipLoot;
- (FullTaskProto_Builder*) setChanceOfEquipLoot:(Float32) value;
- (FullTaskProto_Builder*) clearChanceOfEquipLoot;

- (NSArray*) potentialLootEquipIdsList;
- (int32_t) potentialLootEquipIdsAtIndex:(int32_t) index;
- (FullTaskProto_Builder*) replacePotentialLootEquipIdsAtIndex:(int32_t) index with:(int32_t) value;
- (FullTaskProto_Builder*) addPotentialLootEquipIds:(int32_t) value;
- (FullTaskProto_Builder*) addAllPotentialLootEquipIds:(NSArray*) values;
- (FullTaskProto_Builder*) clearPotentialLootEquipIdsList;

- (BOOL) hasExpGained;
- (int32_t) expGained;
- (FullTaskProto_Builder*) setExpGained:(int32_t) value;
- (FullTaskProto_Builder*) clearExpGained;

- (BOOL) hasAssetNumWithinCity;
- (int32_t) assetNumWithinCity;
- (FullTaskProto_Builder*) setAssetNumWithinCity:(int32_t) value;
- (FullTaskProto_Builder*) clearAssetNumWithinCity;

- (NSArray*) equipReqsList;
- (FullTaskProto_FullTaskEquipReqProto*) equipReqsAtIndex:(int32_t) index;
- (FullTaskProto_Builder*) replaceEquipReqsAtIndex:(int32_t) index with:(FullTaskProto_FullTaskEquipReqProto*) value;
- (FullTaskProto_Builder*) addEquipReqs:(FullTaskProto_FullTaskEquipReqProto*) value;
- (FullTaskProto_Builder*) addAllEquipReqs:(NSArray*) values;
- (FullTaskProto_Builder*) clearEquipReqsList;
@end

@interface FullCityProto : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasMinLevel_:1;
  BOOL hasExpGainedBaseOnRankup_:1;
  BOOL hasCoinsGainedBaseOnRankup_:1;
  BOOL hasName_:1;
  int32_t id;
  int32_t minLevel;
  int32_t expGainedBaseOnRankup;
  int32_t coinsGainedBaseOnRankup;
  NSString* name;
}
- (BOOL) hasId;
- (BOOL) hasName;
- (BOOL) hasMinLevel;
- (BOOL) hasExpGainedBaseOnRankup;
- (BOOL) hasCoinsGainedBaseOnRankup;
@property (readonly) int32_t id;
@property (readonly, retain) NSString* name;
@property (readonly) int32_t minLevel;
@property (readonly) int32_t expGainedBaseOnRankup;
@property (readonly) int32_t coinsGainedBaseOnRankup;

+ (FullCityProto*) defaultInstance;
- (FullCityProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FullCityProto_Builder*) builder;
+ (FullCityProto_Builder*) builder;
+ (FullCityProto_Builder*) builderWithPrototype:(FullCityProto*) prototype;

+ (FullCityProto*) parseFromData:(NSData*) data;
+ (FullCityProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullCityProto*) parseFromInputStream:(NSInputStream*) input;
+ (FullCityProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullCityProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FullCityProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FullCityProto_Builder : PBGeneratedMessage_Builder {
@private
  FullCityProto* result;
}

- (FullCityProto*) defaultInstance;

- (FullCityProto_Builder*) clear;
- (FullCityProto_Builder*) clone;

- (FullCityProto*) build;
- (FullCityProto*) buildPartial;

- (FullCityProto_Builder*) mergeFrom:(FullCityProto*) other;
- (FullCityProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FullCityProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (int32_t) id;
- (FullCityProto_Builder*) setId:(int32_t) value;
- (FullCityProto_Builder*) clearId;

- (BOOL) hasName;
- (NSString*) name;
- (FullCityProto_Builder*) setName:(NSString*) value;
- (FullCityProto_Builder*) clearName;

- (BOOL) hasMinLevel;
- (int32_t) minLevel;
- (FullCityProto_Builder*) setMinLevel:(int32_t) value;
- (FullCityProto_Builder*) clearMinLevel;

- (BOOL) hasExpGainedBaseOnRankup;
- (int32_t) expGainedBaseOnRankup;
- (FullCityProto_Builder*) setExpGainedBaseOnRankup:(int32_t) value;
- (FullCityProto_Builder*) clearExpGainedBaseOnRankup;

- (BOOL) hasCoinsGainedBaseOnRankup;
- (int32_t) coinsGainedBaseOnRankup;
- (FullCityProto_Builder*) setCoinsGainedBaseOnRankup:(int32_t) value;
- (FullCityProto_Builder*) clearCoinsGainedBaseOnRankup;
@end

@interface CoordinateProto : PBGeneratedMessage {
@private
  BOOL hasX_:1;
  BOOL hasY_:1;
  int32_t x;
  int32_t y;
}
- (BOOL) hasX;
- (BOOL) hasY;
@property (readonly) int32_t x;
@property (readonly) int32_t y;

+ (CoordinateProto*) defaultInstance;
- (CoordinateProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CoordinateProto_Builder*) builder;
+ (CoordinateProto_Builder*) builder;
+ (CoordinateProto_Builder*) builderWithPrototype:(CoordinateProto*) prototype;

+ (CoordinateProto*) parseFromData:(NSData*) data;
+ (CoordinateProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CoordinateProto*) parseFromInputStream:(NSInputStream*) input;
+ (CoordinateProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CoordinateProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CoordinateProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CoordinateProto_Builder : PBGeneratedMessage_Builder {
@private
  CoordinateProto* result;
}

- (CoordinateProto*) defaultInstance;

- (CoordinateProto_Builder*) clear;
- (CoordinateProto_Builder*) clone;

- (CoordinateProto*) build;
- (CoordinateProto*) buildPartial;

- (CoordinateProto_Builder*) mergeFrom:(CoordinateProto*) other;
- (CoordinateProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CoordinateProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasX;
- (int32_t) x;
- (CoordinateProto_Builder*) setX:(int32_t) value;
- (CoordinateProto_Builder*) clearX;

- (BOOL) hasY;
- (int32_t) y;
- (CoordinateProto_Builder*) setY:(int32_t) value;
- (CoordinateProto_Builder*) clearY;
@end

@interface LocationProto : PBGeneratedMessage {
@private
  BOOL hasLatitude_:1;
  BOOL hasLongitude_:1;
  Float32 latitude;
  Float32 longitude;
}
- (BOOL) hasLatitude;
- (BOOL) hasLongitude;
@property (readonly) Float32 latitude;
@property (readonly) Float32 longitude;

+ (LocationProto*) defaultInstance;
- (LocationProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LocationProto_Builder*) builder;
+ (LocationProto_Builder*) builder;
+ (LocationProto_Builder*) builderWithPrototype:(LocationProto*) prototype;

+ (LocationProto*) parseFromData:(NSData*) data;
+ (LocationProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LocationProto*) parseFromInputStream:(NSInputStream*) input;
+ (LocationProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LocationProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LocationProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LocationProto_Builder : PBGeneratedMessage_Builder {
@private
  LocationProto* result;
}

- (LocationProto*) defaultInstance;

- (LocationProto_Builder*) clear;
- (LocationProto_Builder*) clone;

- (LocationProto*) build;
- (LocationProto*) buildPartial;

- (LocationProto_Builder*) mergeFrom:(LocationProto*) other;
- (LocationProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LocationProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLatitude;
- (Float32) latitude;
- (LocationProto_Builder*) setLatitude:(Float32) value;
- (LocationProto_Builder*) clearLatitude;

- (BOOL) hasLongitude;
- (Float32) longitude;
- (LocationProto_Builder*) setLongitude:(Float32) value;
- (LocationProto_Builder*) clearLongitude;
@end

@interface FullMarketplacePostProto : PBGeneratedMessage {
@private
  BOOL hasTimeOfPost_:1;
  BOOL hasMarketplacePostId_:1;
  BOOL hasPosterId_:1;
  BOOL hasPostedWood_:1;
  BOOL hasPostedDiamonds_:1;
  BOOL hasPostedCoins_:1;
  BOOL hasDiamondCost_:1;
  BOOL hasCoinCost_:1;
  BOOL hasWoodCost_:1;
  BOOL hasPostedEquip_:1;
  BOOL hasPostType_:1;
  int64_t timeOfPost;
  int32_t marketplacePostId;
  int32_t posterId;
  int32_t postedWood;
  int32_t postedDiamonds;
  int32_t postedCoins;
  int32_t diamondCost;
  int32_t coinCost;
  int32_t woodCost;
  FullEquipProto* postedEquip;
  MarketplacePostType postType;
}
- (BOOL) hasMarketplacePostId;
- (BOOL) hasPosterId;
- (BOOL) hasPostType;
- (BOOL) hasTimeOfPost;
- (BOOL) hasPostedEquip;
- (BOOL) hasPostedWood;
- (BOOL) hasPostedDiamonds;
- (BOOL) hasPostedCoins;
- (BOOL) hasDiamondCost;
- (BOOL) hasCoinCost;
- (BOOL) hasWoodCost;
@property (readonly) int32_t marketplacePostId;
@property (readonly) int32_t posterId;
@property (readonly) MarketplacePostType postType;
@property (readonly) int64_t timeOfPost;
@property (readonly, retain) FullEquipProto* postedEquip;
@property (readonly) int32_t postedWood;
@property (readonly) int32_t postedDiamonds;
@property (readonly) int32_t postedCoins;
@property (readonly) int32_t diamondCost;
@property (readonly) int32_t coinCost;
@property (readonly) int32_t woodCost;

+ (FullMarketplacePostProto*) defaultInstance;
- (FullMarketplacePostProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FullMarketplacePostProto_Builder*) builder;
+ (FullMarketplacePostProto_Builder*) builder;
+ (FullMarketplacePostProto_Builder*) builderWithPrototype:(FullMarketplacePostProto*) prototype;

+ (FullMarketplacePostProto*) parseFromData:(NSData*) data;
+ (FullMarketplacePostProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullMarketplacePostProto*) parseFromInputStream:(NSInputStream*) input;
+ (FullMarketplacePostProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullMarketplacePostProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FullMarketplacePostProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FullMarketplacePostProto_Builder : PBGeneratedMessage_Builder {
@private
  FullMarketplacePostProto* result;
}

- (FullMarketplacePostProto*) defaultInstance;

- (FullMarketplacePostProto_Builder*) clear;
- (FullMarketplacePostProto_Builder*) clone;

- (FullMarketplacePostProto*) build;
- (FullMarketplacePostProto*) buildPartial;

- (FullMarketplacePostProto_Builder*) mergeFrom:(FullMarketplacePostProto*) other;
- (FullMarketplacePostProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FullMarketplacePostProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMarketplacePostId;
- (int32_t) marketplacePostId;
- (FullMarketplacePostProto_Builder*) setMarketplacePostId:(int32_t) value;
- (FullMarketplacePostProto_Builder*) clearMarketplacePostId;

- (BOOL) hasPosterId;
- (int32_t) posterId;
- (FullMarketplacePostProto_Builder*) setPosterId:(int32_t) value;
- (FullMarketplacePostProto_Builder*) clearPosterId;

- (BOOL) hasPostType;
- (MarketplacePostType) postType;
- (FullMarketplacePostProto_Builder*) setPostType:(MarketplacePostType) value;
- (FullMarketplacePostProto_Builder*) clearPostType;

- (BOOL) hasTimeOfPost;
- (int64_t) timeOfPost;
- (FullMarketplacePostProto_Builder*) setTimeOfPost:(int64_t) value;
- (FullMarketplacePostProto_Builder*) clearTimeOfPost;

- (BOOL) hasPostedEquip;
- (FullEquipProto*) postedEquip;
- (FullMarketplacePostProto_Builder*) setPostedEquip:(FullEquipProto*) value;
- (FullMarketplacePostProto_Builder*) setPostedEquipBuilder:(FullEquipProto_Builder*) builderForValue;
- (FullMarketplacePostProto_Builder*) mergePostedEquip:(FullEquipProto*) value;
- (FullMarketplacePostProto_Builder*) clearPostedEquip;

- (BOOL) hasPostedWood;
- (int32_t) postedWood;
- (FullMarketplacePostProto_Builder*) setPostedWood:(int32_t) value;
- (FullMarketplacePostProto_Builder*) clearPostedWood;

- (BOOL) hasPostedDiamonds;
- (int32_t) postedDiamonds;
- (FullMarketplacePostProto_Builder*) setPostedDiamonds:(int32_t) value;
- (FullMarketplacePostProto_Builder*) clearPostedDiamonds;

- (BOOL) hasPostedCoins;
- (int32_t) postedCoins;
- (FullMarketplacePostProto_Builder*) setPostedCoins:(int32_t) value;
- (FullMarketplacePostProto_Builder*) clearPostedCoins;

- (BOOL) hasDiamondCost;
- (int32_t) diamondCost;
- (FullMarketplacePostProto_Builder*) setDiamondCost:(int32_t) value;
- (FullMarketplacePostProto_Builder*) clearDiamondCost;

- (BOOL) hasCoinCost;
- (int32_t) coinCost;
- (FullMarketplacePostProto_Builder*) setCoinCost:(int32_t) value;
- (FullMarketplacePostProto_Builder*) clearCoinCost;

- (BOOL) hasWoodCost;
- (int32_t) woodCost;
- (FullMarketplacePostProto_Builder*) setWoodCost:(int32_t) value;
- (FullMarketplacePostProto_Builder*) clearWoodCost;
@end

@interface MinimumUserTaskProto : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasNumTimesActed_:1;
  BOOL hasTask_:1;
  int32_t userId;
  int32_t numTimesActed;
  FullTaskProto* task;
}
- (BOOL) hasUserId;
- (BOOL) hasTask;
- (BOOL) hasNumTimesActed;
@property (readonly) int32_t userId;
@property (readonly, retain) FullTaskProto* task;
@property (readonly) int32_t numTimesActed;

+ (MinimumUserTaskProto*) defaultInstance;
- (MinimumUserTaskProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MinimumUserTaskProto_Builder*) builder;
+ (MinimumUserTaskProto_Builder*) builder;
+ (MinimumUserTaskProto_Builder*) builderWithPrototype:(MinimumUserTaskProto*) prototype;

+ (MinimumUserTaskProto*) parseFromData:(NSData*) data;
+ (MinimumUserTaskProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MinimumUserTaskProto*) parseFromInputStream:(NSInputStream*) input;
+ (MinimumUserTaskProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MinimumUserTaskProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MinimumUserTaskProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MinimumUserTaskProto_Builder : PBGeneratedMessage_Builder {
@private
  MinimumUserTaskProto* result;
}

- (MinimumUserTaskProto*) defaultInstance;

- (MinimumUserTaskProto_Builder*) clear;
- (MinimumUserTaskProto_Builder*) clone;

- (MinimumUserTaskProto*) build;
- (MinimumUserTaskProto*) buildPartial;

- (MinimumUserTaskProto_Builder*) mergeFrom:(MinimumUserTaskProto*) other;
- (MinimumUserTaskProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MinimumUserTaskProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (MinimumUserTaskProto_Builder*) setUserId:(int32_t) value;
- (MinimumUserTaskProto_Builder*) clearUserId;

- (BOOL) hasTask;
- (FullTaskProto*) task;
- (MinimumUserTaskProto_Builder*) setTask:(FullTaskProto*) value;
- (MinimumUserTaskProto_Builder*) setTaskBuilder:(FullTaskProto_Builder*) builderForValue;
- (MinimumUserTaskProto_Builder*) mergeTask:(FullTaskProto*) value;
- (MinimumUserTaskProto_Builder*) clearTask;

- (BOOL) hasNumTimesActed;
- (int32_t) numTimesActed;
- (MinimumUserTaskProto_Builder*) setNumTimesActed:(int32_t) value;
- (MinimumUserTaskProto_Builder*) clearNumTimesActed;
@end

@interface FullUserQuestDataLarge : PBGeneratedMessage {
@private
  BOOL hasComplete_:1;
  BOOL hasUserId_:1;
  BOOL hasQuestId_:1;
  BOOL complete_:1;
  int32_t userId;
  int32_t questId;
  NSMutableArray* mutableRequiredTasksProgressList;
  NSMutableArray* mutableRequiredDefeatTypeJobProgressList;
  NSMutableArray* mutableRequiredBuildStructJobProgressList;
  NSMutableArray* mutableRequiredUpgradeStructJobProgressList;
  NSMutableArray* mutableRequiredPossessEquipJobProgressList;
}
- (BOOL) hasUserId;
- (BOOL) hasQuestId;
- (BOOL) hasComplete;
@property (readonly) int32_t userId;
@property (readonly) int32_t questId;
- (BOOL) complete;
- (NSArray*) requiredTasksProgressList;
- (MinimumUserTaskProto*) requiredTasksProgressAtIndex:(int32_t) index;
- (NSArray*) requiredDefeatTypeJobProgressList;
- (MinimumUserDefeatTypeJobProto*) requiredDefeatTypeJobProgressAtIndex:(int32_t) index;
- (NSArray*) requiredBuildStructJobProgressList;
- (MinimumUserBuildStructJobProto*) requiredBuildStructJobProgressAtIndex:(int32_t) index;
- (NSArray*) requiredUpgradeStructJobProgressList;
- (MinimumUserUpgradeStructJobProto*) requiredUpgradeStructJobProgressAtIndex:(int32_t) index;
- (NSArray*) requiredPossessEquipJobProgressList;
- (MinimumUserPossessEquipJobProto*) requiredPossessEquipJobProgressAtIndex:(int32_t) index;

+ (FullUserQuestDataLarge*) defaultInstance;
- (FullUserQuestDataLarge*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FullUserQuestDataLarge_Builder*) builder;
+ (FullUserQuestDataLarge_Builder*) builder;
+ (FullUserQuestDataLarge_Builder*) builderWithPrototype:(FullUserQuestDataLarge*) prototype;

+ (FullUserQuestDataLarge*) parseFromData:(NSData*) data;
+ (FullUserQuestDataLarge*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullUserQuestDataLarge*) parseFromInputStream:(NSInputStream*) input;
+ (FullUserQuestDataLarge*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullUserQuestDataLarge*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FullUserQuestDataLarge*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FullUserQuestDataLarge_Builder : PBGeneratedMessage_Builder {
@private
  FullUserQuestDataLarge* result;
}

- (FullUserQuestDataLarge*) defaultInstance;

- (FullUserQuestDataLarge_Builder*) clear;
- (FullUserQuestDataLarge_Builder*) clone;

- (FullUserQuestDataLarge*) build;
- (FullUserQuestDataLarge*) buildPartial;

- (FullUserQuestDataLarge_Builder*) mergeFrom:(FullUserQuestDataLarge*) other;
- (FullUserQuestDataLarge_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FullUserQuestDataLarge_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (FullUserQuestDataLarge_Builder*) setUserId:(int32_t) value;
- (FullUserQuestDataLarge_Builder*) clearUserId;

- (BOOL) hasQuestId;
- (int32_t) questId;
- (FullUserQuestDataLarge_Builder*) setQuestId:(int32_t) value;
- (FullUserQuestDataLarge_Builder*) clearQuestId;

- (BOOL) hasComplete;
- (BOOL) complete;
- (FullUserQuestDataLarge_Builder*) setComplete:(BOOL) value;
- (FullUserQuestDataLarge_Builder*) clearComplete;

- (NSArray*) requiredTasksProgressList;
- (MinimumUserTaskProto*) requiredTasksProgressAtIndex:(int32_t) index;
- (FullUserQuestDataLarge_Builder*) replaceRequiredTasksProgressAtIndex:(int32_t) index with:(MinimumUserTaskProto*) value;
- (FullUserQuestDataLarge_Builder*) addRequiredTasksProgress:(MinimumUserTaskProto*) value;
- (FullUserQuestDataLarge_Builder*) addAllRequiredTasksProgress:(NSArray*) values;
- (FullUserQuestDataLarge_Builder*) clearRequiredTasksProgressList;

- (NSArray*) requiredDefeatTypeJobProgressList;
- (MinimumUserDefeatTypeJobProto*) requiredDefeatTypeJobProgressAtIndex:(int32_t) index;
- (FullUserQuestDataLarge_Builder*) replaceRequiredDefeatTypeJobProgressAtIndex:(int32_t) index with:(MinimumUserDefeatTypeJobProto*) value;
- (FullUserQuestDataLarge_Builder*) addRequiredDefeatTypeJobProgress:(MinimumUserDefeatTypeJobProto*) value;
- (FullUserQuestDataLarge_Builder*) addAllRequiredDefeatTypeJobProgress:(NSArray*) values;
- (FullUserQuestDataLarge_Builder*) clearRequiredDefeatTypeJobProgressList;

- (NSArray*) requiredBuildStructJobProgressList;
- (MinimumUserBuildStructJobProto*) requiredBuildStructJobProgressAtIndex:(int32_t) index;
- (FullUserQuestDataLarge_Builder*) replaceRequiredBuildStructJobProgressAtIndex:(int32_t) index with:(MinimumUserBuildStructJobProto*) value;
- (FullUserQuestDataLarge_Builder*) addRequiredBuildStructJobProgress:(MinimumUserBuildStructJobProto*) value;
- (FullUserQuestDataLarge_Builder*) addAllRequiredBuildStructJobProgress:(NSArray*) values;
- (FullUserQuestDataLarge_Builder*) clearRequiredBuildStructJobProgressList;

- (NSArray*) requiredUpgradeStructJobProgressList;
- (MinimumUserUpgradeStructJobProto*) requiredUpgradeStructJobProgressAtIndex:(int32_t) index;
- (FullUserQuestDataLarge_Builder*) replaceRequiredUpgradeStructJobProgressAtIndex:(int32_t) index with:(MinimumUserUpgradeStructJobProto*) value;
- (FullUserQuestDataLarge_Builder*) addRequiredUpgradeStructJobProgress:(MinimumUserUpgradeStructJobProto*) value;
- (FullUserQuestDataLarge_Builder*) addAllRequiredUpgradeStructJobProgress:(NSArray*) values;
- (FullUserQuestDataLarge_Builder*) clearRequiredUpgradeStructJobProgressList;

- (NSArray*) requiredPossessEquipJobProgressList;
- (MinimumUserPossessEquipJobProto*) requiredPossessEquipJobProgressAtIndex:(int32_t) index;
- (FullUserQuestDataLarge_Builder*) replaceRequiredPossessEquipJobProgressAtIndex:(int32_t) index with:(MinimumUserPossessEquipJobProto*) value;
- (FullUserQuestDataLarge_Builder*) addRequiredPossessEquipJobProgress:(MinimumUserPossessEquipJobProto*) value;
- (FullUserQuestDataLarge_Builder*) addAllRequiredPossessEquipJobProgress:(NSArray*) values;
- (FullUserQuestDataLarge_Builder*) clearRequiredPossessEquipJobProgressList;
@end

@interface MinimumUserDefeatTypeJobProto : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasQuestId_:1;
  BOOL hasNumDefeated_:1;
  BOOL hasDefeatTypeJobId_:1;
  int32_t userId;
  int32_t questId;
  int32_t numDefeated;
  DefeatTypeJobProto* defeatTypeJobId;
}
- (BOOL) hasUserId;
- (BOOL) hasQuestId;
- (BOOL) hasDefeatTypeJobId;
- (BOOL) hasNumDefeated;
@property (readonly) int32_t userId;
@property (readonly) int32_t questId;
@property (readonly, retain) DefeatTypeJobProto* defeatTypeJobId;
@property (readonly) int32_t numDefeated;

+ (MinimumUserDefeatTypeJobProto*) defaultInstance;
- (MinimumUserDefeatTypeJobProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MinimumUserDefeatTypeJobProto_Builder*) builder;
+ (MinimumUserDefeatTypeJobProto_Builder*) builder;
+ (MinimumUserDefeatTypeJobProto_Builder*) builderWithPrototype:(MinimumUserDefeatTypeJobProto*) prototype;

+ (MinimumUserDefeatTypeJobProto*) parseFromData:(NSData*) data;
+ (MinimumUserDefeatTypeJobProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MinimumUserDefeatTypeJobProto*) parseFromInputStream:(NSInputStream*) input;
+ (MinimumUserDefeatTypeJobProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MinimumUserDefeatTypeJobProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MinimumUserDefeatTypeJobProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MinimumUserDefeatTypeJobProto_Builder : PBGeneratedMessage_Builder {
@private
  MinimumUserDefeatTypeJobProto* result;
}

- (MinimumUserDefeatTypeJobProto*) defaultInstance;

- (MinimumUserDefeatTypeJobProto_Builder*) clear;
- (MinimumUserDefeatTypeJobProto_Builder*) clone;

- (MinimumUserDefeatTypeJobProto*) build;
- (MinimumUserDefeatTypeJobProto*) buildPartial;

- (MinimumUserDefeatTypeJobProto_Builder*) mergeFrom:(MinimumUserDefeatTypeJobProto*) other;
- (MinimumUserDefeatTypeJobProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MinimumUserDefeatTypeJobProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (MinimumUserDefeatTypeJobProto_Builder*) setUserId:(int32_t) value;
- (MinimumUserDefeatTypeJobProto_Builder*) clearUserId;

- (BOOL) hasQuestId;
- (int32_t) questId;
- (MinimumUserDefeatTypeJobProto_Builder*) setQuestId:(int32_t) value;
- (MinimumUserDefeatTypeJobProto_Builder*) clearQuestId;

- (BOOL) hasDefeatTypeJobId;
- (DefeatTypeJobProto*) defeatTypeJobId;
- (MinimumUserDefeatTypeJobProto_Builder*) setDefeatTypeJobId:(DefeatTypeJobProto*) value;
- (MinimumUserDefeatTypeJobProto_Builder*) setDefeatTypeJobIdBuilder:(DefeatTypeJobProto_Builder*) builderForValue;
- (MinimumUserDefeatTypeJobProto_Builder*) mergeDefeatTypeJobId:(DefeatTypeJobProto*) value;
- (MinimumUserDefeatTypeJobProto_Builder*) clearDefeatTypeJobId;

- (BOOL) hasNumDefeated;
- (int32_t) numDefeated;
- (MinimumUserDefeatTypeJobProto_Builder*) setNumDefeated:(int32_t) value;
- (MinimumUserDefeatTypeJobProto_Builder*) clearNumDefeated;
@end

@interface DefeatTypeJobProto : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasNumEnemiesToDefeat_:1;
  BOOL hasCityId_:1;
  BOOL hasTypeOfEnemy_:1;
  int32_t id;
  int32_t numEnemiesToDefeat;
  int32_t cityId;
  UserType typeOfEnemy;
}
- (BOOL) hasId;
- (BOOL) hasTypeOfEnemy;
- (BOOL) hasNumEnemiesToDefeat;
- (BOOL) hasCityId;
@property (readonly) int32_t id;
@property (readonly) UserType typeOfEnemy;
@property (readonly) int32_t numEnemiesToDefeat;
@property (readonly) int32_t cityId;

+ (DefeatTypeJobProto*) defaultInstance;
- (DefeatTypeJobProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DefeatTypeJobProto_Builder*) builder;
+ (DefeatTypeJobProto_Builder*) builder;
+ (DefeatTypeJobProto_Builder*) builderWithPrototype:(DefeatTypeJobProto*) prototype;

+ (DefeatTypeJobProto*) parseFromData:(NSData*) data;
+ (DefeatTypeJobProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DefeatTypeJobProto*) parseFromInputStream:(NSInputStream*) input;
+ (DefeatTypeJobProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DefeatTypeJobProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (DefeatTypeJobProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface DefeatTypeJobProto_Builder : PBGeneratedMessage_Builder {
@private
  DefeatTypeJobProto* result;
}

- (DefeatTypeJobProto*) defaultInstance;

- (DefeatTypeJobProto_Builder*) clear;
- (DefeatTypeJobProto_Builder*) clone;

- (DefeatTypeJobProto*) build;
- (DefeatTypeJobProto*) buildPartial;

- (DefeatTypeJobProto_Builder*) mergeFrom:(DefeatTypeJobProto*) other;
- (DefeatTypeJobProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DefeatTypeJobProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (int32_t) id;
- (DefeatTypeJobProto_Builder*) setId:(int32_t) value;
- (DefeatTypeJobProto_Builder*) clearId;

- (BOOL) hasTypeOfEnemy;
- (UserType) typeOfEnemy;
- (DefeatTypeJobProto_Builder*) setTypeOfEnemy:(UserType) value;
- (DefeatTypeJobProto_Builder*) clearTypeOfEnemy;

- (BOOL) hasNumEnemiesToDefeat;
- (int32_t) numEnemiesToDefeat;
- (DefeatTypeJobProto_Builder*) setNumEnemiesToDefeat:(int32_t) value;
- (DefeatTypeJobProto_Builder*) clearNumEnemiesToDefeat;

- (BOOL) hasCityId;
- (int32_t) cityId;
- (DefeatTypeJobProto_Builder*) setCityId:(int32_t) value;
- (DefeatTypeJobProto_Builder*) clearCityId;
@end

@interface MinimumUserBuildStructJobProto : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasQuestId_:1;
  BOOL hasNumOfStructUserHas_:1;
  BOOL hasBuildStructJob_:1;
  int32_t userId;
  int32_t questId;
  int32_t numOfStructUserHas;
  BuildStructJobProto* buildStructJob;
}
- (BOOL) hasUserId;
- (BOOL) hasQuestId;
- (BOOL) hasBuildStructJob;
- (BOOL) hasNumOfStructUserHas;
@property (readonly) int32_t userId;
@property (readonly) int32_t questId;
@property (readonly, retain) BuildStructJobProto* buildStructJob;
@property (readonly) int32_t numOfStructUserHas;

+ (MinimumUserBuildStructJobProto*) defaultInstance;
- (MinimumUserBuildStructJobProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MinimumUserBuildStructJobProto_Builder*) builder;
+ (MinimumUserBuildStructJobProto_Builder*) builder;
+ (MinimumUserBuildStructJobProto_Builder*) builderWithPrototype:(MinimumUserBuildStructJobProto*) prototype;

+ (MinimumUserBuildStructJobProto*) parseFromData:(NSData*) data;
+ (MinimumUserBuildStructJobProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MinimumUserBuildStructJobProto*) parseFromInputStream:(NSInputStream*) input;
+ (MinimumUserBuildStructJobProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MinimumUserBuildStructJobProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MinimumUserBuildStructJobProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MinimumUserBuildStructJobProto_Builder : PBGeneratedMessage_Builder {
@private
  MinimumUserBuildStructJobProto* result;
}

- (MinimumUserBuildStructJobProto*) defaultInstance;

- (MinimumUserBuildStructJobProto_Builder*) clear;
- (MinimumUserBuildStructJobProto_Builder*) clone;

- (MinimumUserBuildStructJobProto*) build;
- (MinimumUserBuildStructJobProto*) buildPartial;

- (MinimumUserBuildStructJobProto_Builder*) mergeFrom:(MinimumUserBuildStructJobProto*) other;
- (MinimumUserBuildStructJobProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MinimumUserBuildStructJobProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (MinimumUserBuildStructJobProto_Builder*) setUserId:(int32_t) value;
- (MinimumUserBuildStructJobProto_Builder*) clearUserId;

- (BOOL) hasQuestId;
- (int32_t) questId;
- (MinimumUserBuildStructJobProto_Builder*) setQuestId:(int32_t) value;
- (MinimumUserBuildStructJobProto_Builder*) clearQuestId;

- (BOOL) hasBuildStructJob;
- (BuildStructJobProto*) buildStructJob;
- (MinimumUserBuildStructJobProto_Builder*) setBuildStructJob:(BuildStructJobProto*) value;
- (MinimumUserBuildStructJobProto_Builder*) setBuildStructJobBuilder:(BuildStructJobProto_Builder*) builderForValue;
- (MinimumUserBuildStructJobProto_Builder*) mergeBuildStructJob:(BuildStructJobProto*) value;
- (MinimumUserBuildStructJobProto_Builder*) clearBuildStructJob;

- (BOOL) hasNumOfStructUserHas;
- (int32_t) numOfStructUserHas;
- (MinimumUserBuildStructJobProto_Builder*) setNumOfStructUserHas:(int32_t) value;
- (MinimumUserBuildStructJobProto_Builder*) clearNumOfStructUserHas;
@end

@interface BuildStructJobProto : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasStructId_:1;
  BOOL hasQuantityRequired_:1;
  int32_t id;
  int32_t structId;
  int32_t quantityRequired;
}
- (BOOL) hasId;
- (BOOL) hasStructId;
- (BOOL) hasQuantityRequired;
@property (readonly) int32_t id;
@property (readonly) int32_t structId;
@property (readonly) int32_t quantityRequired;

+ (BuildStructJobProto*) defaultInstance;
- (BuildStructJobProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BuildStructJobProto_Builder*) builder;
+ (BuildStructJobProto_Builder*) builder;
+ (BuildStructJobProto_Builder*) builderWithPrototype:(BuildStructJobProto*) prototype;

+ (BuildStructJobProto*) parseFromData:(NSData*) data;
+ (BuildStructJobProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BuildStructJobProto*) parseFromInputStream:(NSInputStream*) input;
+ (BuildStructJobProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BuildStructJobProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BuildStructJobProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BuildStructJobProto_Builder : PBGeneratedMessage_Builder {
@private
  BuildStructJobProto* result;
}

- (BuildStructJobProto*) defaultInstance;

- (BuildStructJobProto_Builder*) clear;
- (BuildStructJobProto_Builder*) clone;

- (BuildStructJobProto*) build;
- (BuildStructJobProto*) buildPartial;

- (BuildStructJobProto_Builder*) mergeFrom:(BuildStructJobProto*) other;
- (BuildStructJobProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BuildStructJobProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (int32_t) id;
- (BuildStructJobProto_Builder*) setId:(int32_t) value;
- (BuildStructJobProto_Builder*) clearId;

- (BOOL) hasStructId;
- (int32_t) structId;
- (BuildStructJobProto_Builder*) setStructId:(int32_t) value;
- (BuildStructJobProto_Builder*) clearStructId;

- (BOOL) hasQuantityRequired;
- (int32_t) quantityRequired;
- (BuildStructJobProto_Builder*) setQuantityRequired:(int32_t) value;
- (BuildStructJobProto_Builder*) clearQuantityRequired;
@end

@interface MinimumUserUpgradeStructJobProto : PBGeneratedMessage {
@private
  BOOL hasIsComplete_:1;
  BOOL hasUserId_:1;
  BOOL hasQuestId_:1;
  BOOL hasUpgradeStructJob_:1;
  BOOL isComplete_:1;
  int32_t userId;
  int32_t questId;
  UpgradeStructJobProto* upgradeStructJob;
}
- (BOOL) hasUserId;
- (BOOL) hasQuestId;
- (BOOL) hasUpgradeStructJob;
- (BOOL) hasIsComplete;
@property (readonly) int32_t userId;
@property (readonly) int32_t questId;
@property (readonly, retain) UpgradeStructJobProto* upgradeStructJob;
- (BOOL) isComplete;

+ (MinimumUserUpgradeStructJobProto*) defaultInstance;
- (MinimumUserUpgradeStructJobProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MinimumUserUpgradeStructJobProto_Builder*) builder;
+ (MinimumUserUpgradeStructJobProto_Builder*) builder;
+ (MinimumUserUpgradeStructJobProto_Builder*) builderWithPrototype:(MinimumUserUpgradeStructJobProto*) prototype;

+ (MinimumUserUpgradeStructJobProto*) parseFromData:(NSData*) data;
+ (MinimumUserUpgradeStructJobProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MinimumUserUpgradeStructJobProto*) parseFromInputStream:(NSInputStream*) input;
+ (MinimumUserUpgradeStructJobProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MinimumUserUpgradeStructJobProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MinimumUserUpgradeStructJobProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MinimumUserUpgradeStructJobProto_Builder : PBGeneratedMessage_Builder {
@private
  MinimumUserUpgradeStructJobProto* result;
}

- (MinimumUserUpgradeStructJobProto*) defaultInstance;

- (MinimumUserUpgradeStructJobProto_Builder*) clear;
- (MinimumUserUpgradeStructJobProto_Builder*) clone;

- (MinimumUserUpgradeStructJobProto*) build;
- (MinimumUserUpgradeStructJobProto*) buildPartial;

- (MinimumUserUpgradeStructJobProto_Builder*) mergeFrom:(MinimumUserUpgradeStructJobProto*) other;
- (MinimumUserUpgradeStructJobProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MinimumUserUpgradeStructJobProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (MinimumUserUpgradeStructJobProto_Builder*) setUserId:(int32_t) value;
- (MinimumUserUpgradeStructJobProto_Builder*) clearUserId;

- (BOOL) hasQuestId;
- (int32_t) questId;
- (MinimumUserUpgradeStructJobProto_Builder*) setQuestId:(int32_t) value;
- (MinimumUserUpgradeStructJobProto_Builder*) clearQuestId;

- (BOOL) hasUpgradeStructJob;
- (UpgradeStructJobProto*) upgradeStructJob;
- (MinimumUserUpgradeStructJobProto_Builder*) setUpgradeStructJob:(UpgradeStructJobProto*) value;
- (MinimumUserUpgradeStructJobProto_Builder*) setUpgradeStructJobBuilder:(UpgradeStructJobProto_Builder*) builderForValue;
- (MinimumUserUpgradeStructJobProto_Builder*) mergeUpgradeStructJob:(UpgradeStructJobProto*) value;
- (MinimumUserUpgradeStructJobProto_Builder*) clearUpgradeStructJob;

- (BOOL) hasIsComplete;
- (BOOL) isComplete;
- (MinimumUserUpgradeStructJobProto_Builder*) setIsComplete:(BOOL) value;
- (MinimumUserUpgradeStructJobProto_Builder*) clearIsComplete;
@end

@interface UpgradeStructJobProto : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasStructId_:1;
  BOOL hasLevelReq_:1;
  int32_t id;
  int32_t structId;
  int32_t levelReq;
}
- (BOOL) hasId;
- (BOOL) hasStructId;
- (BOOL) hasLevelReq;
@property (readonly) int32_t id;
@property (readonly) int32_t structId;
@property (readonly) int32_t levelReq;

+ (UpgradeStructJobProto*) defaultInstance;
- (UpgradeStructJobProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UpgradeStructJobProto_Builder*) builder;
+ (UpgradeStructJobProto_Builder*) builder;
+ (UpgradeStructJobProto_Builder*) builderWithPrototype:(UpgradeStructJobProto*) prototype;

+ (UpgradeStructJobProto*) parseFromData:(NSData*) data;
+ (UpgradeStructJobProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UpgradeStructJobProto*) parseFromInputStream:(NSInputStream*) input;
+ (UpgradeStructJobProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UpgradeStructJobProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UpgradeStructJobProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UpgradeStructJobProto_Builder : PBGeneratedMessage_Builder {
@private
  UpgradeStructJobProto* result;
}

- (UpgradeStructJobProto*) defaultInstance;

- (UpgradeStructJobProto_Builder*) clear;
- (UpgradeStructJobProto_Builder*) clone;

- (UpgradeStructJobProto*) build;
- (UpgradeStructJobProto*) buildPartial;

- (UpgradeStructJobProto_Builder*) mergeFrom:(UpgradeStructJobProto*) other;
- (UpgradeStructJobProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UpgradeStructJobProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (int32_t) id;
- (UpgradeStructJobProto_Builder*) setId:(int32_t) value;
- (UpgradeStructJobProto_Builder*) clearId;

- (BOOL) hasStructId;
- (int32_t) structId;
- (UpgradeStructJobProto_Builder*) setStructId:(int32_t) value;
- (UpgradeStructJobProto_Builder*) clearStructId;

- (BOOL) hasLevelReq;
- (int32_t) levelReq;
- (UpgradeStructJobProto_Builder*) setLevelReq:(int32_t) value;
- (UpgradeStructJobProto_Builder*) clearLevelReq;
@end

@interface MinimumUserPossessEquipJobProto : PBGeneratedMessage {
@private
  BOOL hasIsComplete_:1;
  BOOL hasUserId_:1;
  BOOL hasQuestId_:1;
  BOOL hasPossessEquipJobProto_:1;
  BOOL isComplete_:1;
  int32_t userId;
  int32_t questId;
  PossessEquipJobProto* possessEquipJobProto;
}
- (BOOL) hasUserId;
- (BOOL) hasQuestId;
- (BOOL) hasPossessEquipJobProto;
- (BOOL) hasIsComplete;
@property (readonly) int32_t userId;
@property (readonly) int32_t questId;
@property (readonly, retain) PossessEquipJobProto* possessEquipJobProto;
- (BOOL) isComplete;

+ (MinimumUserPossessEquipJobProto*) defaultInstance;
- (MinimumUserPossessEquipJobProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MinimumUserPossessEquipJobProto_Builder*) builder;
+ (MinimumUserPossessEquipJobProto_Builder*) builder;
+ (MinimumUserPossessEquipJobProto_Builder*) builderWithPrototype:(MinimumUserPossessEquipJobProto*) prototype;

+ (MinimumUserPossessEquipJobProto*) parseFromData:(NSData*) data;
+ (MinimumUserPossessEquipJobProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MinimumUserPossessEquipJobProto*) parseFromInputStream:(NSInputStream*) input;
+ (MinimumUserPossessEquipJobProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MinimumUserPossessEquipJobProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MinimumUserPossessEquipJobProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MinimumUserPossessEquipJobProto_Builder : PBGeneratedMessage_Builder {
@private
  MinimumUserPossessEquipJobProto* result;
}

- (MinimumUserPossessEquipJobProto*) defaultInstance;

- (MinimumUserPossessEquipJobProto_Builder*) clear;
- (MinimumUserPossessEquipJobProto_Builder*) clone;

- (MinimumUserPossessEquipJobProto*) build;
- (MinimumUserPossessEquipJobProto*) buildPartial;

- (MinimumUserPossessEquipJobProto_Builder*) mergeFrom:(MinimumUserPossessEquipJobProto*) other;
- (MinimumUserPossessEquipJobProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MinimumUserPossessEquipJobProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (MinimumUserPossessEquipJobProto_Builder*) setUserId:(int32_t) value;
- (MinimumUserPossessEquipJobProto_Builder*) clearUserId;

- (BOOL) hasQuestId;
- (int32_t) questId;
- (MinimumUserPossessEquipJobProto_Builder*) setQuestId:(int32_t) value;
- (MinimumUserPossessEquipJobProto_Builder*) clearQuestId;

- (BOOL) hasPossessEquipJobProto;
- (PossessEquipJobProto*) possessEquipJobProto;
- (MinimumUserPossessEquipJobProto_Builder*) setPossessEquipJobProto:(PossessEquipJobProto*) value;
- (MinimumUserPossessEquipJobProto_Builder*) setPossessEquipJobProtoBuilder:(PossessEquipJobProto_Builder*) builderForValue;
- (MinimumUserPossessEquipJobProto_Builder*) mergePossessEquipJobProto:(PossessEquipJobProto*) value;
- (MinimumUserPossessEquipJobProto_Builder*) clearPossessEquipJobProto;

- (BOOL) hasIsComplete;
- (BOOL) isComplete;
- (MinimumUserPossessEquipJobProto_Builder*) setIsComplete:(BOOL) value;
- (MinimumUserPossessEquipJobProto_Builder*) clearIsComplete;
@end

@interface PossessEquipJobProto : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasEquipId_:1;
  BOOL hasQuantityReq_:1;
  int32_t id;
  int32_t equipId;
  int32_t quantityReq;
}
- (BOOL) hasId;
- (BOOL) hasEquipId;
- (BOOL) hasQuantityReq;
@property (readonly) int32_t id;
@property (readonly) int32_t equipId;
@property (readonly) int32_t quantityReq;

+ (PossessEquipJobProto*) defaultInstance;
- (PossessEquipJobProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PossessEquipJobProto_Builder*) builder;
+ (PossessEquipJobProto_Builder*) builder;
+ (PossessEquipJobProto_Builder*) builderWithPrototype:(PossessEquipJobProto*) prototype;

+ (PossessEquipJobProto*) parseFromData:(NSData*) data;
+ (PossessEquipJobProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PossessEquipJobProto*) parseFromInputStream:(NSInputStream*) input;
+ (PossessEquipJobProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PossessEquipJobProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PossessEquipJobProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PossessEquipJobProto_Builder : PBGeneratedMessage_Builder {
@private
  PossessEquipJobProto* result;
}

- (PossessEquipJobProto*) defaultInstance;

- (PossessEquipJobProto_Builder*) clear;
- (PossessEquipJobProto_Builder*) clone;

- (PossessEquipJobProto*) build;
- (PossessEquipJobProto*) buildPartial;

- (PossessEquipJobProto_Builder*) mergeFrom:(PossessEquipJobProto*) other;
- (PossessEquipJobProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PossessEquipJobProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (int32_t) id;
- (PossessEquipJobProto_Builder*) setId:(int32_t) value;
- (PossessEquipJobProto_Builder*) clearId;

- (BOOL) hasEquipId;
- (int32_t) equipId;
- (PossessEquipJobProto_Builder*) setEquipId:(int32_t) value;
- (PossessEquipJobProto_Builder*) clearEquipId;

- (BOOL) hasQuantityReq;
- (int32_t) quantityReq;
- (PossessEquipJobProto_Builder*) setQuantityReq:(int32_t) value;
- (PossessEquipJobProto_Builder*) clearQuantityReq;
@end

@interface FullQuestProto : PBGeneratedMessage {
@private
  BOOL hasEquipIdGained_:1;
  BOOL hasExpGained_:1;
  BOOL hasWoodGained_:1;
  BOOL hasDiamondsGained_:1;
  BOOL hasCoinsGained_:1;
  BOOL hasAssetNumWithinCity_:1;
  BOOL hasCityId_:1;
  BOOL hasId_:1;
  BOOL hasInProgress_:1;
  BOOL hasDoneResponse_:1;
  BOOL hasDescription_:1;
  BOOL hasName_:1;
  int32_t equipIdGained;
  int32_t expGained;
  int32_t woodGained;
  int32_t diamondsGained;
  int32_t coinsGained;
  int32_t assetNumWithinCity;
  int32_t cityId;
  int32_t id;
  NSString* inProgress;
  NSString* doneResponse;
  NSString* description;
  NSString* name;
  NSMutableArray* mutableQuestsRequiredForThisList;
  NSMutableArray* mutableTaskReqsList;
  NSMutableArray* mutableUpgradeStructJobsReqsList;
  NSMutableArray* mutableBuildStructJobsReqsList;
  NSMutableArray* mutableDefeatTypeReqsList;
  NSMutableArray* mutablePossessEquipJobReqsList;
}
- (BOOL) hasId;
- (BOOL) hasCityId;
- (BOOL) hasName;
- (BOOL) hasDescription;
- (BOOL) hasDoneResponse;
- (BOOL) hasInProgress;
- (BOOL) hasAssetNumWithinCity;
- (BOOL) hasCoinsGained;
- (BOOL) hasDiamondsGained;
- (BOOL) hasWoodGained;
- (BOOL) hasExpGained;
- (BOOL) hasEquipIdGained;
@property (readonly) int32_t id;
@property (readonly) int32_t cityId;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSString* description;
@property (readonly, retain) NSString* doneResponse;
@property (readonly, retain) NSString* inProgress;
@property (readonly) int32_t assetNumWithinCity;
@property (readonly) int32_t coinsGained;
@property (readonly) int32_t diamondsGained;
@property (readonly) int32_t woodGained;
@property (readonly) int32_t expGained;
@property (readonly) int32_t equipIdGained;
- (NSArray*) questsRequiredForThisList;
- (int32_t) questsRequiredForThisAtIndex:(int32_t) index;
- (NSArray*) taskReqsList;
- (int32_t) taskReqsAtIndex:(int32_t) index;
- (NSArray*) upgradeStructJobsReqsList;
- (int32_t) upgradeStructJobsReqsAtIndex:(int32_t) index;
- (NSArray*) buildStructJobsReqsList;
- (int32_t) buildStructJobsReqsAtIndex:(int32_t) index;
- (NSArray*) defeatTypeReqsList;
- (int32_t) defeatTypeReqsAtIndex:(int32_t) index;
- (NSArray*) possessEquipJobReqsList;
- (int32_t) possessEquipJobReqsAtIndex:(int32_t) index;

+ (FullQuestProto*) defaultInstance;
- (FullQuestProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FullQuestProto_Builder*) builder;
+ (FullQuestProto_Builder*) builder;
+ (FullQuestProto_Builder*) builderWithPrototype:(FullQuestProto*) prototype;

+ (FullQuestProto*) parseFromData:(NSData*) data;
+ (FullQuestProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullQuestProto*) parseFromInputStream:(NSInputStream*) input;
+ (FullQuestProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FullQuestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FullQuestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FullQuestProto_Builder : PBGeneratedMessage_Builder {
@private
  FullQuestProto* result;
}

- (FullQuestProto*) defaultInstance;

- (FullQuestProto_Builder*) clear;
- (FullQuestProto_Builder*) clone;

- (FullQuestProto*) build;
- (FullQuestProto*) buildPartial;

- (FullQuestProto_Builder*) mergeFrom:(FullQuestProto*) other;
- (FullQuestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FullQuestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (int32_t) id;
- (FullQuestProto_Builder*) setId:(int32_t) value;
- (FullQuestProto_Builder*) clearId;

- (BOOL) hasCityId;
- (int32_t) cityId;
- (FullQuestProto_Builder*) setCityId:(int32_t) value;
- (FullQuestProto_Builder*) clearCityId;

- (BOOL) hasName;
- (NSString*) name;
- (FullQuestProto_Builder*) setName:(NSString*) value;
- (FullQuestProto_Builder*) clearName;

- (BOOL) hasDescription;
- (NSString*) description;
- (FullQuestProto_Builder*) setDescription:(NSString*) value;
- (FullQuestProto_Builder*) clearDescription;

- (BOOL) hasDoneResponse;
- (NSString*) doneResponse;
- (FullQuestProto_Builder*) setDoneResponse:(NSString*) value;
- (FullQuestProto_Builder*) clearDoneResponse;

- (BOOL) hasInProgress;
- (NSString*) inProgress;
- (FullQuestProto_Builder*) setInProgress:(NSString*) value;
- (FullQuestProto_Builder*) clearInProgress;

- (BOOL) hasAssetNumWithinCity;
- (int32_t) assetNumWithinCity;
- (FullQuestProto_Builder*) setAssetNumWithinCity:(int32_t) value;
- (FullQuestProto_Builder*) clearAssetNumWithinCity;

- (BOOL) hasCoinsGained;
- (int32_t) coinsGained;
- (FullQuestProto_Builder*) setCoinsGained:(int32_t) value;
- (FullQuestProto_Builder*) clearCoinsGained;

- (BOOL) hasDiamondsGained;
- (int32_t) diamondsGained;
- (FullQuestProto_Builder*) setDiamondsGained:(int32_t) value;
- (FullQuestProto_Builder*) clearDiamondsGained;

- (BOOL) hasWoodGained;
- (int32_t) woodGained;
- (FullQuestProto_Builder*) setWoodGained:(int32_t) value;
- (FullQuestProto_Builder*) clearWoodGained;

- (BOOL) hasExpGained;
- (int32_t) expGained;
- (FullQuestProto_Builder*) setExpGained:(int32_t) value;
- (FullQuestProto_Builder*) clearExpGained;

- (BOOL) hasEquipIdGained;
- (int32_t) equipIdGained;
- (FullQuestProto_Builder*) setEquipIdGained:(int32_t) value;
- (FullQuestProto_Builder*) clearEquipIdGained;

- (NSArray*) questsRequiredForThisList;
- (int32_t) questsRequiredForThisAtIndex:(int32_t) index;
- (FullQuestProto_Builder*) replaceQuestsRequiredForThisAtIndex:(int32_t) index with:(int32_t) value;
- (FullQuestProto_Builder*) addQuestsRequiredForThis:(int32_t) value;
- (FullQuestProto_Builder*) addAllQuestsRequiredForThis:(NSArray*) values;
- (FullQuestProto_Builder*) clearQuestsRequiredForThisList;

- (NSArray*) taskReqsList;
- (int32_t) taskReqsAtIndex:(int32_t) index;
- (FullQuestProto_Builder*) replaceTaskReqsAtIndex:(int32_t) index with:(int32_t) value;
- (FullQuestProto_Builder*) addTaskReqs:(int32_t) value;
- (FullQuestProto_Builder*) addAllTaskReqs:(NSArray*) values;
- (FullQuestProto_Builder*) clearTaskReqsList;

- (NSArray*) upgradeStructJobsReqsList;
- (int32_t) upgradeStructJobsReqsAtIndex:(int32_t) index;
- (FullQuestProto_Builder*) replaceUpgradeStructJobsReqsAtIndex:(int32_t) index with:(int32_t) value;
- (FullQuestProto_Builder*) addUpgradeStructJobsReqs:(int32_t) value;
- (FullQuestProto_Builder*) addAllUpgradeStructJobsReqs:(NSArray*) values;
- (FullQuestProto_Builder*) clearUpgradeStructJobsReqsList;

- (NSArray*) buildStructJobsReqsList;
- (int32_t) buildStructJobsReqsAtIndex:(int32_t) index;
- (FullQuestProto_Builder*) replaceBuildStructJobsReqsAtIndex:(int32_t) index with:(int32_t) value;
- (FullQuestProto_Builder*) addBuildStructJobsReqs:(int32_t) value;
- (FullQuestProto_Builder*) addAllBuildStructJobsReqs:(NSArray*) values;
- (FullQuestProto_Builder*) clearBuildStructJobsReqsList;

- (NSArray*) defeatTypeReqsList;
- (int32_t) defeatTypeReqsAtIndex:(int32_t) index;
- (FullQuestProto_Builder*) replaceDefeatTypeReqsAtIndex:(int32_t) index with:(int32_t) value;
- (FullQuestProto_Builder*) addDefeatTypeReqs:(int32_t) value;
- (FullQuestProto_Builder*) addAllDefeatTypeReqs:(NSArray*) values;
- (FullQuestProto_Builder*) clearDefeatTypeReqsList;

- (NSArray*) possessEquipJobReqsList;
- (int32_t) possessEquipJobReqsAtIndex:(int32_t) index;
- (FullQuestProto_Builder*) replacePossessEquipJobReqsAtIndex:(int32_t) index with:(int32_t) value;
- (FullQuestProto_Builder*) addPossessEquipJobReqs:(int32_t) value;
- (FullQuestProto_Builder*) addAllPossessEquipJobReqs:(NSArray*) values;
- (FullQuestProto_Builder*) clearPossessEquipJobReqsList;
@end

