// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "Event.pb.h"

@class ApproveOrRejectRequestToJoinClanRequestProto;
@class ApproveOrRejectRequestToJoinClanRequestProto_Builder;
@class ApproveOrRejectRequestToJoinClanResponseProto;
@class ApproveOrRejectRequestToJoinClanResponseProto_Builder;
@class ArmoryRequestProto;
@class ArmoryRequestProto_Builder;
@class ArmoryResponseProto;
@class ArmoryResponseProto_Builder;
@class BattleRequestProto;
@class BattleRequestProto_Builder;
@class BattleResponseProto;
@class BattleResponseProto_Builder;
@class BeginClanTowerWarRequestProto;
@class BeginClanTowerWarRequestProto_Builder;
@class BeginClanTowerWarResponseProto;
@class BeginClanTowerWarResponseProto_Builder;
@class BeginGoldmineTimerRequestProto;
@class BeginGoldmineTimerRequestProto_Builder;
@class BeginGoldmineTimerResponseProto;
@class BeginGoldmineTimerResponseProto_Builder;
@class BootPlayerFromClanRequestProto;
@class BootPlayerFromClanRequestProto_Builder;
@class BootPlayerFromClanResponseProto;
@class BootPlayerFromClanResponseProto_Builder;
@class BossActionRequestProto;
@class BossActionRequestProto_Builder;
@class BossActionResponseProto;
@class BossActionResponseProto_Builder;
@class BossEventProto;
@class BossEventProto_Builder;
@class BuildStructJobProto;
@class BuildStructJobProto_Builder;
@class ChangeClanDescriptionRequestProto;
@class ChangeClanDescriptionRequestProto_Builder;
@class ChangeClanDescriptionResponseProto;
@class ChangeClanDescriptionResponseProto_Builder;
@class ChangeUserLocationRequestProto;
@class ChangeUserLocationRequestProto_Builder;
@class ChangeUserLocationResponseProto;
@class ChangeUserLocationResponseProto_Builder;
@class ChangedClanTowerResponseProto;
@class ChangedClanTowerResponseProto_Builder;
@class CharacterModRequestProto;
@class CharacterModRequestProto_Builder;
@class CharacterModResponseProto;
@class CharacterModResponseProto_Builder;
@class ChatRequestProto;
@class ChatRequestProto_Builder;
@class ChatResponseProto;
@class ChatResponseProto_Builder;
@class ClanBulletinPostProto;
@class ClanBulletinPostProto_Builder;
@class ClanTierLevelProto;
@class ClanTierLevelProto_Builder;
@class ClanTowerProto;
@class ClanTowerProto_Builder;
@class CollectForgeEquipsRequestProto;
@class CollectForgeEquipsRequestProto_Builder;
@class CollectForgeEquipsResponseProto;
@class CollectForgeEquipsResponseProto_Builder;
@class CollectFromGoldmineRequestProto;
@class CollectFromGoldmineRequestProto_Builder;
@class CollectFromGoldmineResponseProto;
@class CollectFromGoldmineResponseProto_Builder;
@class ColorProto;
@class ColorProto_Builder;
@class ConcedeClanTowerWarRequestProto;
@class ConcedeClanTowerWarRequestProto_Builder;
@class ConcedeClanTowerWarResponseProto;
@class ConcedeClanTowerWarResponseProto_Builder;
@class CoordinateProto;
@class CoordinateProto_Builder;
@class CreateClanRequestProto;
@class CreateClanRequestProto_Builder;
@class CreateClanResponseProto;
@class CreateClanResponseProto_Builder;
@class CriticalStructureActionRequestProto;
@class CriticalStructureActionRequestProto_Builder;
@class CriticalStructureActionResponseProto;
@class CriticalStructureActionResponseProto_Builder;
@class DefeatTypeJobProto;
@class DefeatTypeJobProto_Builder;
@class DialogueProto;
@class DialogueProto_Builder;
@class DialogueProto_SpeechSegmentProto;
@class DialogueProto_SpeechSegmentProto_Builder;
@class EarnFreeDiamondsRequestProto;
@class EarnFreeDiamondsRequestProto_Builder;
@class EarnFreeDiamondsResponseProto;
@class EarnFreeDiamondsResponseProto_Builder;
@class EnableAPNSRequestProto;
@class EnableAPNSRequestProto_Builder;
@class EnableAPNSResponseProto;
@class EnableAPNSResponseProto_Builder;
@class EquipEquipmentRequestProto;
@class EquipEquipmentRequestProto_Builder;
@class EquipEquipmentResponseProto;
@class EquipEquipmentResponseProto_Builder;
@class ExpansionWaitCompleteRequestProto;
@class ExpansionWaitCompleteRequestProto_Builder;
@class ExpansionWaitCompleteResponseProto;
@class ExpansionWaitCompleteResponseProto_Builder;
@class FinishForgeAttemptWaittimeWithDiamondsRequestProto;
@class FinishForgeAttemptWaittimeWithDiamondsRequestProto_Builder;
@class FinishForgeAttemptWaittimeWithDiamondsResponseProto;
@class FinishForgeAttemptWaittimeWithDiamondsResponseProto_Builder;
@class FinishNormStructWaittimeWithDiamondsRequestProto;
@class FinishNormStructWaittimeWithDiamondsRequestProto_Builder;
@class FinishNormStructWaittimeWithDiamondsResponseProto;
@class FinishNormStructWaittimeWithDiamondsResponseProto_Builder;
@class ForgeAttemptWaitCompleteRequestProto;
@class ForgeAttemptWaitCompleteRequestProto_Builder;
@class ForgeAttemptWaitCompleteResponseProto;
@class ForgeAttemptWaitCompleteResponseProto_Builder;
@class FullBossProto;
@class FullBossProto_Builder;
@class FullCityProto;
@class FullCityProto_Builder;
@class FullClanProto;
@class FullClanProtoWithClanSize;
@class FullClanProtoWithClanSize_Builder;
@class FullClanProto_Builder;
@class FullEquipProto;
@class FullEquipProto_Builder;
@class FullMarketplacePostProto;
@class FullMarketplacePostProto_Builder;
@class FullQuestProto;
@class FullQuestProto_Builder;
@class FullStructureProto;
@class FullStructureProto_Builder;
@class FullTaskProto;
@class FullTaskProto_Builder;
@class FullTaskProto_FullTaskEquipReqProto;
@class FullTaskProto_FullTaskEquipReqProto_Builder;
@class FullUserBossProto;
@class FullUserBossProto_Builder;
@class FullUserCityExpansionDataProto;
@class FullUserCityExpansionDataProto_Builder;
@class FullUserCityProto;
@class FullUserCityProto_Builder;
@class FullUserClanProto;
@class FullUserClanProto_Builder;
@class FullUserCritstructProto;
@class FullUserCritstructProto_Builder;
@class FullUserEquipProto;
@class FullUserEquipProto_Builder;
@class FullUserProto;
@class FullUserProto_Builder;
@class FullUserQuestDataLargeProto;
@class FullUserQuestDataLargeProto_Builder;
@class FullUserStructureProto;
@class FullUserStructureProto_Builder;
@class GeneralNotificationResponseProto;
@class GeneralNotificationResponseProto_Builder;
@class GenerateAttackListRequestProto;
@class GenerateAttackListRequestProto_Builder;
@class GenerateAttackListResponseProto;
@class GenerateAttackListResponseProto_Builder;
@class GoldSaleProto;
@class GoldSaleProto_Builder;
@class GroupChatMessageProto;
@class GroupChatMessageProto_Builder;
@class InAppPurchaseRequestProto;
@class InAppPurchaseRequestProto_Builder;
@class InAppPurchaseResponseProto;
@class InAppPurchaseResponseProto_Builder;
@class LeaderboardEventProto;
@class LeaderboardEventProto_Builder;
@class LeaderboardEventRewardProto;
@class LeaderboardEventRewardProto_Builder;
@class LeaveClanRequestProto;
@class LeaveClanRequestProto_Builder;
@class LeaveClanResponseProto;
@class LeaveClanResponseProto_Builder;
@class LevelUpRequestProto;
@class LevelUpRequestProto_Builder;
@class LevelUpResponseProto;
@class LevelUpResponseProto_Builder;
@class LoadNeutralCityRequestProto;
@class LoadNeutralCityRequestProto_Builder;
@class LoadNeutralCityResponseProto;
@class LoadNeutralCityResponseProto_Builder;
@class LoadPlayerCityRequestProto;
@class LoadPlayerCityRequestProto_Builder;
@class LoadPlayerCityResponseProto;
@class LoadPlayerCityResponseProto_Builder;
@class LocationProto;
@class LocationProto_Builder;
@class LockBoxEventProto;
@class LockBoxEventProto_Builder;
@class LockBoxItemProto;
@class LockBoxItemProto_Builder;
@class LogoutRequestProto;
@class LogoutRequestProto_Builder;
@class MinimumClanProto;
@class MinimumClanProto_Builder;
@class MinimumUserBuildStructJobProto;
@class MinimumUserBuildStructJobProto_Builder;
@class MinimumUserDefeatTypeJobProto;
@class MinimumUserDefeatTypeJobProto_Builder;
@class MinimumUserPossessEquipJobProto;
@class MinimumUserPossessEquipJobProto_Builder;
@class MinimumUserProto;
@class MinimumUserProtoForClans;
@class MinimumUserProtoForClans_Builder;
@class MinimumUserProtoWithBattleHistory;
@class MinimumUserProtoWithBattleHistory_Builder;
@class MinimumUserProtoWithLevel;
@class MinimumUserProtoWithLevelForLeaderboard;
@class MinimumUserProtoWithLevelForLeaderboard_Builder;
@class MinimumUserProtoWithLevel_Builder;
@class MinimumUserProto_Builder;
@class MinimumUserQuestTaskProto;
@class MinimumUserQuestTaskProto_Builder;
@class MinimumUserTaskProto;
@class MinimumUserTaskProto_Builder;
@class MinimumUserUpgradeStructJobProto;
@class MinimumUserUpgradeStructJobProto_Builder;
@class MonteCardProto;
@class MonteCardProto_Builder;
@class MoveOrRotateNormStructureRequestProto;
@class MoveOrRotateNormStructureRequestProto_Builder;
@class MoveOrRotateNormStructureResponseProto;
@class MoveOrRotateNormStructureResponseProto_Builder;
@class NeutralCityElementProto;
@class NeutralCityElementProto_Builder;
@class NormStructWaitCompleteRequestProto;
@class NormStructWaitCompleteRequestProto_Builder;
@class NormStructWaitCompleteResponseProto;
@class NormStructWaitCompleteResponseProto_Builder;
@class PickLockBoxRequestProto;
@class PickLockBoxRequestProto_Builder;
@class PickLockBoxResponseProto;
@class PickLockBoxResponseProto_Builder;
@class PlayThreeCardMonteRequestProto;
@class PlayThreeCardMonteRequestProto_Builder;
@class PlayThreeCardMonteResponseProto;
@class PlayThreeCardMonteResponseProto_Builder;
@class PlayerWallPostProto;
@class PlayerWallPostProto_Builder;
@class PossessEquipJobProto;
@class PossessEquipJobProto_Builder;
@class PostOnClanBulletinRequestProto;
@class PostOnClanBulletinRequestProto_Builder;
@class PostOnClanBulletinResponseProto;
@class PostOnClanBulletinResponseProto_Builder;
@class PostOnPlayerWallRequestProto;
@class PostOnPlayerWallRequestProto_Builder;
@class PostOnPlayerWallResponseProto;
@class PostOnPlayerWallResponseProto_Builder;
@class PostToMarketplaceRequestProto;
@class PostToMarketplaceRequestProto_Builder;
@class PostToMarketplaceResponseProto;
@class PostToMarketplaceResponseProto_Builder;
@class PurchaseCityExpansionRequestProto;
@class PurchaseCityExpansionRequestProto_Builder;
@class PurchaseCityExpansionResponseProto;
@class PurchaseCityExpansionResponseProto_Builder;
@class PurchaseFromMarketplaceRequestProto;
@class PurchaseFromMarketplaceRequestProto_Builder;
@class PurchaseFromMarketplaceResponseProto;
@class PurchaseFromMarketplaceResponseProto_Builder;
@class PurchaseGroupChatRequestProto;
@class PurchaseGroupChatRequestProto_Builder;
@class PurchaseGroupChatResponseProto;
@class PurchaseGroupChatResponseProto_Builder;
@class PurchaseMarketplaceLicenseRequestProto;
@class PurchaseMarketplaceLicenseRequestProto_Builder;
@class PurchaseMarketplaceLicenseResponseProto;
@class PurchaseMarketplaceLicenseResponseProto_Builder;
@class PurchaseNormStructureRequestProto;
@class PurchaseNormStructureRequestProto_Builder;
@class PurchaseNormStructureResponseProto;
@class PurchaseNormStructureResponseProto_Builder;
@class PurgeClientStaticDataResponseProto;
@class PurgeClientStaticDataResponseProto_Builder;
@class QuestAcceptRequestProto;
@class QuestAcceptRequestProto_Builder;
@class QuestAcceptResponseProto;
@class QuestAcceptResponseProto_Builder;
@class QuestCompleteResponseProto;
@class QuestCompleteResponseProto_Builder;
@class QuestRedeemRequestProto;
@class QuestRedeemRequestProto_Builder;
@class QuestRedeemResponseProto;
@class QuestRedeemResponseProto_Builder;
@class ReceivedGroupChatResponseProto;
@class ReceivedGroupChatResponseProto_Builder;
@class ReconnectRequestProto;
@class ReconnectRequestProto_Builder;
@class ReconnectResponseProto;
@class ReconnectResponseProto_Builder;
@class RedeemMarketplaceEarningsRequestProto;
@class RedeemMarketplaceEarningsRequestProto_Builder;
@class RedeemMarketplaceEarningsResponseProto;
@class RedeemMarketplaceEarningsResponseProto_Builder;
@class ReferralCodeUsedResponseProto;
@class ReferralCodeUsedResponseProto_Builder;
@class RefillStatWaitCompleteRequestProto;
@class RefillStatWaitCompleteRequestProto_Builder;
@class RefillStatWaitCompleteResponseProto;
@class RefillStatWaitCompleteResponseProto_Builder;
@class RefillStatWithDiamondsRequestProto;
@class RefillStatWithDiamondsRequestProto_Builder;
@class RefillStatWithDiamondsResponseProto;
@class RefillStatWithDiamondsResponseProto_Builder;
@class RequestJoinClanRequestProto;
@class RequestJoinClanRequestProto_Builder;
@class RequestJoinClanResponseProto;
@class RequestJoinClanResponseProto_Builder;
@class RetractMarketplacePostRequestProto;
@class RetractMarketplacePostRequestProto_Builder;
@class RetractMarketplacePostResponseProto;
@class RetractMarketplacePostResponseProto_Builder;
@class RetractRequestJoinClanRequestProto;
@class RetractRequestJoinClanRequestProto_Builder;
@class RetractRequestJoinClanResponseProto;
@class RetractRequestJoinClanResponseProto_Builder;
@class RetrieveClanBulletinPostsRequestProto;
@class RetrieveClanBulletinPostsRequestProto_Builder;
@class RetrieveClanBulletinPostsResponseProto;
@class RetrieveClanBulletinPostsResponseProto_Builder;
@class RetrieveClanInfoRequestProto;
@class RetrieveClanInfoRequestProto_Builder;
@class RetrieveClanInfoResponseProto;
@class RetrieveClanInfoResponseProto_Builder;
@class RetrieveCurrencyFromNormStructureRequestProto;
@class RetrieveCurrencyFromNormStructureRequestProto_Builder;
@class RetrieveCurrencyFromNormStructureRequestProto_StructRetrieval;
@class RetrieveCurrencyFromNormStructureRequestProto_StructRetrieval_Builder;
@class RetrieveCurrencyFromNormStructureResponseProto;
@class RetrieveCurrencyFromNormStructureResponseProto_Builder;
@class RetrieveCurrentMarketplacePostsRequestProto;
@class RetrieveCurrentMarketplacePostsRequestProto_Builder;
@class RetrieveCurrentMarketplacePostsResponseProto;
@class RetrieveCurrentMarketplacePostsResponseProto_Builder;
@class RetrieveLeaderboardRankingsRequestProto;
@class RetrieveLeaderboardRankingsRequestProto_Builder;
@class RetrieveLeaderboardRankingsResponseProto;
@class RetrieveLeaderboardRankingsResponseProto_Builder;
@class RetrieveLeaderboardRequestProto;
@class RetrieveLeaderboardRequestProto_Builder;
@class RetrieveLeaderboardResponseProto;
@class RetrieveLeaderboardResponseProto_Builder;
@class RetrievePlayerWallPostsRequestProto;
@class RetrievePlayerWallPostsRequestProto_Builder;
@class RetrievePlayerWallPostsResponseProto;
@class RetrievePlayerWallPostsResponseProto_Builder;
@class RetrieveStaticDataForShopRequestProto;
@class RetrieveStaticDataForShopRequestProto_Builder;
@class RetrieveStaticDataForShopResponseProto;
@class RetrieveStaticDataForShopResponseProto_Builder;
@class RetrieveStaticDataRequestProto;
@class RetrieveStaticDataRequestProto_Builder;
@class RetrieveStaticDataResponseProto;
@class RetrieveStaticDataResponseProto_Builder;
@class RetrieveTasksForCityRequestProto;
@class RetrieveTasksForCityRequestProto_Builder;
@class RetrieveTasksForCityResponseProto;
@class RetrieveTasksForCityResponseProto_Builder;
@class RetrieveThreeCardMonteRequestProto;
@class RetrieveThreeCardMonteRequestProto_Builder;
@class RetrieveThreeCardMonteResponseProto;
@class RetrieveThreeCardMonteResponseProto_Builder;
@class RetrieveUserEquipForUserRequestProto;
@class RetrieveUserEquipForUserRequestProto_Builder;
@class RetrieveUserEquipForUserResponseProto;
@class RetrieveUserEquipForUserResponseProto_Builder;
@class RetrieveUsersForUserIdsRequestProto;
@class RetrieveUsersForUserIdsRequestProto_Builder;
@class RetrieveUsersForUserIdsResponseProto;
@class RetrieveUsersForUserIdsResponseProto_Builder;
@class SellNormStructureRequestProto;
@class SellNormStructureRequestProto_Builder;
@class SellNormStructureResponseProto;
@class SellNormStructureResponseProto_Builder;
@class SendAdminMessageResponseProto;
@class SendAdminMessageResponseProto_Builder;
@class SendGroupChatRequestProto;
@class SendGroupChatRequestProto_Builder;
@class SendGroupChatResponseProto;
@class SendGroupChatResponseProto_Builder;
@class StartupRequestProto;
@class StartupRequestProto_Builder;
@class StartupResponseProto;
@class StartupResponseProto_AttackedNotificationProto;
@class StartupResponseProto_AttackedNotificationProto_Builder;
@class StartupResponseProto_Builder;
@class StartupResponseProto_DailyBonusInfo;
@class StartupResponseProto_DailyBonusInfo_Builder;
@class StartupResponseProto_MarketplacePostPurchasedNotificationProto;
@class StartupResponseProto_MarketplacePostPurchasedNotificationProto_Builder;
@class StartupResponseProto_ReferralNotificationProto;
@class StartupResponseProto_ReferralNotificationProto_Builder;
@class StartupResponseProto_StartupConstants;
@class StartupResponseProto_StartupConstants_AnimatedSpriteOffsetProto;
@class StartupResponseProto_StartupConstants_AnimatedSpriteOffsetProto_Builder;
@class StartupResponseProto_StartupConstants_BattleConstants;
@class StartupResponseProto_StartupConstants_BattleConstants_Builder;
@class StartupResponseProto_StartupConstants_BazaarMinLevelConstants;
@class StartupResponseProto_StartupConstants_BazaarMinLevelConstants_Builder;
@class StartupResponseProto_StartupConstants_Builder;
@class StartupResponseProto_StartupConstants_CharacterModConstants;
@class StartupResponseProto_StartupConstants_CharacterModConstants_Builder;
@class StartupResponseProto_StartupConstants_ClanConstants;
@class StartupResponseProto_StartupConstants_ClanConstants_Builder;
@class StartupResponseProto_StartupConstants_DownloadableNibConstants;
@class StartupResponseProto_StartupConstants_DownloadableNibConstants_Builder;
@class StartupResponseProto_StartupConstants_ExpansionConstants;
@class StartupResponseProto_StartupConstants_ExpansionConstants_Builder;
@class StartupResponseProto_StartupConstants_ForgeConstants;
@class StartupResponseProto_StartupConstants_ForgeConstants_Builder;
@class StartupResponseProto_StartupConstants_FormulaConstants;
@class StartupResponseProto_StartupConstants_FormulaConstants_Builder;
@class StartupResponseProto_StartupConstants_GoldmineConstants;
@class StartupResponseProto_StartupConstants_GoldmineConstants_Builder;
@class StartupResponseProto_StartupConstants_KiipRewardConditions;
@class StartupResponseProto_StartupConstants_KiipRewardConditions_Builder;
@class StartupResponseProto_StartupConstants_LockBoxConstants;
@class StartupResponseProto_StartupConstants_LockBoxConstants_Builder;
@class StartupResponseProto_StartupConstants_ThreeCardMonteConstants;
@class StartupResponseProto_StartupConstants_ThreeCardMonteConstants_Builder;
@class StartupResponseProto_TutorialConstants;
@class StartupResponseProto_TutorialConstants_Builder;
@class StartupResponseProto_TutorialConstants_FullTutorialQuestProto;
@class StartupResponseProto_TutorialConstants_FullTutorialQuestProto_Builder;
@class SubmitEquipsToBlacksmithRequestProto;
@class SubmitEquipsToBlacksmithRequestProto_Builder;
@class SubmitEquipsToBlacksmithResponseProto;
@class SubmitEquipsToBlacksmithResponseProto_Builder;
@class TaskActionRequestProto;
@class TaskActionRequestProto_Builder;
@class TaskActionResponseProto;
@class TaskActionResponseProto_Builder;
@class TransferClanOwnershipRequestProto;
@class TransferClanOwnershipRequestProto_Builder;
@class TransferClanOwnershipResponseProto;
@class TransferClanOwnershipResponseProto_Builder;
@class UnhandledBlacksmithAttemptProto;
@class UnhandledBlacksmithAttemptProto_Builder;
@class UpdateClientUserResponseProto;
@class UpdateClientUserResponseProto_Builder;
@class UpgradeClanTierLevelRequestProto;
@class UpgradeClanTierLevelRequestProto_Builder;
@class UpgradeClanTierLevelResponseProto;
@class UpgradeClanTierLevelResponseProto_Builder;
@class UpgradeNormStructureRequestProto;
@class UpgradeNormStructureRequestProto_Builder;
@class UpgradeNormStructureResponseProto;
@class UpgradeNormStructureResponseProto_Builder;
@class UpgradeStructJobProto;
@class UpgradeStructJobProto_Builder;
@class UseSkillPointRequestProto;
@class UseSkillPointRequestProto_Builder;
@class UseSkillPointResponseProto;
@class UseSkillPointResponseProto_Builder;
@class UserCreateRequestProto;
@class UserCreateRequestProto_Builder;
@class UserCreateResponseProto;
@class UserCreateResponseProto_Builder;
@class UserLockBoxEventProto;
@class UserLockBoxEventProto_Builder;
@class UserLockBoxItemProto;
@class UserLockBoxItemProto_Builder;
@class UserQuestDetailsRequestProto;
@class UserQuestDetailsRequestProto_Builder;
@class UserQuestDetailsResponseProto;
@class UserQuestDetailsResponseProto_Builder;
@class VaultRequestProto;
@class VaultRequestProto_Builder;
@class VaultResponseProto;
@class VaultResponseProto_Builder;
typedef enum {
  EventProtocolRequestCChatEvent = 0,
  EventProtocolRequestCBattleEvent = 1,
  EventProtocolRequestCVaultEvent = 2,
  EventProtocolRequestCTaskActionEvent = 3,
  EventProtocolRequestCRetrieveUserEquipForUser = 4,
  EventProtocolRequestCStartupEvent = 5,
  EventProtocolRequestCRetrieveStaticDataForShopEvent = 8,
  EventProtocolRequestCArmoryEvent = 9,
  EventProtocolRequestCInAppPurchaseEvent = 10,
  EventProtocolRequestCRetrieveCurrentMarketplacePostsEvent = 11,
  EventProtocolRequestCPostToMarketplaceEvent = 12,
  EventProtocolRequestCRetractPostFromMarketplaceEvent = 13,
  EventProtocolRequestCPurchaseFromMarketplaceEvent = 14,
  EventProtocolRequestCUseSkillPointEvent = 15,
  EventProtocolRequestCGenerateAttackListEvent = 16,
  EventProtocolRequestCPurchaseNormStructureEvent = 17,
  EventProtocolRequestCMoveOrRotateNormStructureEvent = 18,
  EventProtocolRequestCSellNormStructureEvent = 19,
  EventProtocolRequestCUpgradeNormStructureEvent = 20,
  EventProtocolRequestCRetrieveCurrencyFromNormStructureEvent = 21,
  EventProtocolRequestCRefillStatWithDiamondsEvent = 22,
  EventProtocolRequestCFinishNormStructWaittimeWithDiamondsEvent = 23,
  EventProtocolRequestCNormStructWaitCompleteEvent = 24,
  EventProtocolRequestCRedeemMarketplaceEarningsEvent = 25,
  EventProtocolRequestCCritStructureActionEvent = 26,
  EventProtocolRequestCLoadPlayerCityEvent = 27,
  EventProtocolRequestCRetrieveStaticDataEvent = 28,
  EventProtocolRequestCQuestAcceptEvent = 29,
  EventProtocolRequestCUserQuestDetailsEvent = 30,
  EventProtocolRequestCQuestRedeemEvent = 31,
  EventProtocolRequestCPurchaseCityExpansionEvent = 32,
  EventProtocolRequestCExpansionWaitCompleteEvent = 33,
  EventProtocolRequestCRefillStatWaitCompleteEvent = 34,
  EventProtocolRequestCLevelUpEvent = 35,
  EventProtocolRequestCEnableApnsEvent = 36,
  EventProtocolRequestCPurchaseMarketplaceLicenseEvent = 37,
  EventProtocolRequestCUserCreateEvent = 38,
  EventProtocolRequestCEquipEquipmentEvent = 39,
  EventProtocolRequestCChangeUserLocationEvent = 40,
  EventProtocolRequestCLoadNeutralCityEvent = 41,
  EventProtocolRequestCRetrieveUsersForUserIdsEvent = 42,
  EventProtocolRequestCPostOnPlayerWallEvent = 43,
  EventProtocolRequestCRetrievePlayerWallPostsEvent = 44,
  EventProtocolRequestCEarnFreeDiamondsEvent = 45,
  EventProtocolRequestCReconnectEvent = 46,
  EventProtocolRequestCSubmitEquipsToBlacksmith = 48,
  EventProtocolRequestCForgeAttemptWaitComplete = 49,
  EventProtocolRequestCFinishForgeAttemptWaittimeWithDiamonds = 50,
  EventProtocolRequestCCollectForgeEquips = 51,
  EventProtocolRequestCCharacterModEvent = 52,
  EventProtocolRequestCRetrieveLeaderboardEvent = 53,
  EventProtocolRequestCSendGroupChatEvent = 54,
  EventProtocolRequestCPurchaseGroupChatEvent = 55,
  EventProtocolRequestCCreateClanEvent = 56,
  EventProtocolRequestCLeaveClanEvent = 57,
  EventProtocolRequestCRequestJoinClanEvent = 58,
  EventProtocolRequestCRetractRequestJoinClanEvent = 59,
  EventProtocolRequestCApproveOrRejectRequestToJoinClanEvent = 60,
  EventProtocolRequestCTransferClanOwnership = 61,
  EventProtocolRequestCRetrieveClanInfoEvent = 62,
  EventProtocolRequestCChangeClanDescriptionEvent = 63,
  EventProtocolRequestCPostOnClanBulletinEvent = 64,
  EventProtocolRequestCRetrieveClanBulletinPostsEvent = 65,
  EventProtocolRequestCBootPlayerFromClanEvent = 66,
  EventProtocolRequestCRetrieveThreeCardMonteEvent = 67,
  EventProtocolRequestCPlayThreeCardMonteEvent = 68,
  EventProtocolRequestCBeginGoldmineTimerEvent = 69,
  EventProtocolRequestCCollectFromGoldmineEvent = 70,
  EventProtocolRequestCPickLockBoxEvent = 71,
  EventProtocolRequestCBossActionEvent = 72,
  EventProtocolRequestCBeginClanTowerWar = 73,
  EventProtocolRequestCUpgradeClanTierEvent = 74,
  EventProtocolRequestCConcedeClanTowerWar = 75,
  EventProtocolRequestCRetrieveLeaderboardRankingsEvent = 76,
  EventProtocolRequestCLogoutEvent = 101,
  EventProtocolRequestAAdminUpdate = 300,
} EventProtocolRequest;

BOOL EventProtocolRequestIsValidValue(EventProtocolRequest value);

typedef enum {
  EventProtocolResponseSChatEvent = 0,
  EventProtocolResponseSBattleEvent = 1,
  EventProtocolResponseSVaultEvent = 2,
  EventProtocolResponseSTaskActionEvent = 3,
  EventProtocolResponseSRetrieveUserEquipForUser = 4,
  EventProtocolResponseSStartupEvent = 5,
  EventProtocolResponseSRetrieveStaticDataForShopEvent = 8,
  EventProtocolResponseSArmoryEvent = 9,
  EventProtocolResponseSInAppPurchaseEvent = 10,
  EventProtocolResponseSRetrieveCurrentMarketplacePostsEvent = 11,
  EventProtocolResponseSPostToMarketplaceEvent = 12,
  EventProtocolResponseSRetractPostFromMarketplaceEvent = 13,
  EventProtocolResponseSPurchaseFromMarketplaceEvent = 14,
  EventProtocolResponseSUseSkillPointEvent = 15,
  EventProtocolResponseSGenerateAttackListEvent = 16,
  EventProtocolResponseSPurchaseNormStructureEvent = 17,
  EventProtocolResponseSMoveOrRotateNormStructureEvent = 18,
  EventProtocolResponseSSellNormStructureEvent = 19,
  EventProtocolResponseSUpgradeNormStructureEvent = 20,
  EventProtocolResponseSRetrieveCurrencyFromNormStructureEvent = 21,
  EventProtocolResponseSRefillStatWithDiamondsEvent = 22,
  EventProtocolResponseSFinishNormStructWaittimeWithDiamondsEvent = 23,
  EventProtocolResponseSNormStructWaitCompleteEvent = 24,
  EventProtocolResponseSRedeemMarketplaceEarningsEvent = 25,
  EventProtocolResponseSCritStructureActionEvent = 26,
  EventProtocolResponseSLoadPlayerCityEvent = 27,
  EventProtocolResponseSRetrieveStaticDataEvent = 28,
  EventProtocolResponseSQuestAcceptEvent = 29,
  EventProtocolResponseSUserQuestDetailsEvent = 30,
  EventProtocolResponseSQuestRedeemEvent = 31,
  EventProtocolResponseSPurchaseCityExpansionEvent = 32,
  EventProtocolResponseSExpansionWaitCompleteEvent = 33,
  EventProtocolResponseSRefillStatWaitCompleteEvent = 34,
  EventProtocolResponseSLevelUpEvent = 35,
  EventProtocolResponseSEnableApnsEvent = 36,
  EventProtocolResponseSPurchaseMarketplaceLicenseEvent = 37,
  EventProtocolResponseSUserCreateEvent = 38,
  EventProtocolResponseSEquipEquipmentEvent = 39,
  EventProtocolResponseSChangeUserLocationEvent = 40,
  EventProtocolResponseSLoadNeutralCityEvent = 41,
  EventProtocolResponseSRetrieveUsersForUserIdsEvent = 42,
  EventProtocolResponseSPostOnPlayerWallEvent = 43,
  EventProtocolResponseSRetrievePlayerWallPostsEvent = 44,
  EventProtocolResponseSEarnFreeDiamondsEvent = 45,
  EventProtocolResponseSReconnectEvent = 46,
  EventProtocolResponseSSubmitEquipsToBlacksmith = 48,
  EventProtocolResponseSForgeAttemptWaitComplete = 49,
  EventProtocolResponseSFinishForgeAttemptWaittimeWithDiamonds = 50,
  EventProtocolResponseSCollectForgeEquips = 51,
  EventProtocolResponseSCharacterModEvent = 52,
  EventProtocolResponseSRetrieveLeaderboardEvent = 53,
  EventProtocolResponseSSendGroupChatEvent = 54,
  EventProtocolResponseSPurchaseGroupChatEvent = 55,
  EventProtocolResponseSCreateClanEvent = 56,
  EventProtocolResponseSLeaveClanEvent = 57,
  EventProtocolResponseSRequestJoinClanEvent = 58,
  EventProtocolResponseSRetractRequestJoinClanEvent = 59,
  EventProtocolResponseSApproveOrRejectRequestToJoinClanEvent = 60,
  EventProtocolResponseSTransferClanOwnership = 61,
  EventProtocolResponseSRetrieveClanInfoEvent = 62,
  EventProtocolResponseSChangeClanDescriptionEvent = 63,
  EventProtocolResponseSPostOnClanBulletinEvent = 64,
  EventProtocolResponseSRetrieveClanBulletinPostsEvent = 65,
  EventProtocolResponseSBootPlayerFromClanEvent = 66,
  EventProtocolResponseSRetrieveThreeCardMonteEvent = 67,
  EventProtocolResponseSPlayThreeCardMonteEvent = 68,
  EventProtocolResponseSBeginGoldmineTimerEvent = 69,
  EventProtocolResponseSCollectFromGoldmineEvent = 70,
  EventProtocolResponseSPickLockBoxEvent = 71,
  EventProtocolResponseSBossActionEvent = 72,
  EventProtocolResponseSBeginClanTowerWar = 73,
  EventProtocolResponseSUpgradeClanTierEvent = 74,
  EventProtocolResponseSConcedeClanTowerWarEvent = 75,
  EventProtocolResponseSChangedClanTowerEvent = 76,
  EventProtocolResponseSRetrieveLeaderboardRankingsEvent = 77,
  EventProtocolResponseSUpdateClientUserEvent = 101,
  EventProtocolResponseSQuestCompleteEvent = 102,
  EventProtocolResponseSReferralCodeUsedEvent = 103,
  EventProtocolResponseSPurgeStaticDataEvent = 104,
  EventProtocolResponseSReceivedGroupChatEvent = 105,
  EventProtocolResponseSSendAdminMessageEvent = 106,
  EventProtocolResponseSGeneralNotificationEvent = 107,
} EventProtocolResponse;

BOOL EventProtocolResponseIsValidValue(EventProtocolResponse value);


@interface ProtocolsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

