// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Protocols.pb.h"

@implementation ProtocolsRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [ProtocolsRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    [EventRoot registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

BOOL EventProtocolRequestIsValidValue(EventProtocolRequest value) {
  switch (value) {
    case EventProtocolRequestCChatEvent:
    case EventProtocolRequestCBattleEvent:
    case EventProtocolRequestCVaultEvent:
    case EventProtocolRequestCTaskActionEvent:
    case EventProtocolRequestCClericHealEvent:
    case EventProtocolRequestCStartupEvent:
    case EventProtocolRequestCRetrieveTasksForCityEvent:
    case EventProtocolRequestCRetrieveQuestsForCityEvent:
    case EventProtocolRequestCRetrieveEquipsForArmoryEvent:
    case EventProtocolRequestCArmoryEvent:
    case EventProtocolRequestCInAppPurchaseEvent:
    case EventProtocolRequestCRetrieveCurrentMarketplacePostsEvent:
    case EventProtocolRequestCPostToMarketplaceEvent:
    case EventProtocolRequestCRetractPostFromMarketplaceEvent:
    case EventProtocolRequestCPurchaseFromMarketplaceEvent:
    case EventProtocolRequestCUseSkillPointEvent:
    case EventProtocolRequestCGenerateAttackListEvent:
      return YES;
    default:
      return NO;
  }
}
BOOL EventProtocolResponseIsValidValue(EventProtocolResponse value) {
  switch (value) {
    case EventProtocolResponseSChatEvent:
    case EventProtocolResponseSBattleEvent:
    case EventProtocolResponseSVaultEvent:
    case EventProtocolResponseSTaskActionEvent:
    case EventProtocolResponseSClericHealEvent:
    case EventProtocolResponseSStartupEvent:
    case EventProtocolResponseSRetrieveTasksForCityEvent:
    case EventProtocolResponseSRetrieveQuestsForCityEvent:
    case EventProtocolResponseSRetrieveEquipsForArmoryEvent:
    case EventProtocolResponseSArmoryEvent:
    case EventProtocolResponseSInAppPurchaseEvent:
    case EventProtocolResponseSRetrieveCurrentMarketplacePostsEvent:
    case EventProtocolResponseSPostToMarketplaceEvent:
    case EventProtocolResponseSRetractPostFromMarketplaceEvent:
    case EventProtocolResponseSPurchaseFromMarketplaceEvent:
    case EventProtocolResponseSUseSkillPointEvent:
    case EventProtocolResponseSGenerateAttackListEvent:
    case EventProtocolResponseSLevelUpEvent:
    case EventProtocolResponseSUpdateClientUserEvent:
      return YES;
    default:
      return NO;
  }
}
