// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "Event.pb.h"

@class ArmoryRequestProto;
@class ArmoryRequestProto_Builder;
@class ArmoryResponseProto;
@class ArmoryResponseProto_Builder;
@class BattleRequestProto;
@class BattleRequestProto_Builder;
@class BattleResponseProto;
@class BattleResponseProto_Builder;
@class BuildStructJobProto;
@class BuildStructJobProto_Builder;
@class ChangeUserLocationRequestProto;
@class ChangeUserLocationRequestProto_Builder;
@class ChangeUserLocationResponseProto;
@class ChangeUserLocationResponseProto_Builder;
@class ChatRequestProto;
@class ChatRequestProto_Builder;
@class ChatResponseProto;
@class ChatResponseProto_Builder;
@class CoordinateProto;
@class CoordinateProto_Builder;
@class CriticalStructureActionRequestProto;
@class CriticalStructureActionRequestProto_Builder;
@class CriticalStructureActionResponseProto;
@class CriticalStructureActionResponseProto_Builder;
@class DefeatTypeJobProto;
@class DefeatTypeJobProto_Builder;
@class DialogueProto;
@class DialogueProto_Builder;
@class DialogueProto_SpeechSegmentProto;
@class DialogueProto_SpeechSegmentProto_Builder;
@class EarnFreeDiamondsRequestProto;
@class EarnFreeDiamondsRequestProto_Builder;
@class EarnFreeDiamondsResponseProto;
@class EarnFreeDiamondsResponseProto_Builder;
@class EnableAPNSRequestProto;
@class EnableAPNSRequestProto_Builder;
@class EnableAPNSResponseProto;
@class EnableAPNSResponseProto_Builder;
@class EquipEquipmentRequestProto;
@class EquipEquipmentRequestProto_Builder;
@class EquipEquipmentResponseProto;
@class EquipEquipmentResponseProto_Builder;
@class ExpansionWaitCompleteRequestProto;
@class ExpansionWaitCompleteRequestProto_Builder;
@class ExpansionWaitCompleteResponseProto;
@class ExpansionWaitCompleteResponseProto_Builder;
@class FinishNormStructWaittimeWithDiamondsRequestProto;
@class FinishNormStructWaittimeWithDiamondsRequestProto_Builder;
@class FinishNormStructWaittimeWithDiamondsResponseProto;
@class FinishNormStructWaittimeWithDiamondsResponseProto_Builder;
@class FullCityProto;
@class FullCityProto_Builder;
@class FullEquipProto;
@class FullEquipProto_Builder;
@class FullMarketplacePostProto;
@class FullMarketplacePostProto_Builder;
@class FullQuestProto;
@class FullQuestProto_Builder;
@class FullStructureProto;
@class FullStructureProto_Builder;
@class FullTaskProto;
@class FullTaskProto_Builder;
@class FullTaskProto_FullTaskEquipReqProto;
@class FullTaskProto_FullTaskEquipReqProto_Builder;
@class FullUserCityExpansionDataProto;
@class FullUserCityExpansionDataProto_Builder;
@class FullUserCityProto;
@class FullUserCityProto_Builder;
@class FullUserCritstructProto;
@class FullUserCritstructProto_Builder;
@class FullUserEquipProto;
@class FullUserEquipProto_Builder;
@class FullUserProto;
@class FullUserProto_Builder;
@class FullUserQuestDataLargeProto;
@class FullUserQuestDataLargeProto_Builder;
@class FullUserStructureProto;
@class FullUserStructureProto_Builder;
@class GenerateAttackListRequestProto;
@class GenerateAttackListRequestProto_Builder;
@class GenerateAttackListResponseProto;
@class GenerateAttackListResponseProto_Builder;
@class InAppPurchaseRequestProto;
@class InAppPurchaseRequestProto_Builder;
@class InAppPurchaseResponseProto;
@class InAppPurchaseResponseProto_Builder;
@class LevelUpRequestProto;
@class LevelUpRequestProto_Builder;
@class LevelUpResponseProto;
@class LevelUpResponseProto_Builder;
@class LoadNeutralCityRequestProto;
@class LoadNeutralCityRequestProto_Builder;
@class LoadNeutralCityResponseProto;
@class LoadNeutralCityResponseProto_Builder;
@class LoadPlayerCityRequestProto;
@class LoadPlayerCityRequestProto_Builder;
@class LoadPlayerCityResponseProto;
@class LoadPlayerCityResponseProto_Builder;
@class LocationProto;
@class LocationProto_Builder;
@class MinimumUserBuildStructJobProto;
@class MinimumUserBuildStructJobProto_Builder;
@class MinimumUserDefeatTypeJobProto;
@class MinimumUserDefeatTypeJobProto_Builder;
@class MinimumUserPossessEquipJobProto;
@class MinimumUserPossessEquipJobProto_Builder;
@class MinimumUserProto;
@class MinimumUserProto_Builder;
@class MinimumUserQuestTaskProto;
@class MinimumUserQuestTaskProto_Builder;
@class MinimumUserTaskProto;
@class MinimumUserTaskProto_Builder;
@class MinimumUserUpgradeStructJobProto;
@class MinimumUserUpgradeStructJobProto_Builder;
@class MoveOrRotateNormStructureRequestProto;
@class MoveOrRotateNormStructureRequestProto_Builder;
@class MoveOrRotateNormStructureResponseProto;
@class MoveOrRotateNormStructureResponseProto_Builder;
@class NeutralCityElementProto;
@class NeutralCityElementProto_Builder;
@class NormStructWaitCompleteRequestProto;
@class NormStructWaitCompleteRequestProto_Builder;
@class NormStructWaitCompleteResponseProto;
@class NormStructWaitCompleteResponseProto_Builder;
@class PlayerWallPostProto;
@class PlayerWallPostProto_Builder;
@class PossessEquipJobProto;
@class PossessEquipJobProto_Builder;
@class PostOnPlayerWallRequestProto;
@class PostOnPlayerWallRequestProto_Builder;
@class PostOnPlayerWallResponseProto;
@class PostOnPlayerWallResponseProto_Builder;
@class PostToMarketplaceRequestProto;
@class PostToMarketplaceRequestProto_Builder;
@class PostToMarketplaceResponseProto;
@class PostToMarketplaceResponseProto_Builder;
@class PurchaseCityExpansionRequestProto;
@class PurchaseCityExpansionRequestProto_Builder;
@class PurchaseCityExpansionResponseProto;
@class PurchaseCityExpansionResponseProto_Builder;
@class PurchaseFromMarketplaceRequestProto;
@class PurchaseFromMarketplaceRequestProto_Builder;
@class PurchaseFromMarketplaceResponseProto;
@class PurchaseFromMarketplaceResponseProto_Builder;
@class PurchaseMarketplaceLicenseRequestProto;
@class PurchaseMarketplaceLicenseRequestProto_Builder;
@class PurchaseMarketplaceLicenseResponseProto;
@class PurchaseMarketplaceLicenseResponseProto_Builder;
@class PurchaseNormStructureRequestProto;
@class PurchaseNormStructureRequestProto_Builder;
@class PurchaseNormStructureResponseProto;
@class PurchaseNormStructureResponseProto_Builder;
@class PurgeClientStaticDataResponseProto;
@class PurgeClientStaticDataResponseProto_Builder;
@class QuestAcceptRequestProto;
@class QuestAcceptRequestProto_Builder;
@class QuestAcceptResponseProto;
@class QuestAcceptResponseProto_Builder;
@class QuestCompleteResponseProto;
@class QuestCompleteResponseProto_Builder;
@class QuestRedeemRequestProto;
@class QuestRedeemRequestProto_Builder;
@class QuestRedeemResponseProto;
@class QuestRedeemResponseProto_Builder;
@class RedeemMarketplaceEarningsRequestProto;
@class RedeemMarketplaceEarningsRequestProto_Builder;
@class RedeemMarketplaceEarningsResponseProto;
@class RedeemMarketplaceEarningsResponseProto_Builder;
@class ReferralCodeUsedResponseProto;
@class ReferralCodeUsedResponseProto_Builder;
@class RefillStatWaitCompleteRequestProto;
@class RefillStatWaitCompleteRequestProto_Builder;
@class RefillStatWaitCompleteResponseProto;
@class RefillStatWaitCompleteResponseProto_Builder;
@class RefillStatWithDiamondsRequestProto;
@class RefillStatWithDiamondsRequestProto_Builder;
@class RefillStatWithDiamondsResponseProto;
@class RefillStatWithDiamondsResponseProto_Builder;
@class RetractMarketplacePostRequestProto;
@class RetractMarketplacePostRequestProto_Builder;
@class RetractMarketplacePostResponseProto;
@class RetractMarketplacePostResponseProto_Builder;
@class RetrieveCurrencyFromNormStructureRequestProto;
@class RetrieveCurrencyFromNormStructureRequestProto_Builder;
@class RetrieveCurrencyFromNormStructureResponseProto;
@class RetrieveCurrencyFromNormStructureResponseProto_Builder;
@class RetrieveCurrentMarketplacePostsRequestProto;
@class RetrieveCurrentMarketplacePostsRequestProto_Builder;
@class RetrieveCurrentMarketplacePostsResponseProto;
@class RetrieveCurrentMarketplacePostsResponseProto_Builder;
@class RetrievePlayerWallPostsRequestProto;
@class RetrievePlayerWallPostsRequestProto_Builder;
@class RetrievePlayerWallPostsResponseProto;
@class RetrievePlayerWallPostsResponseProto_Builder;
@class RetrieveStaticDataForShopRequestProto;
@class RetrieveStaticDataForShopRequestProto_Builder;
@class RetrieveStaticDataForShopResponseProto;
@class RetrieveStaticDataForShopResponseProto_Builder;
@class RetrieveStaticDataRequestProto;
@class RetrieveStaticDataRequestProto_Builder;
@class RetrieveStaticDataResponseProto;
@class RetrieveStaticDataResponseProto_Builder;
@class RetrieveTasksForCityRequestProto;
@class RetrieveTasksForCityRequestProto_Builder;
@class RetrieveTasksForCityResponseProto;
@class RetrieveTasksForCityResponseProto_Builder;
@class RetrieveUserEquipForUserRequestProto;
@class RetrieveUserEquipForUserRequestProto_Builder;
@class RetrieveUserEquipForUserResponseProto;
@class RetrieveUserEquipForUserResponseProto_Builder;
@class RetrieveUsersForUserIdsRequestProto;
@class RetrieveUsersForUserIdsRequestProto_Builder;
@class RetrieveUsersForUserIdsResponseProto;
@class RetrieveUsersForUserIdsResponseProto_Builder;
@class SellNormStructureRequestProto;
@class SellNormStructureRequestProto_Builder;
@class SellNormStructureResponseProto;
@class SellNormStructureResponseProto_Builder;
@class StartupRequestProto;
@class StartupRequestProto_Builder;
@class StartupResponseProto;
@class StartupResponseProto_AttackedNotificationProto;
@class StartupResponseProto_AttackedNotificationProto_Builder;
@class StartupResponseProto_Builder;
@class StartupResponseProto_MarketplacePostPurchasedNotificationProto;
@class StartupResponseProto_MarketplacePostPurchasedNotificationProto_Builder;
@class StartupResponseProto_ReferralNotificationProto;
@class StartupResponseProto_ReferralNotificationProto_Builder;
@class StartupResponseProto_StartupConstants;
@class StartupResponseProto_StartupConstants_AnimatedSpriteOffsetProto;
@class StartupResponseProto_StartupConstants_AnimatedSpriteOffsetProto_Builder;
@class StartupResponseProto_StartupConstants_BattleConstants;
@class StartupResponseProto_StartupConstants_BattleConstants_Builder;
@class StartupResponseProto_StartupConstants_Builder;
@class StartupResponseProto_StartupConstants_FormulaConstants;
@class StartupResponseProto_StartupConstants_FormulaConstants_Builder;
@class StartupResponseProto_TutorialConstants;
@class StartupResponseProto_TutorialConstants_Builder;
@class StartupResponseProto_TutorialConstants_FullTutorialQuestProto;
@class StartupResponseProto_TutorialConstants_FullTutorialQuestProto_Builder;
@class TaskActionRequestProto;
@class TaskActionRequestProto_Builder;
@class TaskActionResponseProto;
@class TaskActionResponseProto_Builder;
@class UpdateClientUserResponseProto;
@class UpdateClientUserResponseProto_Builder;
@class UpgradeNormStructureRequestProto;
@class UpgradeNormStructureRequestProto_Builder;
@class UpgradeNormStructureResponseProto;
@class UpgradeNormStructureResponseProto_Builder;
@class UpgradeStructJobProto;
@class UpgradeStructJobProto_Builder;
@class UseSkillPointRequestProto;
@class UseSkillPointRequestProto_Builder;
@class UseSkillPointResponseProto;
@class UseSkillPointResponseProto_Builder;
@class UserCreateRequestProto;
@class UserCreateRequestProto_Builder;
@class UserCreateResponseProto;
@class UserCreateResponseProto_Builder;
@class UserQuestDetailsRequestProto;
@class UserQuestDetailsRequestProto_Builder;
@class UserQuestDetailsResponseProto;
@class UserQuestDetailsResponseProto_Builder;
@class VaultRequestProto;
@class VaultRequestProto_Builder;
@class VaultResponseProto;
@class VaultResponseProto_Builder;
typedef enum {
  EventProtocolRequestCChatEvent = 0,
  EventProtocolRequestCBattleEvent = 1,
  EventProtocolRequestCVaultEvent = 2,
  EventProtocolRequestCTaskActionEvent = 3,
  EventProtocolRequestCRetrieveUserEquipForUser = 4,
  EventProtocolRequestCStartupEvent = 5,
  EventProtocolRequestCRetrieveStaticDataForShopEvent = 8,
  EventProtocolRequestCArmoryEvent = 9,
  EventProtocolRequestCInAppPurchaseEvent = 10,
  EventProtocolRequestCRetrieveCurrentMarketplacePostsEvent = 11,
  EventProtocolRequestCPostToMarketplaceEvent = 12,
  EventProtocolRequestCRetractPostFromMarketplaceEvent = 13,
  EventProtocolRequestCPurchaseFromMarketplaceEvent = 14,
  EventProtocolRequestCUseSkillPointEvent = 15,
  EventProtocolRequestCGenerateAttackListEvent = 16,
  EventProtocolRequestCPurchaseNormStructureEvent = 17,
  EventProtocolRequestCMoveOrRotateNormStructureEvent = 18,
  EventProtocolRequestCSellNormStructureEvent = 19,
  EventProtocolRequestCUpgradeNormStructureEvent = 20,
  EventProtocolRequestCRetrieveCurrencyFromNormStructureEvent = 21,
  EventProtocolRequestCRefillStatWithDiamondsEvent = 22,
  EventProtocolRequestCFinishNormStructWaittimeWithDiamondsEvent = 23,
  EventProtocolRequestCNormStructWaitCompleteEvent = 24,
  EventProtocolRequestCRedeemMarketplaceEarningsEvent = 25,
  EventProtocolRequestCCritStructureActionEvent = 26,
  EventProtocolRequestCLoadPlayerCityEvent = 27,
  EventProtocolRequestCRetrieveStaticDataEvent = 28,
  EventProtocolRequestCQuestAcceptEvent = 29,
  EventProtocolRequestCUserQuestDetailsEvent = 30,
  EventProtocolRequestCQuestRedeemEvent = 31,
  EventProtocolRequestCPurchaseCityExpansionEvent = 32,
  EventProtocolRequestCExpansionWaitCompleteEvent = 33,
  EventProtocolRequestCRefillStatWaitCompleteEvent = 34,
  EventProtocolRequestCLevelUpEvent = 35,
  EventProtocolRequestCEnableApnsEvent = 36,
  EventProtocolRequestCPurchaseMarketplaceLicenseEvent = 37,
  EventProtocolRequestCUserCreateEvent = 38,
  EventProtocolRequestCEquipEquipmentEvent = 39,
  EventProtocolRequestCChangeUserLocationEvent = 40,
  EventProtocolRequestCLoadNeutralCityEvent = 41,
  EventProtocolRequestCRetrieveUsersForUserIdsEvent = 42,
  EventProtocolRequestCPostOnPlayerWall = 43,
  EventProtocolRequestCRetrievePlayerWallPosts = 44,
  EventProtocolRequestCEarnFreeDiamonds = 45,
  EventProtocolRequestAAdminUpdate = 300,
} EventProtocolRequest;

BOOL EventProtocolRequestIsValidValue(EventProtocolRequest value);

typedef enum {
  EventProtocolResponseSChatEvent = 0,
  EventProtocolResponseSBattleEvent = 1,
  EventProtocolResponseSVaultEvent = 2,
  EventProtocolResponseSTaskActionEvent = 3,
  EventProtocolResponseSRetrieveUserEquipForUser = 4,
  EventProtocolResponseSStartupEvent = 5,
  EventProtocolResponseSRetrieveStaticDataForShopEvent = 8,
  EventProtocolResponseSArmoryEvent = 9,
  EventProtocolResponseSInAppPurchaseEvent = 10,
  EventProtocolResponseSRetrieveCurrentMarketplacePostsEvent = 11,
  EventProtocolResponseSPostToMarketplaceEvent = 12,
  EventProtocolResponseSRetractPostFromMarketplaceEvent = 13,
  EventProtocolResponseSPurchaseFromMarketplaceEvent = 14,
  EventProtocolResponseSUseSkillPointEvent = 15,
  EventProtocolResponseSGenerateAttackListEvent = 16,
  EventProtocolResponseSPurchaseNormStructureEvent = 17,
  EventProtocolResponseSMoveOrRotateNormStructureEvent = 18,
  EventProtocolResponseSSellNormStructureEvent = 19,
  EventProtocolResponseSUpgradeNormStructureEvent = 20,
  EventProtocolResponseSRetrieveCurrencyFromNormStructureEvent = 21,
  EventProtocolResponseSRefillStatWithDiamondsEvent = 22,
  EventProtocolResponseSFinishNormStructWaittimeWithDiamondsEvent = 23,
  EventProtocolResponseSNormStructWaitCompleteEvent = 24,
  EventProtocolResponseSRedeemMarketplaceEarningsEvent = 25,
  EventProtocolResponseSCritStructureActionEvent = 26,
  EventProtocolResponseSLoadPlayerCityEvent = 27,
  EventProtocolResponseSRetrieveStaticDataEvent = 28,
  EventProtocolResponseSQuestAcceptEvent = 29,
  EventProtocolResponseSUserQuestDetailsEvent = 30,
  EventProtocolResponseSQuestRedeemEvent = 31,
  EventProtocolResponseSPurchaseCityExpansionEvent = 32,
  EventProtocolResponseSExpansionWaitCompleteEvent = 33,
  EventProtocolResponseSRefillStatWaitCompleteEvent = 34,
  EventProtocolResponseSLevelUpEvent = 35,
  EventProtocolResponseSEnableApnsEvent = 36,
  EventProtocolResponseSPurchaseMarketplaceLicenseEvent = 37,
  EventProtocolResponseSUserCreateEvent = 38,
  EventProtocolResponseSEquipEquipmentEvent = 39,
  EventProtocolResponseSChangeUserLocationEvent = 40,
  EventProtocolResponseSLoadNeutralCityEvent = 41,
  EventProtocolResponseSRetrieveUsersForUserIdsEvent = 42,
  EventProtocolResponseSPostOnPlayerWall = 43,
  EventProtocolResponseSRetrievePlayerWallPosts = 44,
  EventProtocolResponseSEarnFreeDiamonds = 45,
  EventProtocolResponseSUpdateClientUserEvent = 51,
  EventProtocolResponseSQuestCompleteEvent = 52,
  EventProtocolResponseSReferralCodeUsedEvent = 53,
  EventProtocolResponseSPurgeStaticDataEvent = 54,
} EventProtocolResponse;

BOOL EventProtocolResponseIsValidValue(EventProtocolResponse value);


@interface ProtocolsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

